### ISSUE TITLE
Allow `subject` on index manifest

### ISSUE THREAD

**Issue by imjasonh** [opencontainers/image-spec#1002]
[Image Index](https://github.com/opencontainers/image-spec/blob/main/image-index.md) does not allow for a `subject`, while [Image](https://github.com/opencontainers/image-spec/blob/main/manifest.md) does.

I don't think we fully described why an index can't have a `subject` -- I remember it was related to garbage collection, but I still don't understand why an index referring to another manifest shouldn't be allowed.

At the very least can we document in the spec (or non-spec guidance?) why we made this decision?

@sudo-bmitch

**Comment by sudo-bmitch** [comment]
Yup, documentation is needed, but I'm not sure where to put it just yet (suggestions welcome). See this comment for the explanation: https://github.com/opencontainers/image-spec/issues/971#issuecomment-1304818968
