### ISSUE TITLE
[Manifest] Is Digest required or optional ?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#103]
In the spec: 
> digest string
> The digest of the content, as defined by the Registry V2 HTTP API Specificiation.

Other similar items such as schemaVersion and mediaType indicate if they are REQUIRED or OPTIONAL but item does not.

**Comment by stevvooe** [comment]
This should be required.

**Comment by RobDolinMS** [comment]
Thanks @stevvooe.  I've opened #112 to resolve this.

**Comment by stevvooe** [comment]
@RobDolinMS Re-opening until #112 is merged.
