### ISSUE TITLE
Schema validation is broken?

### ISSUE THREAD

**Issue by rchincha** [opencontainers/image-spec#1058]
For example ...

https://github.com/opencontainers/image-spec/blob/main/schema/manifest_test.go#L169

// expected failure: empty layer, expected at least one

However, per spec Layers can be empty?

**Comment by sudo-bmitch** [comment]
We've got the following "SHOULD": https://github.com/opencontainers/image-spec/blob/main/manifest.md#L61

And the last example shows how this can be followed for manifests that don't need any layers using a scratch descriptor:
https://github.com/opencontainers/image-spec/blob/main/manifest.md#L211

**Comment by rchincha** [comment]
Will close this and open an issue with conformance project.
