### ISSUE TITLE
[Manifest] Unclear if "should" intended as "SHOULD"

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#109]
>size int
> ...
>If the length of the retrieved content does not match the specified length, the content should not be trusted.

If intended as a recommendation, use "SHOULD" (ALL CAPS.)  
If not intended as a recommendation invoke RFC meaning, consider alternate wording.

**Comment by stevvooe** [comment]
I'm not even sure this is correct. The size is really there to support preallocation. Content verification should be done through digest.

**Comment by philips** [comment]
I think it is correct. This may protect against future length extension attacks.

**Comment by stevvooe** [comment]
Ok, this should be SHOULD, then.

I'm going to add [this](https://en.wikipedia.org/wiki/Length_extension_attack) to #111, as this question comes up all the time.

**Comment by philips** [comment]
confirmed fixed in #111
