### ISSUE TITLE
Request for Comments for v1.1.0 release

### ISSUE THREAD

**Issue by sajayantony** [opencontainers/image-spec#1093]
This issue serves as a tracking mechanism for collecting feedback from clients or registry operators. 

The primary objective of this issue is to allow implementors to provide their input and opinions within a tentative six-week time frame. During this period, implementors are encouraged to raise any blocking comments or issues related to the proposed changes. These comments and issues will be logged and monitored under the [v1.1.0 Milestone](https://github.com/opencontainers/image-spec/milestone/14).

Additionally, project maintainers and stakeholders are invited to show their support by providing a "Thumbs up" or an LGTM (Looks Good to Me) comment, indicating their endorsement for specific proposals. Such expressions of support are valuable for prioritizing and evaluating the importance of the proposed changes.

Please note that the duration of the six-week time frame is subject to adjustment. Any feedback or issues not explicitly tracked under the milestone will be considered for the subsequent milestone unless the maintainers agree to include them in the v1.1.0 milestone.

/cc @opencontainers/image-spec-maintainers

**Comment by jdolitsky** [comment]
![download](https://github.com/opencontainers/image-spec/assets/393494/3eaf9f76-f517-4503-a9f2-c0c72b4520c8)

**Comment by rchincha** [comment]
Thanks @sajayantony

"The primary objective of this issue is to allow implementors to provide their input and opinions within a tentative six-week time frame. During this period, implementors are encouraged to raise any blocking comments or issues related to the proposed changes. These comments and issues will be logged and monitored under the [v1.1.0 Milestone](https://github.com/opencontainers/image-spec/milestone/14)."

^ glad that we are refining the process - greatly improves ability to plan around OCI deliverables.

**Comment by rchincha** [comment]
Speaking for `zot` project, we already artifacts support merged into 2.0.0-rc5 and index support merged into `main` branch. We will cut another -rc release shortly.

**Comment by sudo-bmitch** [comment]
Putting on my [regclient](https://github.com/regclient/regclient/) hat for a moment:

I've added support for this in regclient and I'm just looking for registries to test the new distribution-spec APIs against and other clients to verify interoperability.

**Comment by northtyphoon** [comment]
For Azure Container Registry, the support for v1.1 RC3 has been rolled out worldwide on all Azure clouds. We are currently testing RC4 and will release it very soon.

**Comment by ChristianKniep** [comment]
Is there a condensed write-up of what changes with v1.1?

**Comment by shizhMSFT** [comment]
`oras-go` has released [`v2.2.1`](https://github.com/oras-project/oras-go/releases/tag/v2.2.1) with `image-spec` dependency bumped up to `v1.1.0-rc4`. Since `oras-go` has integrated `v1.1.0-rc1` and `v1.1.0-rc2` previously in its stable releases, `oras-go` will fully implement `v1.1.0-rc4` with maximum backward compatibility for `v1.1.0-rc1` and `v1.1.0-rc2`. This effort is tracked in https://github.com/oras-project/oras-go/issues/494 and is picked up by @Wwwsylvia. The compatibility for RC versions of `image-spec` is planned to be dropped in `oras-go v3`.

Since `oras` CLI depends on `oras-go`, the current releases of `oras` supports `image-spec v1.1.0-rc2`. The `oras` CLI will support `v1.1.0-rc4` once `oras-go` has fully implemented it. /cc @qweeah

**Comment by jdolitsky** [comment]
> Is there a condensed write-up of what changes with v1.1?

Not that I'm aware of. We should put this together and publish on the OCI blog: https://opencontainers.org/posts/blog/

Maybe people can share here any posts they have which describe the changes. This post I wrote a bit ago details the effect of these changes on a specific client (cosign): https://www.chainguard.dev/unchained/building-towards-oci-v1-1-support-in-cosign

**Comment by jdolitsky** [comment]
I've just opened this PR to add a blog post to outline the upcoming changes in image-spec & distribution-spec v1.1: https://github.com/opencontainers/opencontainers.org/pull/130

Maintainers - please help review and let me know if this reflects your understanding of the major changes and how to communicate them.

**Comment by sudo-bmitch** [comment]
Thanks @milosgajdos. Are there specific parts of the spec that may not get implemented by Docker Hub? And are there changes we should consider before the GA?

**Comment by jdolitsky** [comment]
Please see this blog post for a summary of the upcoming changes in image-spec & distribution-spec: https://opencontainers.org/posts/blog/2023-07-07-summary-of-upcoming-changes-in-oci-image-and-distribution-specs-v-1-1/

**Comment by shizhMSFT** [comment]
The `main` branch of [`oras-go`](https://github.com/oras-project/oras-go) is **up to date** with `image-spec v1.1.0-rc4` and `distribution-spec v1.1.0-rc3` by @Wwwsylvia. Those changes are planned to be published in the next [`v2.3.0`](https://github.com/oras-project/oras-go/milestone/14) release in early August.

[`oras`](https://github.com/oras-project/oras) CLI is being updated with the latest `oras-go` by @qweeah and the next stable release [`v1.1.0`](https://github.com/oras-project/oras/milestone/11) is planned around mid-August.

**Comment by sajayantony** [comment]
So try to keep lines between 80-120 but ensure that new sentences start on a new line?

**Comment by avtakkar** [comment]
At Azure Container Registry, adding to @northtyphoon 's previous [comment](https://github.com/opencontainers/image-spec/issues/1093#issuecomment-1624314980), we did internal testing and don't have any issue with the current RC4 version of the spec besides allowing an index without artifact type (#1106).

**Comment by sajayantony** [comment]
At this point from my side I see no blocking issue on image spec but there is a possible update on distribution to releax the artifact type requirement. Currently https://github.com/opencontainers/image-spec/pull/1109 is in preparation for v1.1.0 is in draft .

**Comment by shizhMSFT** [comment]
[`oras-go v2.3.0`](https://github.com/oras-project/oras-go/releases/tag/v2.3.0) and [`oras v1.1.0`](https://github.com/oras-project/oras/releases/tag/v1.1.0) are released and are compliant with `image-spec v1.1.0-rc4` and `distribution-spec v1.1.0-rc3`.

**Comment by sajayantony** [comment]
Closing this as there are no more outstanding items for release of v1.1 of image spec. 
All future items are targeted towards v1.2 milestone.
