### ISSUE TITLE
Could sha-3 be used for Checksum algorithm for container image?

### ISSUE THREAD

**Issue by mamoona-aslam** [opencontainers/image-spec#1103]
is it possbile to create Container image using sha-3?  if so how?  hats the procedure that this can be achieved?

**Comment by Getrichisaac** [comment]
Nice

**Comment by sudo-bmitch** [comment]
Deleting this since I don't think there's any specific change needed for image-spec. But feel free to keep the conversation going here if there's more that OCI can do.
