### ISSUE TITLE
index with `subject` but contains no `artifactType`

### ISSUE THREAD

**Issue by qweeah** [opencontainers/image-spec#1106]
OCI image spec 1.1.0-rc4 allows image index to have `subject`(updated in [this commit](https://github.com/opencontainers/image-spec/commit/c6854a626fb485c5a889cfe3ac9f3cd7e09dae60)) and `artifactType`(update in [this commit](https://github.com/opencontainers/image-spec/commit/749ea9a27d1eb44b5369ee7e8e296c7e99e3d2e5)). Since both fields are optional, it's possible that user can push an index with `subject` but no `artifactType` like below.

```mermaid
flowchart
index --subject--> image
```

Should we enforce the requirement on both fields like: if `subject` is presented, `artifactType` MUST be presented, otherwise the index is invalid?

**Comment by sudo-bmitch** [comment]
This is related to #1020 and #1077. CC @vbatts and @sajayantony from those PRs.

**Comment by qweeah** [comment]
> Is this stemming from the fact that the artifact Type is a MUST from the referrers API?

Yes.

>  if we want to support index in the referrers API

Good catch. Index with `subject` should be included in the referrers API, so what I suggest is: `artfactType` MUST present if `subject` presents.

**Comment by sajayantony** [comment]
From the call today there were multiple options discussed of from making `artifactType` a MUST, to making it optional in the referrers. The second option sounded like there was more acceptance which would be a change to the distribution spec. 
There needs to be a follow up PR on the distribution spec and it also means that there is no PR expected for the image spec at this point.

**Comment by qweeah** [comment]
> to making it optional in the referrers. The second option sounded like there was more acceptance which would be a change to the distribution spec.

Can you help elaborate on what's the motivation for this preference of making it optional?  Will it also be applied to image referrer descriptors?

**Comment by qweeah** [comment]
Closing as it should be fixed by making artifact type optional in the Referrers API in distribution-spec. Let's continue the discussion in https://github.com/opencontainers/distribution-spec/issues/458

**Comment by sudo-bmitch** [comment]
Wouldn't this be a change to the json spec, or would the referrers API be able to return content that's not image-spec compliant?
