### ISSUE TITLE
[Manifest] Is Config required or optional?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#113]
Similar to #103, the `config` object is not indicated as REQUIRED or OPTIONAL.

**Comment by philips** [comment]
I believe it is required.

**Comment by RobDolinMS** [comment]
Tagging @stevvooe who weighed-in on #103 to weigh-in on this as well.

**Comment by stevvooe** [comment]
These are required on both the manifest and image (in serialization.md, needs a better name).

Unless, there is an example where these wouldn't be required.

**Comment by philips** [comment]
@RobDolinMS want to put up the PR?

**Comment by RobDolinMS** [comment]
Thanks guys.  I've opened PR #119

**Comment by philips** [comment]
Closing this out and moving discussion to #119.

**Comment by RobDolinMS** [comment]
Considering this resolved as PR #119 has been merged.
