### ISSUE TITLE
Reporting Security Issues

### ISSUE THREAD

**Issue by Nirvanasake** [opencontainers/image-spec#1155]

**Comment by tianon** [comment]
Please see https://github.com/opencontainers/.github/blob/main/SECURITY.md ❤️

**Comment by Nirvanasake** [comment]
Hello thank you so much . 
I have not previously experiences but we have been attacked last two months all activite browsers chrome all mdm devices plus VPS servers nonstop doing swaggering 
After 10 days later finally online again but I have been pointed targeted finally I am able to committee with my devices even I can google it not says 404 
It's has been chrome extension via remove ssl certificate then using language colour picked then framework plus bundle attackers but I believe I manage to announce my self back to from zombie or dead plus so can please advise me which steps should be followings 
Devices ssl and crobted browsers 
And block extensionss and removed all store ids 
Then re passwords all devices plus  wifis but they can come back hunting me again it's very frustrating and financially has been so damaged. They are cut me out previously pulls staff but I cannot login git accounts not logging people are pissed of but I cannot login 

Please send me few suggestions thanks
