### ISSUE TITLE
The problem about index: REQUIRED or OPTIONAL?

### ISSUE THREAD

**Issue by Zheaoli** [opencontainers/image-spec#1176]
I have noticed that we describe the index as an optional in here

https://github.com/opencontainers/image-spec/blob/f5f87016de46439ccf91b5381cf76faaae2bc28f/spec.md?plain=1#L5

But we describe that the index.json is REQUIRED in here

https://github.com/opencontainers/image-spec/blob/f5f87016de46439ccf91b5381cf76faaae2bc28f/image-layout.md?plain=1#L28

Is there a conflict description?

FYI I have noticed that the OPTIONAL is added in this PR https://github.com/opencontainers/image-spec/pull/455/files

cc @coolljt0725

**Comment by michaelb990** [comment]
The `image-layout.md` describes the way to organize an image as a directory structure. The `index.json` file described in the Image Layout spec is specific to the on-disk representation of an image and isn't the same as an "image index" described in the `image-index.md` file. Perhaps it's worth disambiguating the `index.json` file in the `image-layout.md` specification.

**Comment by sudo-bmitch** [comment]
I'm closing this out due to a lack of activity. If there is more detail to add or if there are answers to the question above, feel free to follow up in the issue.
