### ISSUE TITLE
performance: consider supporting "blake3-256:<ref>" digests?

### ISSUE THREAD

**Issue by rchincha** [opencontainers/image-spec#1193]
https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf
^ blake3 is fast (but newer crypto) 

Would help with building and verifying images, especially large images.

**Comment by sudo-bmitch** [comment]
I believe this is a duplicate of #819.

**Comment by tianon** [comment]
Agreed 👍

**Comment by rchincha** [comment]
The motivation for suggesting blake3 here is mainly for perf reasons. If there is another hash - secure and faster than sha2, that is something we should consider.

**Comment by tianon** [comment]
I think there are other benefits to blake3, but I'm far from the expert and I think #819 (the prior blake3 discussion which already has a lot of interesting discussion and useful links in it) is a more appropriate place to discuss further.
