### ISSUE TITLE
[ReadMe] Base layer term seems overloaded

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#120]
In ReadMe.md, there are references to "base layer" but seems to be an overloaded use of the term:
> The high level components of the spec include:
> •An image manifest and filesystem serialization (base layer)
> •A process of hashing the image format for integrity and content-addressing (base layer)
> •Signatures that are based on signing image content address (optional layer)
> •Naming that is federated based on DNS and can be delegated (optional layer)

Maybe change: 
"base layer" --> REQUIRED
"optional layer" --> OPTIONAL

**Comment by philips** [comment]
Base layer is a term from the OCI Scope Table. I will try and add a clarifying statement but we should use the same language: https://www.opencontainers.org/governance/oci-scope-table

**Comment by philips** [comment]
Fixed in https://github.com/opencontainers/image-spec/pull/124

**Comment by RobDolinMS** [comment]
@philips Thanks for the quick action on this. 

It's a relatively minor nit, but I think REQUIRED and OPTIONAL are more generally understood than "base layer" and "optional layer" (though I now better understand the context after being pointed to the opening sentences defining these in the [OCI Scope Table](https://www.opencontainers.org/governance/oci-scope-table).)

Would you (or others) have any concern if I submitted a PR in that direction?

**Comment by philips** [comment]
@RobDolinMS Honestly I would rather just fix the Scope Table to use this standard language. :(

If you can add clarifying information to this project I would take a PR though.
