### ISSUE TITLE
manifest: Why use schemaVersion == 2

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#121]
It might be good to have some additional guidance around schemaVersion
> schemaVersion  int
> This REQUIRED property specifies the image manifest schema version. This schema uses the version  2 .

For example, is this intended to align with major and minor versions?  i.e. v0.1 ==1, v0.2 ==2, etc.?

**Comment by stevvooe** [comment]
@RobDolinMS This is an artifact we have in place for compatibility with older versions of docker. It reflects a sub-versioning over the representation of the schema over time, corresponding with the move to mediatypes to do proper version resolution.

Keeping it in the OCI specification is a hedge for compatibility. With some experimentation, it is possible we can remove, but we should confirm that first. The specification likely deserves some language explaining this.

The value of `schemaVersion` will never go above 2.

**Comment by philips** [comment]
@RobDolinMS want to take a swing at adding the language?
