### ISSUE TITLE
Proposal to Expand architecture Field for Feature Levels in OCI Manifests

### ISSUE THREAD

**Issue by sfxworks** [opencontainers/image-spec#1223]
## Description

The current OCI Image Specification defines `architecture` values such as `amd64`, `arm64`, and others, along with an optional `variant` field. However, as modern workloads increasingly depend on advanced CPU capabilities, such as AVX512, there is a need to extend the `architecture` field itself to reflect **feature-level distinctions**. This would allow more granular and performance-aware image selection, especially for scenarios like AI workloads, ML inference, and scientific computing, where performance is tied to CPU instruction sets.

Rather than specifying individual features (e.g., `AVX512F`, `AVX512DQ`), this proposal suggests expanding the `architecture` field to include **feature levels**. For example, `amd64-v4` could represent a subset of `amd64` with AVX512 and related optimizations.

---

### 1. Modern AI and HPC Workloads
- Applications like TensorFlow or PyTorch benefit significantly from AVX512 instructions, which are only available on newer x86-64 CPUs.
- By extending `architecture` to `amd64-v4`, OCI manifests could allow container runtimes to automatically pull optimized images for these workloads.

### 2. Feature-Level Differentiation Without Complexity
- Instead of listing specific features (e.g., `AVX512BW`, `AVX512CD`), feature levels like `amd64-v4` offer a cleaner abstraction and align with GCC’s x86-64 feature levels.
- This approach simplifies container image creation while ensuring backward compatibility.

### 3. Fallback for Compatibility
- Multi-platform manifests could include:
  - `amd64-v4` for feature-rich nodes.
  - `amd64` as a fallback for older CPUs.

### 4. Standardization Across Ecosystems
- Aligns with efforts in GCC and compilers to standardize feature levels (e.g., `x86-64-v4`, `x86-64-v3`).
- Simplifies workload scheduling in environments like Kubernetes by allowing containers to advertise compatibility with feature levels.

---

## Proposed Change

Expand the `architecture` field in OCI Image Manifests to include **feature levels** as part of the `architecture` value itself.

### Example Manifest Update:
```json
{
  "manifests": [
    {
      "platform": {
        "architecture": "amd64-v4",
        "os": "linux"
      },
      "digest": "sha256:optimized-image"
    },
    {
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "digest": "sha256:generic-image"
    }
  ]
}
```

### Key Points
1. **Backward Compatibility**:
   - Runtimes unaware of `amd64-v4` would fall back to `amd64`.
2. **Alignment with Compiler Standards**:
   - The `v4` suffix mirrors GCC x86-64 feature levels (`v2`, `v3`, `v4`), making it intuitive for developers.
3. **No Need for Explicit Features**:
   - Avoids introducing a `features` array, which could lead to fragmentation and complexity.

---

## Rationale for Architecture Expansion

Expanding `architecture` aligns with the growing need to optimize container workloads for modern hardware:

1. **Simplified Workload Optimization**:
   - Developers and image authors can target architectures like `amd64-v4` without managing individual features.

2. **AI and HPC Workloads**:
   - As AVX512 is critical for AI performance, containers can transparently leverage hardware-optimized images without explicit runtime intervention.

3. **Cleaner Abstraction**:
   - Defining generalized levels (`amd64-v4`) avoids the pitfalls of overly specific feature lists, which can lead to compatibility issues.

---

### 1. For Image Authors
- Simplifies the creation of multi-architecture images optimized for hardware capabilities.
- Enables a single manifest to target both feature-rich and generic nodes.

### 2. For Runtimes
- Requires minor changes to CRI-O, containerd, and Podman to respect extended `architecture` fields.
- Fallback behavior is already well-supported via multi-platform manifests.

### 3. For Ecosystems
- Standardizes how feature-level optimizations are handled, aligning container workloads with advancements in hardware and software (e.g., GCC, LLVM).

---

### 1. Use `variant` Field
- While the `variant` field could theoretically encode feature levels, this usage is non-standard and could cause compatibility issues.

### 2. Add a `features` Field
- Listing individual features (e.g., `AVX512F`, `AVX512DQ`) introduces unnecessary complexity and risks fragmentation.

---

## References

- [GCC x86-64 Feature Levels](https://www.phoronix.com/news/GCC-11-x86-64-Feature-Levels)
- [Kubernetes Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery)

**Comment by sudo-bmitch** [comment]
Using the variant is currently part of the spec, and supported by many tools (they may require updates to detect the latest versions). See https://github.com/opencontainers/image-spec/blob/main/image-index.md#platform-variants

**Comment by sfxworks** [comment]
NEAT!
