### ISSUE TITLE
descriptor: discuss the reserved fields

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#125]
The descriptor spec has a section on reserved fields which we really don't have great precedent for. This issue is to discuss the formalization or removal of the "reserved" concept across the spec. 

Previous discussions:
https://github.com/opencontainers/image-spec/pull/111#discussion-diff-65659259
https://github.com/opencontainers/image-spec/pull/111#discussion-diff-65752637

**Comment by wking** [comment]
On Tue, Jun 07, 2016 at 04:33:21PM -0700, Brandon Philips wrote:
> Previous discussions:
> https://github.com/opencontainers/image-spec/pull/111#discussion-diff-65659259
> https://github.com/opencontainers/image-spec/pull/111#discussion-diff-65752637

And also in [1], where I argue for for JSON-LD to get explicit,
per-property semantics.

[1]: https://github.com/opencontainers/image-spec/pull/111#discussion_r65468737
