### ISSUE TITLE
[1.0.0] Expand on tar format and whiteouts

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#127]
From the [mailing-list thread on v1.0.0](https://groups.google.com/a/opencontainers.org/d/msg/dev/NPBMTrniG8Q/BS6adHTaAgAJ)

**Comment by philips** [comment]
@stevvooe Putting need info on this because I don't know exactly what more information you want to see in the spec.

**Comment by stevvooe** [comment]
@philips My plan was to spend time filing these bugs today or tomorrow.

**Comment by vbatts** [comment]
Right on. Feel free to edit the title and description of the issue

**Comment by philips** [comment]
Moved to #130

**Comment by stevvooe** [comment]
@vbatts Thanks for filing. I put a full description of the missing white format in #130.

**Comment by vbatts** [comment]
Cool cool
