### ISSUE TITLE
Split serialization.md into layers and config documents

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#128]
From the [mailing-list thread on v1.0.0](https://groups.google.com/a/opencontainers.org/d/msg/dev/NPBMTrniG8Q/BS6adHTaAgAJ)

**Comment by philips** [comment]
I can do this but @stevvooe felt strongly about the naming.

I feel like "filesystem serialization" is the best name for the media-type that is today tarball representing a filesystem. This term is also sort of implied by the mime-type `application/vnd.oci.image.serialization.rootfs.tar.gzip`. Any objections to calling the two split out "config" and "filesystem serialization" @stevvooe?

**Comment by philips** [comment]
ping @stevvooe

**Comment by stevvooe** [comment]
@philips I think that's okay. I'll send a PR to split these into two then we can see if there is enough context for each format.

**Comment by stevvooe** [comment]
@duglin Was going to take this on when #171 landed, but that is taking some extra time. This is starting to make sense as the size of the layers section gets expanded.
