### ISSUE TITLE
Describe format and application of whiteout files

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#130]
Whiteout files allow layers higher in the stack to control how base layer content appears in a container filesystem. Much of the whiteout format comes from the AUFS implementation, but certain files are not transmitted. There are many details about format and application that are currently missing from the specification.

Ensuring that these whiteouts are handled consistently is critical to a portable image format.

The docker implementation can inform this specification. Several details on the whiteout files are available [here](https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/pkg/archive/whiteouts.go). Change calculation is [here](https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/pkg/archive/changes.go#L83).

It would be good to examine other implementations to inform this, as well.

Supercedes #127

**Comment by philips** [comment]
Are you going to take on the task of writing this up? Can I assign this to you?

**Comment by vbatts** [comment]
This is specifically referring to the `*.wh.*` entries in a tar archive? or also a whiteout list?

**Comment by philips** [comment]
ping @stevvooe

**Comment by stevvooe** [comment]
@philips Sorry. I have been busy with a release.

We need to specify the format of the `*.wh.*` files. There are also security considerations that we may want to address in the specification.

**Comment by stevvooe** [comment]
It may be sufficient to include language to this affect, from http://aufs.sourceforge.net/aufs.html:

> The whiteout is for hiding files on lower branches. Also it is applied to stop readdir going lower branches. The latter case is called ’opaque directory.’ Any whiteout is an empty file, it means whiteout is just an mark. In the case of hiding lower files, the name of whiteout is ’.wh.<filename>.’ And in the case of stopping readdir, the name is ’.wh..wh..opq’ or ’.wh.__dir_opaque.’ The name depends upon your compile configuration CONFIG_AUFS_COMPAT. All whiteouts are hardlinked, including ’<writable branch top dir>/.wh..wh.aufs.’

The overlay documentation contains s imilar section: https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt.

The main issue is that we have an example based specification. Adding an introduction to the changeset model will cover this.
