### ISSUE TITLE
image-layout: are `refs` following semver?

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#132]
basically $SUBJECT - or can we name refs inside `./refs/` the way we want? Can I name refs using _digests_ also?

/cc @vbatts @philips

**Comment by philips** [comment]
You can name the refs however you want. You _could_name it by something that looks like a digest but it would resolve to the digest in the ref document. cc @stevvooe

**Comment by runcom** [comment]
@philips I think we should make this clear in the image-layout.md - if I'm not wrong this is left to the reader to understand

**Comment by philips** [comment]
@runcom Would you mind taking a swing at making this clearer?
