### ISSUE TITLE
image-layout: clarification about ./blobs/ directory content

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#134]
It isn't (wasn't for me) immediately clear that files under `./blobs/` can be either manifests or actual tar blobs - the example at the end shows only a manifest so this made me ask where acutal data (tars) was. I think this should be clarified.

**Comment by runcom** [comment]
@philips I'll clarify this as well in a PR

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 03:35:54PM -0700, Antonio Murdaca wrote:
> It isn't (wasn't for me) immediately clear that files under
> `./blobs/` can be either manifests or actual tar blob…

They can be anything you want (even text/plain, image/png, …).  Most
image-unpacking software is unlikely to be able to unpack those types
if you reference them, but that doesn't mean they're invalid entries
in the blob store (e.g. maybe you don't reference them from the
manifest-list you asked to have unpacked).

**Comment by runcom** [comment]
I see, but as an implementation I was struggling at understanding how tar files were (coming from Docker background here) even if it's obvious to you. I think this needs clarification if I was unable to get it at the first look.

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 03:47:36PM -0700, Antonio Murdaca wrote:
> I think this needs clarification if I was unable to get it at the
> first look.

Absolutely.  I was just chiming in to avoid having the clarification
you're adding be too narrowly scoped ;).

**Comment by philips** [comment]
@runcom thanks! Great to have another set of eyes reading through this. @vbatts @stevvooe and I are way to close to see the flaws in our descriptions :)
