### ISSUE TITLE
image-layout: blobs have schema?

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#138]
```
The image layout has two top level directories:

"blobs" contains content-addressable blobs. **A blob has no schema** and should be considered opaque.
"refs" contains descriptors pointing to an image manifest list
```

just a question, but blobs can contain manifests which have schema - am I just misunderstanding?

@philips ?

**Comment by philips** [comment]
@runcom I am trying to express if you don't know what the blob is ahead of time you can't figure it out without guessing.

**Comment by runcom** [comment]
@philips got it
