### ISSUE TITLE
oci-image-tool: Drop http.FileSystem?

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#150]
While reading #148, the [`http.FileSystem` section][1] struck me as the wrong approach.  “I'd like to validate this content against this JSON Schema” is easy to support generically, and keeping the schemas themselves outside of that tool allows you to use an existing version of the tool to validate new content against new schemas.  If you compile the schemas in, you have to rebuild the tool to get access to the new schemas.

For an alternative approach, see the in-flight opencontainers/runtime-spec#490.  This approach allows a generic JSON-Schema validator to use whichever schema you point it at.  It would be nice to put the schemas up on www.opencontainers.org/schema/…, but even without that you can [use the raw GitHub URLs][2].  For oci-image-tool, you'd need a method to convert the detected/configured media type / version to a schema URL, but you already do that for `http.FileSystem`.  The URLs would just get a bit longer, and if we start removing schemas you'd have to add logic to pin to the last image-spec version which carried a schema for your media type.

If this sounds like a reasonable approach, I can work up a PR.

[1]: https://github.com/opencontainers/image-spec/pull/148/files#diff-2cb561c5e46512465f54a0f84d421c80R45
[2]: https://github.com/opencontainers/runtime-spec/pull/490/files#diff-751d571a4cba0b0155c3d3bf793e08e8R44

**Comment by philips** [comment]
I would be fine with making this an optional feature. Requiring network traffic by default doesn't seem like the best default however.

**Comment by wking** [comment]
On Thu, Jun 16, 2016 at 03:01:46PM -0700, Brandon Philips wrote:
> I would be fine with making this an optional feature. Requiring
> network traffic by default doesn't seem like the best default
> however.

Does Go have defaults for storing associated data (like Python's [1])?
Baking it into the binary seems like “here's my spell checker with a
compiled in snapshot of today's dictionary” (and I hope nobody does
that ;).

[1]: https://docs.python.org/3/distutils/setupscript.html#installing-package-data

**Comment by philips** [comment]
@wking no, this is the "right" way os doing this for Go. Compiling in the data in a section via a const is the common practice. Not great but that is how it is. 

We have a bunch of tools at CoreOS that use this fake filesystem thingie as default and then let people override in "dev" mode.

**Comment by s-urbaniak** [comment]
Agreeing to all @philips said. I can work on a possibility to look up schema via http/s, or if you @wking would like to do a PR, that'd be fine too.

**Comment by wking** [comment]
On Fri, Jun 17, 2016 at 06:48:30AM -0700, Sergiusz Urbaniak wrote:
> I can work on a possibility to look up schema via http/s…

I'm happy to let you do the work ;).

**Comment by philips** [comment]
I am going to make this post-v1.0.0 as it feels like a nice to have. Also, labeling as help wanted as it is a fun Go project for someone :)

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#24

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:48:57PM -0700, Brandon Philips wrote:
> This issue was moved to opencontainers/image-tools#24

Is this an image-tools issue?  My understanding was that cmd/ and
image/ were moving to image-tools, but that schema/ and specs-go/ were
staying.  We could keep schema/*.json but move schema/*.go, but
runtime-spec currently keeps both [1].

[1]: https://github.com/opencontainers/runtime-spec/tree/v1.0.0-rc2/schema

**Comment by wking** [comment]
On Wed, Sep 21, 2016 at 01:54:55PM -0700, W. Trevor King wrote:
> On Tue, Sep 20, 2016 at 07:48:57PM -0700, Brandon Philips wrote:
> > This issue was moved to opencontainers/image-tools#24
> 
> Is this an image-tools issue?

With #337 having landed, I think that this is pretty clearly still an
image-spec issue.  Can we re-open this?
