### ISSUE TITLE
master broken: unable to validate: open /config-schema.json: no such file or directory

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#162]
This is probably due to the floating dependencies without #148, but recent builds in a clean Go directory break with:

    $ make test
    go test -race ./...
    ?       github.com/opencontainers/image-spec/cmd/oci-image-tool [no test files]
    ?       github.com/opencontainers/image-spec/image      [no test files]
    --- FAIL: TestConfig (0.00s)
            config_test.go:162: test 6: expected validation failure false but got true, err schema application/vnd.oci.image.serialization.config.v1+json: unable to validate: open /config-schema.json: no such file or directory
    …

**Comment by wking** [comment]
Spun off from [earlier discussion][1] in #161.

[1]: https://github.com/opencontainers/image-spec/pull/161#issuecomment-227300170

**Comment by wking** [comment]
And the problem is (not surprisingly, given the error message) with `http/FileSystem` (see discussion in #150).  The tests pass with the following patch:

    diff --git a/schema/validator.go b/schema/validator.go
    index abc8d6d..537314a 100644
    --- a/schema/validator.go
    +++ b/schema/validator.go
    @@ -19,6 +19,7 @@ import (
     	"fmt"
     	"io"
     	"io/ioutil"
    +	"path/filepath"
     
     	"github.com/pkg/errors"
     	"github.com/xeipuuv/gojsonschema"
    @@ -44,7 +45,12 @@ func (v Validator) Validate(src io.Reader) error {
     		return errors.Wrap(err, "unable to read manifest")
     	}
     
    -	sl := gojsonschema.NewReferenceLoaderFileSystem("file:///"+specs[v], fs)
    +	//sl := gojsonschema.NewReferenceLoaderFileSystem("file:///"+specs[v], fs)
    +	refPath, err := filepath.Abs(specs[v])
    +	if err != nil {
    +		return err
    +	}
    +	sl := gojsonschema.NewReferenceLoader("file://" + refPath)
     	ml := gojsonschema.NewStringLoader(string(buf))
     
     	result, err := gojsonschema.Validate(sl, ml)

**Comment by wking** [comment]
Rolling back assorted dependencies, I the issue was introduced by xeipuuv/gojsonschema#103, and there are already comments there about broken loading as a result.  So folks who want a working test suite should pin thier gojsonschema before that PR landed or wait until they roll out a fix.

**Comment by vbatts** [comment]
correct. rolling back https://github.com/xeipuuv/gojsonschema/commit/ac948b64b57aa1beeb91c87069730e6f24bc91d9 lets the tests pass again. :-\

**Comment by petemoore** [comment]
I think https://github.com/xeipuuv/gojsonschema/pull/105 fixed a bug introduced in https://github.com/xeipuuv/gojsonschema/pull/103 - so you _might_ not need to pin anymore...

**Comment by vbatts** [comment]
nope. 105 did not fix the issue.

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#23
