### ISSUE TITLE
Name compatibility across discovery systems

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#175]
Spun off from #173 (trying to keep each discussion isolated in it's own issue ;):

On Thu, Jul 21, 2016 at 04:38:55PM -0700, Stephen Day [wrote](https://github.com/opencontainers/image-spec/issues/173#issuecomment-234416091):

> 1. Names need to be compatible across image layout, dns and other
>    discovery systems.

I'm not convinced that this is a MUST.  Compatibility between systems is useful, and guidelines on portable names are very helpful in encouraging users to chose portable names.  However, limiting _each system_ to only the portable set is a race to the bottom.  There's no reason that image-layout (for example) couldn't support names that were impossible to resolve via DNS.  It would just mean that users who used those names wouldn't support discovery via DNS.  So I'm in favor of:
- Documenting guidelines for portable naming and
- Making each system as flexible as possible (regardless of what is possible in other systems).

**Comment by vbatts** [comment]
This has turned out to be a non-issue. Folks use the URI of their registry, and the digest is the source of truth
