### ISSUE TITLE
Signed name-assertion objects

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#176]
Spun off from #173:

On Thu, Jul 21, 2016 at 04:38:55PM -0700, Stephen Day [wrote](https://github.com/opencontainers/image-spec/issues/173#issuecomment-234416091):

> 1. The trust model for naming must be clarified (how does one trust
>    the names in a tar file?). File names aren't a very good
>    authority if you can't verify the integrity of the underlying
>    storage.

I have some notes on modeling this [here](https://github.com/opencontainers/image-spec/issues/23#issuecomment-212651871), [here](https://github.com/opencontainers/image-spec/issues/23#issuecomment-221432834), and [here](https://groups.google.com/d/msg/containers-dev/HPzM3KrRGbI/QEshLiVSAgAJ), but I think we need the following types:
- `application/vnd.oci.image.named.blob.v1+json`, with properties for a `name` string and a `blob` descriptor, asserting that that name applies to that descriptor.
- `application/vnd.oci.image.signed.blob.v1+json`, with properties for a `blob` descriptor and `signatures` array of descriptors.

The signature payloads would use existing media types like [application/pgp-signature](http://tools.ietf.org/html/rfc3156#section-9) and [application/jose+json](https://tools.ietf.org/html/rfc7515#section-9.2.1).

I think that's enough to get started, and we can talk about [blobs for public keys](https://github.com/ipfs/specs/tree/5173085ad35a5b6121008da61600f85027dc3035/keychain#diagrams), [signing algorithms](https://github.com/ipfs/specs/tree/5173085ad35a5b6121008da61600f85027dc3035/keychain#abstract), [validity schemes](https://github.com/ipfs/specs/tree/5173085ad35a5b6121008da61600f85027dc3035/iprs-interplanetary-record-system#the-objects), etc. later if there is demand for carrying them in-band.

**Comment by vbatts** [comment]
I don't see this conversation having traction or a common goal.

**Comment by wking** [comment]
> I don't see this conversation having traction...

Yeah, over two years without a response sounds like "no traction" to me ;).

> ... or a common goal.

I think havong a standardized way to sign images is a pretty clear goal.  This proposal is one way to do that, and it has the benefit of allowing signed name-assertions to live in CAS where they are easy to mirror and distribute.  #22 has discussion on many alternatives as well.  It would be nice if image-spec maintainers eventually picked one approach and specified it.
