### ISSUE TITLE
cmd/oci-image-tool: no tests dependencies

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#179]
```
$ make test
go test -race ./...
# github.com/opencontainers/image-spec/schema
schema/spec_test.go:29:2: cannot find package "github.com/russross/blackfriday" in any of:
	/home/amurdaca/src/github.com/opencontainers/image-spec/vendor/github.com/russross/blackfriday (vendor tree)
	/usr/lib/golang/src/github.com/russross/blackfriday (from $GOROOT)
	/home/amurdaca/src/github.com/russross/blackfriday (from $GOPATH)
FAIL	github.com/opencontainers/image-spec/schema [setup failed]
^CMakefile:93: recipe for target 'test' failed
make: *** [test] Interrupt

```

Also, just a question: How do I `glide install` the first time I clone the repo? I tried `glide install` but it does not work correctly (it pulls stuff in and other stuff)

/cc @s-urbaniak

**Comment by s-urbaniak** [comment]
@runcom You shouldn't have to do anything, all vendored dependencies are checked in, `make test` simply delegates to `go test ./...`. You only need glide if you want to update/bump/add dependencies. Do you have `$GOPATH` defined? I guess `go test` needs a valid `GOPATH` to see the `vendor` directory.

**Comment by s-urbaniak** [comment]
@runcom I can reproduce locally, seems a new dependency was pulled, without vendoring, let me submit a PR.

**Comment by runcom** [comment]
> @runcom I can reproduce locally, seems a new dependency was pulled, without vendoring, let me submit a PR.

yeah...that was it...

**Comment by stevvooe** [comment]
This dependency was added before we had glide...
