### ISSUE TITLE
[bug] gometalinter fails to find/install `unused`

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#185]
not really sure what is happening here :arrow_right: https://travis-ci.org/opencontainers/image-spec/builds/148376653#L223

tried to reproduce locally, but `unused` is not even attempted to install:
```bash
vbatts@bananaboat] {master *} ~$ export GOPATH=$(mktemp -d)
[vbatts@bananaboat] {master *} ~$ env | grep GO
GOROOT=/home/vbatts/src/go
GOPATH=/tmp/tmp.szZOVm
[vbatts@bananaboat] {master *} ~$ go get -u github.com/alecthomas/gometalinter
[vbatts@bananaboat] {master *} ~$ gometalinter --install
Installing:
  structcheck
  goconst
  golint
  interfacer
  deadcode
  unconvert
  gotype
  aligncheck
  varcheck
  gocyclo
  ineffassign
  dupl
  lll
  gosimple
  goimports
  errcheck
```

**Comment by philips** [comment]
@vbatts What needs to happen here?

**Comment by vbatts** [comment]
oh, this "went away". But could return, due to the way `gometalinter` arbitrarily adds new linters that will be slurped up. Other projects work around this by excluding all linters by default and only including the specific linters needed. Perhaps some enterprising young contributor can offer such, but for now I'll close this.
