### ISSUE TITLE
Remove windows-specific rootfs type from serialization

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#186]
The following PR is removing support for machine-located windows base layers:

https://github.com/docker/docker/pull/25090/files#diff-b1247b61dc69edc892f3be4ea4f300a6R373

This was a hack that allowed the local container runtime to supply filesystem layers. This needs to be removed from OCI, as well, as this was never intended for long term support and problem won't be supported in OCI.

The use case may be valid, but OCI support should be done very differently.

**Comment by swernli** [comment]
@jstarks FYI

**Comment by philips** [comment]
@stevvooe what needs to happen with this?

**Comment by stevvooe** [comment]
Just remove that section. I can take care of it.
