### ISSUE TITLE
digest format mismatch

### ISSUE THREAD

**Issue by amitsaha** [opencontainers/image-spec#193]
```
$ git diff
diff --git a/image/descriptor.go b/image/descriptor.go
index 9a5d183..3ad70ec 100644
--- a/image/descriptor.go
+++ b/image/descriptor.go
@@ -106,7 +106,7 @@ func (d *descriptor) validateContent(r io.Reader) error {
                return errors.Wrap(err, "error generating hash")
        }
 
-       digest := "sha256:" + hex.EncodeToString(h.Sum(nil))
+       digest := "sha256-" + hex.EncodeToString(h.Sum(nil))
 
        if digest != d.Digest {
                return errors.New("digest mismatch")
```

Is this an oversight? My example image is here: https://github.com/amitsaha/oci-image-experiments/tree/master/image

**Comment by vbatts** [comment]
Is what? the use of a hyphen? It is due to file names, and avoiding `:` in the file name.

**Comment by amitsaha** [comment]
Yeah, I was referring to the construction of the digest using "sha256:" rather than "sha256-". Have I named my files wrongly? I am probably confused somewhere.

**Comment by stevvooe** [comment]
The files should use the `-` format. Upon reading from disk, this should be immediately converted to the digest format.

As a security rule, never use the parsed value of the digest. Calculate the digest and verify against the parse value and return the calculated version.

I'm surprised to see such slip-shod assembly of digests in the code base. We created a digest package long ago that addresses these problems.

**Comment by amitsaha** [comment]
okay, I figured out the issue:

- When I am referring to blobs, I should use ":" notation
- But the files themselves should be named using "-"

is there any reason for it being this way?

**Comment by stevvooe** [comment]
@amitsaha That is a very odd way to make that conclusion.

These are references to a blob object, made up of an algorithm and hex bytes. These references have a format that describes the targeted blob. We can serialize these references to a format that is compatible with the target. The standard serialization for a digest reference uses a colon. In formats where the colon character is disallowed, such as filesystems, we use a dash.

If there were a place to store blobs that supported colons, we would just use the colon syntax.

**Comment by amitsaha** [comment]
I see what you mean. My conclusion was certainly not correct. However, Linux filesystems (Windows doesn't) do support ":" in filenames right?

**Comment by stevvooe** [comment]
> My conclusion was certainly not correct.

No, but you created a thesis based on observation!! Testing ideas is the best way to understand something new. :)

> However, Linux filesystems (Windows doesn't) do support ":" in filenames right?

Yep, and that is why we specify a dash. It keeps the character set restricted for serialization that may land on disks.

**Comment by stevvooe** [comment]
@amitsaha It looks like your question is answered. Feel free to re-open if there was more clarification needed.
