### ISSUE TITLE
serialization: clarify order of application of tar entries

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#196]
We need to clarify that when encountering conflicting tar entries, the latest entry in the layer should be used. This has always been implied but we need to clarify this in the context of opaque layers, as well.

cc @vbatts

**Comment by vbatts** [comment]
Hah. I'm confus. Order does not matter, until it does?

**Comment by stevvooe** [comment]
I'm not sure if I've ever said that order doesn't matter.

The difference here is application of _identical_ resources. We also need to be careful about how this is specified in the context of opaque file ordering.

For regular files, we take latest entry.

Opaque files need to be stable sorted to top, preserving ordering, then latest entry is applied.

This is necessary to guarantee consistent unpacking of tar archives.

**Comment by philips** [comment]
The reason for doing this would be compatibility with the Docker Engine. @vbatts says that tar-split will fail with errors since Docker v1.8 with duplicate layers.

My personal preference would be to disallow duplicate dentries in an OCI layer.

@stevvooe and @vbatts took this as their action item to investigate.

**Comment by stevvooe** [comment]
> My personal preference would be to disallow duplicate dentries in an OCI layer.

How should that be implemented? Should an unpacker keep a list of unpacked entries and error on duplicate or should it error out if the resource already exists in the unpack destination?

**Comment by philips** [comment]
@stevvooe In order to support overlay filesystems it is going to have to keep a list of unpacked entries. But, I don't think we have to specify how it disallows duplicates.

**Comment by philips** [comment]
@runcom  @s-urbaniak could you add support and a test to the oci-image-tool for this ?

**Comment by stevvooe** [comment]
@philips In overlay, this isn't too big of an issue. The problem arises when trying to assemble the layer by applying tar after tar to a rootfs. If you encounter an entry that is already present, you can't tell if it was in the current tar or a lower layer without keeping track of the encountered entries. This may place undue memory requirements on the processor, but, in practice, this may not be an issue.

**Comment by s-urbaniak** [comment]
@philips ack, @runcom up for this or shall I?

**Comment by runcom** [comment]
Currently taking care of #222 and adding this to my todo if you are ok

**Comment by s-urbaniak** [comment]
@runcom fine with me, thanks!

**Comment by runcom** [comment]
PR opened https://github.com/opencontainers/image-spec/pull/240

**Comment by vbatts** [comment]
cool. Now for me to put some verbiage down.

**Comment by philips** [comment]
This will be fixed by #255

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 09:55:58AM -0700, Brandon Philips wrote:
> This will be fixed by #255 

Is this actually covered by #255?  Can you point out the line(s)?

**Comment by vbatts** [comment]
https://github.com/opencontainers/image-spec/pull/255/files#diff-dc2bb3b4eddcffe96e682193926e8ff6R10

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 10:29:41AM -0700, Vincent Batts wrote:
> https://github.com/opencontainers/image-spec/pull/255/files#diff-dc2bb3b4eddcffe96e682193926e8ff6R10

But that doesn't include order of application.  If you have a whiteout
early in the tar and remove the whited-out entries, but a later entry
lands in one of the whited-out locations, what happens?  I think we
should specify that the tar entries are applied in the order listed in
the tarball, and that no information about previous entries is
recorded to affect subsequent entries (with the possible exception of
erroring out in the event of duplicate entries?).

**Comment by philips** [comment]
@vbatts is this done

**Comment by vbatts** [comment]
@wking that wording was done by @stevvooe already.

**Comment by vbatts** [comment]
#255 is merged now

**Comment by wking** [comment]
On Fri, Sep 09, 2016 at 10:00:30AM -0700, Vincent Batts wrote:
> @wking that wording was done by @stevvooe already.

The closest wording I can find is [1], which sounds like “all
whiteouts in the layer must be applied before you apply anything else
from the layer”.  Is that really what we want?  I don't see a way to
implement it without making two passes through the layer tarball.

[1]: https://github.com/opencontainers/image-spec/blame/72d05255cd884d28cc7505d22a39514aeaafdaab/layer.md#L197-L198

**Comment by stevvooe** [comment]
@wking We discussed those implications when merging the issue. Unfortunately, for non-overlay based implementations, this is a requirement. It should only require memory for metadata linear to the number of  entries, which is small in practice.

(Note that there may be a way to do it in one pass by unpacking to temporary locations then moving the resource into place after whiteouts have been processed)

**Comment by wking** [comment]
On Fri, Sep 09, 2016 at 02:24:33PM -0700, Stephen Day wrote:
> @wking We discussed those implications when merging the
> issue. Unfortunately, for non-overlay based implementations, this is
> a requirement.

Got it.  Thanks for the clarification :).
