### ISSUE TITLE
Create validator.opencontainers.org

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/image-spec#203]
Provide a sandbox for the image-spec maintainers to play with a tool

cc: @vbatts @stevvooe

**Comment by RobDolinMS** [comment]
Similar to https://validator.w3.org/, it would be nice if this supported the following scenarios:
* Upload (Validate by File Upload)
* Point to a file (Validate by URI)
* Paste (Validate by Direct Input)

**Comment by RobDolinMS** [comment]
@caniszczyk It might make sense to break this into a few work items:
* Provision the "validator" subdomain for opencontainers.org
* Set-up validator.opencontainers.org to point to a URL like http://opencontainers.github.io/image-tools/
* Publish code into gh-pages branch of OCI images-tools repo to support web interface to OCI Image Format validation

**Comment by wking** [comment]
On Wed, Aug 24, 2016 at 02:00:53PM -0700, Rob Dolin (MSFT) wrote:
> * Paste (Validate by Direct Input)

Hmm, “Just paste your gzipped tarball in here…” ;).

There are two levels to most of the current oci-image-tool validation:

1. Is the JSON content internally valid (e.g. has all the required fields)?
2. Is everything down the Merkle chain from the passed object valid?

(1) will work fine with an w3 validator approach, but (2) needs a way
to get at the whole image-layout instance, where cut-and-paste doesn't
work so well.

**Comment by wking** [comment]
On Wed, Aug 24, 2016 at 02:04:36PM -0700, Rob Dolin (MSFT) wrote:
> * Publish code into gh-pages branch of OCI images-tools repo to
>   support web interface to OCI Image Format validation

Hmm, I wonder if we can handle image validation entirely in
JavaScript…  It might be possible.

Otherwise we'll probably also need a branch/repo with an OCI bundle to
handle the dynamic part of image validation.

**Comment by wking** [comment]
On Wed, Aug 24, 2016 at 02:04:36PM -0700, Rob Dolin (MSFT) wrote:
> * Set-up validator.opencontainers.org to point to a URL like http://opencontainers.github.io/image-tools/

Looks like we already have something along these lines [1].

[1]: https://github.com/opencontainers/validator.opencontainers.org

**Comment by philips** [comment]
Who is going to do this work? I certainly don't have the time to build a webservice. Are you Chris?

**Comment by caniszczyk** [comment]
@philips this was requested by @vbatts, I assume it's on his plate when he has time

**Comment by glestaris** [comment]
What would the scope of the validator be? Would it just parse the manifest/config or go as far as unpacking the blobs?

**Comment by wking** [comment]
On Thu, Aug 25, 2016 at 05:35:13AM -0700, George Lestaris wrote:
> What would the scope of the validator be? Would it just parse the
> manifest/config or go as far as unpacking the blobs?

I opened a scoping issue in
opencontainers/validator.opencontainers.org#1 yesterday, if we want to
keep that discussion collected there.

**Comment by RobDolinMS** [comment]
I've added my comments as a PR and Issue against the other repo: https://github.com/opencontainers/validator.opencontainers.org/pull/4 and https://github.com/opencontainers/validator.opencontainers.org/issues/5

**Comment by RobDolinMS** [comment]
I recommend closing this issue and directing conversations around web hosting of container validation to: https://github.com/opencontainers/validator.opencontainers.org
/cc @caniszczyk @philips
