### ISSUE TITLE
image-spec: add RFC boiler plate

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#204]
Similar to https://github.com/opencontainers/runtime-spec#open-container-runtime-specification boiler plate about MUST, MUST NOT, etc.

cc @RobDolinMS and @jlb13

**Comment by RobDolinMS** [comment]
(Howard Huang from Huawei also volunteered to help)

**Comment by RobDolinMS** [comment]
Opened PR #207 to address this

**Comment by wking** [comment]
#207 has landed, so this can be closed.  Not sure why GitHub is not sending me email about these ;).
