### ISSUE TITLE
image layout: move to slash separation for blob storage layout

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#208]
Currently, blobs are stored with the follow format:

```
blobs/<digest>-<hex bytes>
```

This has caused confusion in the context of the `:`-separated hash format.

To make this more clear, the blobs should be stored in the following format:

```
blobs/sha256/<hex bytes>
```

cc @vbatts @philips

**Comment by wking** [comment]
Or we could use `<algo>-<hex-digest>` for both the blob names and the blob filenames, in which case there would be even less confusion.

I'm ok with using a path separator, but Windows folks would have to be careful to use the appropriate separator for the engine (e.g. `/` for image-layout backed by HTTPS, tar, … and `\` for image-layout backed by local directories).

**Comment by philips** [comment]
+1 to this concept.

**Comment by glestaris** [comment]
That would be nice. We can store multiple images under the same directory structure.

**Comment by stevvooe** [comment]
@xiekeyang @glestaris We have discussed the convention of using a portion of the digest to partition the CAS files but have been unable to find any recent examples of where this actually speeds up retrieval.

Do you have any data supporting this design? What is the actual performance impact?

**Comment by wking** [comment]
On Thu, Aug 25, 2016 at 07:06:12AM -0700, Stephen Day wrote:
> @xiekeyang @glestaris We have discussed the convention of using a
> portion of the digest to partition the CAS files but have been
> unable to find any recent examples of where this actually speeds up
> retrieval.

Previous discussion of hash sharding starting here [1].

[1]: https://github.com/opencontainers/image-spec/pull/94#discussion_r65265938

**Comment by xiekeyang** [comment]
@stevvooe @wking  Got it, thanks a lot!

**Comment by philips** [comment]
@runcom @s-urbaniak could you work-up a patch to make this change in the tooling? And then @stevvooe or I can make the english language change.

**Comment by stevvooe** [comment]
@philips I can take this on!

**Comment by philips** [comment]
@stevvooe are you going to do the code, english or both?

**Comment by philips** [comment]
@runcom volunteered to do the code side of this one.

**Comment by runcom** [comment]
created https://github.com/opencontainers/image-spec/pull/230 for the code side
