### ISSUE TITLE
linked data in image layout

### ISSUE THREAD

**Issue by xiekeyang** [opencontainers/image-spec#213]
The spec draws the image layout that is compatible with runc. The description and example in spec imply one oci image layout.

Maybe oci image spec are concerning the repository layout including many images. So, it should introduce merkle-links as blobs organization.

I'm not sure if my idea is out of scope of oci image spec. Here I would like to get the perspective from maintainers. If we should finish the spec about merkle-links? 

Thanks a lot.

**Comment by vbatts** [comment]
@xiekeyang did you mean to close this?

I'm not opposed to a merkle tree of objects, but that would likely be a different subdirectory, also that would need to include information in mimetype-like-config file for like block size and order of the hashes, and top-level hash of the trie, potentially even which hashing algorithm is used.

For now this would be net-new development so I would say we're not going to block v1 with a feature like this, and ideally could be introduced in a post-v1 discussion that is hopefully a non-breaking feature.
