### ISSUE TITLE
oci-image-tool: Cleanup partially-unpacked directories on failures

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#242]
We might want a switch to turn this off, but I think the default should be to remove the unpack directory if we fail partway through the unpack.

Spun off from [here][1].

[1]: https://github.com/opencontainers/image-spec/pull/240#issuecomment-244138589

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#21

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:48:16PM -0700, Brandon Philips wrote:
> This issue was moved to opencontainers/image-tools#21

PR is opencontainers/image-tools#7.
