### ISSUE TITLE
Image-layout.md not included in released spec

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#244]
The text of the [image-layout.md file](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) does not seem to be included in the released HTML version of the spec (as of v0.4.0.)

**Comment by RobDolinMS** [comment]
I believe the [descriptor.md file ](https://github.com/opencontainers/image-spec/blob/master/descriptor.md) is also not included :(

**Comment by wking** [comment]
They need to be added to [1].

[1]: https://github.com/opencontainers/image-spec/blob/08ef0b1d662ac889d3bf2e99957acddad8e5804f/Makefile#L22-L29

**Comment by vbatts** [comment]
See #275
