### ISSUE TITLE
[ReadMe] Should we remove (or update) FAQ?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#246]
The FAQ section of the ReadMe (which gets included in the released spec) seems like it has been minimally updated since being copied from the project proposal.  

I'm glad to submit a PR to update (or remove) depending on consensus from Dev community.

**Comment by wking** [comment]
On Thu, Sep 01, 2016 at 01:51:09PM -0700, Rob Dolin (MSFT) wrote:
> I'm glad to submit a PR to update…

How would you update it?  [1] looks reasonably current to me, although
I might replace “Why start this work now?” with “Why work on this?”
and “Why a new project?” with “Why a new OCI Project?”.  And a more
logical ordering might be:

* Why work on this?
* Why a new OCI Project?
* Why doesn't this project mention distribution?
* What happens to AppC or Docker Image Formats?

[1]: https://github.com/opencontainers/image-spec/tree/08ef0b1d662ac889d3bf2e99957acddad8e5804f#faq

**Comment by philips** [comment]
Entries 2 and 3 can probably be removed. I think the rest is still relevent.

**Comment by wking** [comment]
On Thu, Sep 01, 2016 at 01:59:52PM -0700, Brandon Philips wrote:
> Entries 2 and 3 can probably be removed.

Those are the “why does this project exist” entries.  I don't think
that motivation is stale.  If they were stale, we'd be talking about
closing down this project.

**Comment by jonboulle** [comment]
Partially touched on in #367 

I think we should retain a FAQ in the README. If we don't want to publish it in the spec artefacts (PDF etc) then we should change the process by which we create those documents.

**Comment by vbatts** [comment]
Is this still needed? I just read over the FAQ again, and while the second entry could have a Q more like "Isn't this the same as the runtime-spec", I feel like the A is mostly fine. I'm tempted to just close this issue for now.

**Comment by caniszczyk** [comment]
also as an FYI we did an extensive update of the FAQ on the website recently: https://www.opencontainers.org/faq

**Comment by vbatts** [comment]
so should we just point to that and be done with this?

**Comment by jonboulle** [comment]
TBH the distribution question still comes up so often that we should continue to reference it it. But we can probably get rid of the "new project" and "why work on this" questions and point to the website FAQ.

**Comment by vbatts** [comment]
done
