### ISSUE TITLE
Images missing from HTML version of spec

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#247]
Images are not rendering in the HTML released version of the Image Format spec (v0.4.0.)  

The root cause MIGHT be that the HTML src= attributes seem to use relative URLs instead of absolute URLs.:

```
<p>The following figure shows how the above media types reference each other:</p>
<p><img src="img/media-types.png" /></p>
```

NOTE: Images ARE rendering in PDF version of spec :)

**Comment by RobDolinMS** [comment]
I recommend tagging with Milestone = v1.0.0 since this should not block any minor releases, but would be good to resolve before a v1 release.

**Comment by philips** [comment]
cc @vbatts

**Comment by vbatts** [comment]
i think this is because the pdf inlines the images, but the html expects to find the images.
I went down the road to base64 encode and html inline the images, that was not real great for this doc process.

I could attach those `img/` files in the release docs. That would seem sufficient to me. WDYT @RobDolinMS ?

**Comment by wking** [comment]
On Wed, Sep 07, 2016 at 12:21:19PM -0700, Vincent Batts wrote:
> I went down the road to base64 encode and html inline the images,
> that was not real great for this doc process.

If the goal is to produce a single-page version of the spec, I think
we can save a lot of headache by writing it up in one big Markdown
file (opencontainers/runtime-spec#264 had something similar, but we
don't even need that much magic).  Or we can switch to
reStructuredText or some other format that's designed with this sort
of “produce compilable documentation” goal in mind.

**Comment by vbatts** [comment]
i've spent some cycles on this, and still do not have a solution yet.
I realize the concern, but worse-comes-to-worse, I'd drop the single page HTML and only provide PDF rather than so-grossly hack this in.

**Comment by philips** [comment]
As Rob says above, this is low priority, moving to rc3.

**Comment by philips** [comment]
I am moving this to rc4 based on discussion on the mailing list that HTML and PDF isn't really the end goal as much as a top to bottom readable spec: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/XNreeSORPTQ

**Comment by RobDolinMS** [comment]
Per chat on OCI Dev ConCall, a partial (and sufficient) solution would be for a /img/ directory to be included with the release.  When the HTML spec is published, the /img/ directory should be published in the same location and the images will render.

**Comment by vbatts** [comment]
two things @RobDolinMS
* @wking's idea of an HTML `<base>` tag works fine, and will fetch the images from the tagged version on github. I've manually updated the RC3 and RC2 html documents with this approach.
* I, or someone, will take a stab at a PR to get this in the `make docs` target so it is not a manual process.

For posterity, it is adding to the top of the *.html file:
```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>image-spec v1.0.0-rc3</title>
    <base href="https://raw.githubusercontent.com/opencontainers/image-spec/v1.0.0-rc3/">
  </head>
  <body>
```
and to the tail of it:
```html

</body>
</html>
```

**Comment by vbatts** [comment]
opened a PR for this
