### ISSUE TITLE
[Media Types] What is the status of the ...combined media type?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#248]
The [image ](https://github.com/opencontainers/image-spec/blob/master/img/media-types.png) in the [media-types.md file](https://github.com/opencontainers/image-spec/blob/master/media-types.md) includes a box for "application/vnd.oci.image.serialization.combined.v1+json" but this is not described in the list of Media Types.

- Should the image be updated to remove the ...combined media type?
- Should the media-types.md file be updated to include a description of the ...combined media type?
- Something else?

**Comment by wking** [comment]
On Thu, Sep 01, 2016 at 03:03:40PM -0700, Rob Dolin (MSFT) wrote:
> - Should the image be updated to remove the ...combined media type?

Yes.  Looks like this was missed in #135.

**Comment by philips** [comment]
@RobDolinMS yes, please remove. A PR would be appreciated.

**Comment by RobDolinMS** [comment]
Thanks.  I have submitted PR #249

**Comment by RobDolinMS** [comment]
Closing as PR #249 has been merged.
