### ISSUE TITLE
Any chance of using hashes rather than random numbers for layer id's?

### ISSUE THREAD

**Issue by timthelion** [opencontainers/image-spec#25]
I'm confused why layers are refered to using random numbers rather than with cryptographic hashes. We already know that using random numbers as IDs lead to security problems at Docker, so why continue using this approach in a new standard?

The only thing that occures to me, is that one might think it possible that two layers of the same image would have the same hash, for example, if a file was repetedly whited out. But in truth this would NEVER happen, as the JSON file, which specifies the layers parent, would be different.

**Comment by philips** [comment]
I believe we should just update the language to say the ID MUST be a crypto hash. Would you mind submitting a PR to the location that has this language?

**Comment by timthelion** [comment]
The current text is this:

````
 Image ID
    Each layer is given an ID upon its creation. It is represented as a hexadecimal encoding of 256 bits, e.g., a9561eb1b190625c9adb5a9513e72c4dedafc1cb2d4c5236c9a6957ec7dfd5a9. Image IDs should be sufficiently random so as to be globally unique. 32 bytes read from /dev/urandom is sufficient for all practical purposes. Alternatively, an image ID may be derived as a cryptographic hash of image contents as the result is considered indistinguishable from random. The choice is left up to implementors. 
````

If I change it to being:

````
An image ID must be derived as a cryptographic hash of image contents.
````

That doesn't work, because as I already stated, there can be multiple `layer.tar` files with the same contents.

I would propose:

````
The layer ID is derived as a cryptographic hash of the files which define the image passed to an SHA256 hash function in the following order:

 - The unicode encoded string "json".
 - The contents of the json file.
 - The unicode encoded string "layer.tar"
 - The contents of the layer.tar file
 - The unicode encoded string "VERSION".
 - The contents of the VERSION file.
````

In order to have a proper hash across a directory, it needs to be specified that closely (well, actually, I put it in alphabetic order, but I think it is easier to understand when it is written out in long form.)

**Comment by timthelion** [comment]
Does anyone know the exact specification, including order of meta-data hashing, is for Docker image ids?

**Comment by kamalmarhubi** [comment]
Will a traversal order for the filesystem contents be specified for the hash of the layer tar file?

**Comment by kamalmarhubi** [comment]
Ah I see this is what you mean about there being mulltiple layer tar files with the same contents.

**Comment by philips** [comment]
@vbatts the new serialization doc removes all of the non CAS ids, right? This can be closed, I think.

**Comment by vbatts** [comment]
Correct.
