### ISSUE TITLE
[RFE] oci-image-tool: produce a layer archive

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#254]
Add a sub-command where two directory paths can be provided and the utility will produce a layer archive from comparing the two references.

(this exercise will help ensure the [layer.md](./layer.md) is readable)

**Comment by coolljt0725** [comment]
I'd like to work on this :)

**Comment by philips** [comment]
@coolljt0725 go for it.

**Comment by coolljt0725** [comment]
working on that, pr is coming :)

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#20

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:48:04PM -0700, Brandon Philips wrote:
> This issue was moved to opencontainers/image-tools#20

PR is opencontainers/image-tools#8.
