### ISSUE TITLE
oci-image-tool: check media types under refs/

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#260]
Came across this and oci-image-tool wasn't warning me when a reference descriptor under refs/ wasn't containing a valid media type (especially because it was the empty string with my testing).

Should oci-image-tool take care of this as well?

/cc @s-urbaniak @vbatts @philips @stevvooe

**Comment by runcom** [comment]
(likewise I think a check of oci-layout to be version == the spec version tested against is required to be added to the tool)

**Comment by coolljt0725** [comment]
I +1 on this, I came across this when I  `oci-image-tool validate` an old image layout which layer media type is still `application/vnd.oci.image.serialization.rootfs.tar.gzip`, I think it should throw out a warning or error

**Comment by runcom** [comment]
I'll fix it if people agree

**Comment by philips** [comment]
Yes, oci-image-tool should error out on this.

**Comment by runcom** [comment]
took care of this at https://github.com/opencontainers/image-spec/issues/262
