### ISSUE TITLE
oci-image-tool unpack does not preserve permissions and ownership of entries

### ISSUE THREAD

**Issue by glestaris** [opencontainers/image-spec#281]
`oci-image-tool` does not `chmod` or `chown` the extracted files. I wonder if this is something intentional or PR-worthy.

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 07:07:39AM -0700, George Lestaris wrote:
> `oci-image-tool` does not `chmod` or `chown` the extracted files. I
> wonder if this is something intentional or PR-worthy.

I think this should be fixed.  Unpacking semantics should probably be
just like tar, and from tar(1) [1]:

       --no-same-owner
              Extract files as yourself (default for ordinary users).

       --no-same-permissions
              Apply the user's umask when extracting  permissions  from
              the archive (default for ordinary users).

[1]: http://www.gnu.org/software/tar/manual/html_node/Option-Summary.html

**Comment by glestaris** [comment]
I am happy to pick this up as a PR then @image-spec-maintainers.

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#17

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:47:22PM -0700, Brandon Philips wrote:
> This issue was moved to opencontainers/image-tools#17

PR is in opencontainers/image-tools#3.
