### ISSUE TITLE
cmd/oci-image-tool: is having empty refs/ a valid image?

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#287]
$SUBJECT and basically, is it valid to have stuff under `blobs/` not referenced? Can I still package it up and validation is ok given there are no refs/? Should we print a warning (which can be silenced)?

**Comment by wking** [comment]
On Fri, Sep 09, 2016 at 01:40:15AM -0700, Antonio Murdaca wrote:
> $SUBJECT

I think so.  At least I don't see any “and there MUST be at least one
ref” language.  And if you cared about running images from the layour
that would be “and there MUST be at least one unpackable ref”
language.  And then you have to match the oci-layout version with the
media types that were unpackable when it was current (or is validity
in the eye of the validator?)… This is a bowl that I do not want to
fathom ;).

Maybe folks are just using an image-layout to ship some missing blobs.

I don't see any incentive to image-authors to publish ref-less blobs
and then pretend they are runnable, so I don't see a need to get into
the business of restricting refs.

> … and basically, is it valid to have stuff under `blobs/` not
> referenced?

Yes [1].

> Should we print a warning?

Warnings for “there are no refs” and “dangling blob sha256-abc…” sound
useful to me.  Maybe put the first behind ‘--log-level warn’ and the
second behind ‘--log-level info’ based on how likely I think they are
to be a mistake and how many lines will get printed if they exist ;).

[1]: https://github.com/opencontainers/image-spec/blame/e6a431f1584468f112a52c01a02d326199b99021/image-layout.md#L46

**Comment by vbatts** [comment]
Both seem valid to me

**Comment by runcom** [comment]
Alright, can we keep this open so we won't forget about adding some sort of warning/log when this happens

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#15

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:46:54PM -0700, Brandon Philips wrote:
> This issue was moved to opencontainers/image-tools#15

It seems like whether a refs-less image-layout is valid or not is
primarily a question for the image-layout spec.  Or have we already
reached a consensus on that in favor of the spec as it stands (with no
requirement for having refs or restrictions on media types for those
refs).  The spec's current position makes sense to me.

If we've already reached a consensus on the spec position, the
remaining issue is just “should we warn users when validating layouts
without refs (with recognized types)?”, and that seems like it can be
handled in image-tools without spec clarity around the warning
condition.
