### ISSUE TITLE
cmd/oci-image-tool: use logrus to ease printing to stdout

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#288]
$SUBJECT - logrus have various and a nicer way of printing logs to stdout with the option to specify the log level (which can then be used to differentiate the validation level in a nicer way).
The current way of embedding stdout in the validation struct isn't as pretty as it would be by having a nicer logger like logrus. 

I would also suggest to have a context (not necessary `context.Context`) object which can be used to embed system stuff like a logger - to be the first argument to function like `descriptor.Validate(ctx, ...)` so we extract the logger from there and print while validating. (Right now this isn't possible, and the logger should be explicitly passed to `Validate` changing its definition). @stevvooe wdyt?

@s-urbaniak wdyt?

/cc @vbatts @stevvooe @philips

**Comment by s-urbaniak** [comment]
logrus is pretty accepted in the ecosystem, and structured logging doesn't
sound too bad. So I am +1 for this.

**Comment by xiekeyang** [comment]
+1

**Comment by runcom** [comment]
I'll work on this once we reach consensus and figure out all the other issues about errors/warnings when validating an image, I would love to have a table-like document which lists soft and hard requirement for image validation w/o having to go through the whole spec to figure out MUST and SHOULD. Do you guys think it would be nice/useful to have such a document for oci-image-tool?

**Comment by xiekeyang** [comment]
It is deep related to #234 
In which we are also discussing logrus.
https://github.com/opencontainers/image-spec/pull/234#issuecomment-245789721

**Comment by s-urbaniak** [comment]
xfref regarding "how to inject the logger": https://github.com/opencontainers/image-spec/pull/234#issuecomment-245876579

I am in favor of classical dependency injection as per https://peter.bourgon.org/go-best-practices-2016/#program-design.

**Comment by wking** [comment]
On Fri, Sep 09, 2016 at 03:25:13AM -0700, Sergiusz Urbaniak wrote:
> I am in favor of classical dependency injection as per
> https://peter.bourgon.org/go-best-practices-2016/#program-design.

I'm ok with including a logger in our types to avoid relying on global
state.  But transitioning to logrus could happen in two stages:

* Replace log calls with logrus calls using the global state.
* Replace global-state logging with explicit logger state carried in
  our types.

Both of those can happen independently.  The first should be
straightforward and can happen at any time.  The latter should
probably happen along with or after we reorganize validation, etc., to
be more library-like.

**Comment by runcom** [comment]
> The latter should
> probably happen along with or after we reorganize validation, etc., to
> be more library-like.

totally agree on this point

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#14
