### ISSUE TITLE
failure to create-image-bundle - no error produced

### ISSUE THREAD

**Issue by dustymabe** [opencontainers/image-spec#293]
I run the code to create an image bundle and the return code is 0 but no rootfs is created. Not sure what the problem is.

using projectatomic/skopeo@362bfc5fe37db08b945d190c377b617c6a7e4c3c
using oci-image-tool @ 0a76d61e056738881495bad151824cfbe29864a0 from PR #257 

```
[vagrant@f24 skop3]$ skopeo copy docker://dustymabe/fedora20-pdftk:format2  oci:dustymabe-fedora20-pdftk-format2-oci:format2
[vagrant@f24 skop3]$ sudo oci-image-tool create-runtime-bundle --ref format2 ./dustymabe-fedora20-pdftk-format2-oci/ ./dustymabe-fedora20-pdftk-format2-bundle/
[vagrant@f24 skop3]$ echo $?
0
[vagrant@f24 skop3]$ ls dustymabe-fedora20-pdftk-format2-bundle/
config.json
```

**Comment by runcom** [comment]
Can't reproduce using `master` + cherry-pick https://github.com/opencontainers/image-spec/pull/257/commits/5c9e424ef0bde55e452930a2c9b0f61520cdbc78 from #257 - I guess something else made into `master` and fixed the issue you're having here. Could you try it yourself?
```sh
$ skopeo copy docker://dustymabe/fedora20-pdftk:format2  oci:dustymabe-fedora20-pdftk-format2-oci:format2
$ mkdir dustymabe-fedora20-pdftk-format2-bundle
$ sudo /home/amurdaca/bin/oci-image-tool create-runtime-bundle --ref format2 ./dustymabe-fedora20-pdftk-format2-oci/ ./dustymabe-fedora20-pdftk-format2-bundle/
$ ll dustymabe-fedora20-pdftk-format2-bundle/
total 8.0K
-rw-r--r--.  1 root root  440 Sep 10 10:44 config.json
drwxr-xr-x. 17 root root 4.0K Sep 10 10:44 rootfs
$ tree dustymabe-fedora20-pdftk-format2-bundle/rootfs
[ truncated ]
    ├── lock -> ../run/lock
    ├── log
    │   ├── btmp
    │   ├── journal
    │   ├── lastlog
    │   ├── README
    │   ├── tallylog
    │   ├── wtmp
    │   └── yum.log
    ├── mail -> spool/mail
    ├── nis
    ├── opt
    ├── preserve
    ├── run -> ../run
    ├── spool
    │   ├── cron [error opening dir]
    │   ├── lpd
    │   └── mail
    ├── tmp
    └── yp

2045 directories, 15146 files
```

**Comment by dustymabe** [comment]
it gets a little farther for me, but not quite all the way there:


```
[vagrant@f24 skop5]$ skopeo copy docker://dustymabe/fedora20-pdftk:format2  oci:dustymabe-fedora20-pdftk-format2-oci:format2
[vagrant@f24 skop5]$ sudo /sharedfolder/code/go/bin/oci-image-tool create-runtime-bundle --ref format2 ./dustymabe-fedora20-pdftk-format2-oci/ ./dustymabe-fedora20-pdftk-format2-bundle/                                                                                                                     
unpacking failed: sha256:62bd9ab678f7f73a2d632b260d1602e0aa8d04c4e664d5aeb62eafecea419018: not found
[vagrant@f24 skop5]$ 
[vagrant@f24 skop5]$ sudo /sharedfolder/code/go/bin/oci-image-tool unpack --ref format2 ./dustymabe-fedora20-pdftk-format2-oci/ ./dustymabe-fedora20-pdftk-format2-unpacked/                                                                                                                                  
unpacking failed: sha256:62bd9ab678f7f73a2d632b260d1602e0aa8d04c4e664d5aeb62eafecea419018: not found
[vagrant@f24 skop5]$ tree dustymabe-fedora20-pdftk-format2-oci
dustymabe-fedora20-pdftk-format2-oci
├── blobs
│   ├── sha256-2550592b7b4c118c55514234464666dca4d67183a3b6494e6e05e68decf8c39d
│   ├── sha256-486795df2fc19d6475d13dff4eaa3bb817d10d87e293da86b9a73bdba1370e65
│   ├── sha256-62bd9ab678f7f73a2d632b260d1602e0aa8d04c4e664d5aeb62eafecea419018
│   ├── sha256-90781a7c6cf06cdae184adccf10068970db98f049ce2a9dcf2cc5763a68c3f1e
│   ├── sha256-94737896b79700c606a5b1c5eea3cf2de4c1562fe567ea31b1ce55ce84d6a847
│   └── sha256-a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
├── oci-layout
└── refs
    └── format2

2 directories, 8 files
[vagrant@f24 skop5]$ cat dustymabe-fedora20-pdftk-format2-oci/refs/format2 
{"digest":"sha256:62bd9ab678f7f73a2d632b260d1602e0aa8d04c4e664d5aeb62eafecea419018","mediaType":"application/vnd.oci.image.manifest.v1+json","size":1453}
```

I pushed up my "master + cherry-picked commit" code to https://github.com/dustymabe/image-spec/commit/2d0d1db58195b2c2d708be2eea91751ad907a1c9 - do we maybe want to synchronize on the exact same commit and see if we get the same behavior?

**Comment by wking** [comment]
On Sat, Sep 10, 2016 at 06:30:36PM -0700, Dusty Mabe wrote:
> dustymabe-fedora20-pdftk-format2-oci
> ├── blobs
> │   ├── sha256-2550592b7b4c118c55514234464666dca4d67183a3b6494e6e05e68decf8c39d
> │   ├── sha256-486795df2fc19d6475d13dff4eaa3bb817d10d87e293da86b9a73bdba1370e65

This is the format from before #230 and #232.  You should either
generate the new format or patch your oci-image-tool to use the old
format.

**Comment by runcom** [comment]
@dustymade you're probably use an old skopeo version..

**Comment by dustymabe** [comment]
> @dustymabe you're probably use an old skopeo version..

that was it. was using skopeo from the system (fedora) and not the compiled one from master. 

The only error that I get now is on unpack:

```
[vagrant@f24 skop6]$ sudo /sharedfolder/code/go/bin/oci-image-tool unpack --ref format2 ./dustymabe-fedora20-pdftk-format2-oci/ ./dustymabe-fedora20-pdftk-format2-unpacked/
unpacking failed: error extracting layer: invalid symlink "dustymabe-fedora20-pdftk-format2-unpacked/bin" -> "usr/bin"
```

**Comment by runcom** [comment]
@dustymabe, I think I've already solved that in the current oci-image-tool master code (it's working for me). Not sure what's going on otherwise..

**Comment by dustymabe** [comment]
@runcom - I should be using master + cherry picked https://github.com/opencontainers/image-spec/pull/257/commits/5c9e424ef0bde55e452930a2c9b0f61520cdbc78. 

Do you mind checking? This is what I'm using: https://github.com/dustymabe/image-spec/commit/2d0d1db58195b2c2d708be2eea91751ad907a1c9

**Comment by runcom** [comment]
@dustymabe seems so - not sure why this is working for me then

**Comment by dustymabe** [comment]
In that case i'm not worried about it. The issue I reported has been fixed somewhere in current master. would be nice to get #257 in.

**Comment by amitsaha** [comment]
I had to cherry-pick https://github.com/opencontainers/image-spec/pull/257/commits/5c9e424ef0bde55e452930a2c9b0f61520cdbc78 onto my master too to be able to get `oci-image-tool` to be unpack correctly.
