### ISSUE TITLE
image-tools naming

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#296]
I have a working branch/repo at https://github.com/runcom/image-tools which basically removes from this repo the `cmd/*` bits to be later become `opencontainers/image-tools`.

Basically that big `oci-image-tool` became a set of smaller binaries.
Commands under `cmd/*` looks like this:
```sh
# s/runcom/opencontainers/g to test them out
$ go get github.com/opencontainers/image-tools/cmd/oci-validate
$ go get github.com/opencontainers/image-tools/cmd/oci-unpack
$ go get github.com/opencontainers/image-tools/cmd/oci-create-runtime-bundle
```
The `oci-` prefix is ugly but is making sure commands like `unpack` and `validate` do not conflicts with already installed binaries - should we care? because it's much nicer w/o that prefix.

Thoughts? Preferences?

@philips @vbatts @stevvooe @s-urbaniak

**Comment by jonboulle** [comment]
I don't see a problem with the prefix.

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 03:18:19AM -0700, Antonio Murdaca wrote:
> Commands under `cmd/*` looks like this:
> ```sh
> # s/runcom/opencontainers/g
> $ go get github.com/opencontainers/image-tools/cmd/oci-validate
> $ go get github.com/opencontainers/image-tools/cmd/oci-unpack
> $ go get github.com/opencontainers/image-tools/cmd/oci-create-runtime-bundle
> ```
> The `oci-` prefix is ugly but is making sure commands like `unpack`
> and `validate` do not conflicts with already installed binaries -
> should we care? because it's much nicer w/o that prefix.
> 
> Thoughts? Preferences?

The prefix should be oci-image-… to avoid conflicting with
oci-runtime-… (which is presumably what ocitools will be installing
after opencontainer/tob#18).

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 03:18:19AM -0700, Antonio Murdaca wrote:
> $ go get github.com/opencontainers/image-tools/cmd/oci-validate
> $ go get github.com/opencontainers/image-tools/cmd/oci-unpack
> $ go get github.com/opencontainers/image-tools/cmd/oci-create-runtime-bundle
> ```
> The `oci-` prefix is ugly but is making sure commands like `unpack`
> and `validate` do not conflicts with already installed binaries…

Wait, are you switching to install these as separate binaries?
Instead of the current situation where they are sub-commands of a
wrapping oci-image-tool?

**Comment by runcom** [comment]
> Wait, are you switching to install these as separate binaries?
> Instead of the current situation where they are sub-commands of a
> wrapping oci-image-tool?

yes

**Comment by runcom** [comment]
@wking I don't see how we would have image-toolS if it's just one - also they're pretty good standalone  right?

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 11:02:03AM -0700, Antonio Murdaca wrote:
> @wking I don't see how we would have image-toolS if it's just one -
> also they're pretty good standalone right?

If they're good standalone (and I think they are), make them separate
projects ;).  Why pin versioning for the validator to versioning for
the unpacker?

On the other hand, I'm also ok with them being the suite of core tools
for the format, and having them as sub-commands of a top-level
oci-image (oci-image-tool, or oci-image-tools, or ocii, …).

**Comment by stevvooe** [comment]
Please don't remove `oci-` prefix.

**Comment by philips** [comment]
yes, please keep oci-. If the toolkit gets huge at some point down the road we can add an optional git style `oci <subcommand>` tool or something.

**Comment by runcom** [comment]
@stevvooe @philips @vbatts et all - alright, I'll keep it. Just in case the new repo is going to be populated, this repo https://github.com/runcom/image-tools contains the code with this cmd split to be moved to opencontainers/image-tool

**Comment by s-urbaniak** [comment]
:+1: on keeping the `oci-` prefix

**Comment by stevvooe** [comment]
@runcom Can we close this?
