### ISSUE TITLE
Image IDs and checksums

### ISSUE THREAD

**Issue by blakelapierre** [opencontainers/image-spec#30]
@philips [requested](https://news.ycombinator.com/item?id=11498633) an issue to require [Image IDs](https://github.com/opencontainers/image-spec/blob/master/serialization.md) to be crypto hashes and not be randomly generated.

> Image ID

> Each layer is given an ID upon its creation. It is represented as a hexadecimal encoding of 256 bits, e.g., a9561eb1b190625c9adb5a9513e72c4dedafc1cb2d4c5236c9a6957ec7dfd5a9. Image IDs should be sufficiently random so as to be globally unique. 32 bytes read from /dev/urandom is sufficient for all practical purposes. Alternatively, an image ID may be derived as a cryptographic hash of image contents as the result is considered indistinguishable from random. The choice is left up to implementors.

However, wouldn't that make

>Image Checksum

>The checksum is a cryptographic digest of the artifact.

redundant?

I'm not sure why you *shouldn't* be able to use a 'random' (or other) ID, but I'm also not sure why you wouldn't want to use a hash of the content.

**Comment by timthelion** [comment]
@blakelapierre The reason you shouldn't be allowed to use a random ID is that when one downloads an image from a sever based on an ID, if the ID is random that user has no idea what they are downloading. This allows the server to send them a different image than the one they requested.

Worse, it can lead to actual security flaws. It used to be that the docker registry served layers based on the layer id, that is, you would request a url like `registry.docker.io/layer=randomid123`. And anyone could upload layers. So it was then possible to upload a layer with the id `randomid123` and overwrite a layer that already existed in the registry. So anyone could replace the base Debian layer with a virus!

The image checksum and the image ID would not be the same. The image checksum would be the checksum of `layer.tar` while the layer id would be the checksum of `layer.tar` along with all of the meta-data surrounding it.

**Comment by philips** [comment]
I think this is a dupe of https://github.com/opencontainers/image-spec/issues/30. I am closing it in an effort to consolidate but LMK if I misunderstood.
