### ISSUE TITLE
layer: hardlink verbiage

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#306]
reference: https://github.com/opencontainers/image-spec/pull/255/files/f5a91ffe001afe2308628b112f3d9534fb94c2da#r78089784

Iron out the wording for a layer changeset preserving hardlinks (where applicable).

**Comment by philips** [comment]
We have three options:

1. Be explicit saying they aren't supported
2. Saying it is implementation specific
3. Trying to write down something about how to explicitly handle it

We can look at what is happening in the current media type handling in Docker Engine. @stevvooe can try and hunt that down.

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 02:25:55PM -0700, Brandon Philips wrote:
> We have three options:
> 
> 1. Be explicit saying they aren't supported
> 2. Saying it is implementation specific

(1) seems overly restrictive.  I think this is like #304, where you
want to allow implementations to extend the spec (and support
something like hardlinks that it doesn't currently define) but suggest
that portable images avoid these implementation-defined extensions
without and out-of-band reason to expect support.

> 3. Trying to write down something about how to explicitly handle it

This is fine too.  So I think the choices are whether to:

a. Define a hardlink serialization procedure.
b. Require implementations (on a given platform?) to support it.

**Comment by stevvooe** [comment]
[Here](https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L313) is the hard link handling in docker.
