### ISSUE TITLE
include URL to the project

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#307]
Anyone that uses the cli tools ought to have see a URL to the project in the usage (`--help`), so that:
* they can learn more on the spec that the tool is referencing
* they can report issues

**Comment by runcom** [comment]
@vbatts do we want the URL to show up only when `oci-image-tool --help` (or w/o `--help`) or with every subcommand? it requires to duplicate that URL to every subcommand if we go to show it on every subcommand. Is this for 0.5.0?

**Comment by vbatts** [comment]
I wasn't think that every subcommand need it... but maybe? I'm not convinced. Only that it need to be discoverable.

And this is just a nice-to-have, not related to v0.5.0

**Comment by philips** [comment]
This issue was moved to opencontainers/image-tools#13
