### ISSUE TITLE
HTML and PDF clean-up

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#314]
From OCI F2F items: https://docs.google.com/document/d/1bsi9JCnmOMSZCDh3VmDCO1m17w1aNexX09naomcpUOs/edit

I'll take point on this, but would like input/feedback from  @RobDolinMS and @stephenrwalli

**Comment by vbatts** [comment]
@RobDolinMS and @stephenrwalli Feedback on particulars for this?

**Comment by vbatts** [comment]
This is a pretty loose marker. I'm moving it to a later milestone until hearing specific feedback

**Comment by jonboulle** [comment]
from F2F: try using Hugo?

**Comment by philips** [comment]
I am moving this to rc4 based on discussion on the mailing list that HTML and PDF isn't really the end goal as much as a top to bottom readable spec: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/XNreeSORPTQ

**Comment by vbatts** [comment]
This google doc is not longer readable. We've done stuff to improve in this area. I'm going to close this particular issue, and folks can open issues/PRs for specific improvements.
