### ISSUE TITLE
The word `serializaton` of build-diagram.png  should be changed?

### ISSUE THREAD

**Issue by coolljt0725** [opencontainers/image-spec#322]
After  split serialization into image and layer(71650f273d012516d2c9a322f6b67d27b6ba05ef) and rename serialization.md -> config.md (17c1f00097a716ca369d089159dd9569e7a0e0d0), the word in `serializaton` of `build-diagram.png` should be changed?

**Comment by wking** [comment]
On Sun, Sep 18, 2016 at 07:07:18AM -0700, Lei Jitang wrote:
> After split serialization into image and layer (71650f27) and rename
> serialization.md -> config.md (17c1f000), the work in `serializaton`
> of `build-diagram.png` should be changed?

Yeah, probably to “layer”.  @philips, can you update [1] and PR a new
image?

[1]: https://docs.google.com/drawings/d/1cYRHLBq3b7fTDeuLsXg1htr4B9eeORc3XATzJuK-YiM/edit

**Comment by wking** [comment]
Fixed by #357.
