### ISSUE TITLE
config.md: clarify which filed is required or optional

### ISSUE THREAD

**Issue by coolljt0725** [opencontainers/image-spec#331]
It's not clear which filed is required or optional in `config.md`(https://github.com/opencontainers/image-spec/blob/master/config.md)
We should make this clear.

**Comment by wking** [comment]
On Mon, Sep 19, 2016 at 07:51:00PM -0700, Lei Jitang wrote:
> It's not clear which filed is required or optional in `config.md`

Dup of #251?

**Comment by coolljt0725** [comment]
yes, it's a dup
