### ISSUE TITLE
Media type v1 (or not) inconsistency

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#338]
Currently we define `Descriptor` in `specs-go/descriptor.go`, but its media type in `specs-go/v1/mediatype.go` as `application/vnd.oci.descriptor.v1+json`.  It seems like we should decide whether the type is being versioned or not.

* If it is being versioned:
    * shift `Descriptor` to `specs-go/v1/descriptor.go`
* If it is not being versioned (because we are committing to eternal forward compat):
    * shift `MediaTypeDescriptor` to `specs-go/mediatype.go`, and
    * rename the media type to `application/vnd.oci.descriptor+json`

We have the same inconsistency for layers, where the media types are defined in `specs-go/v1/mediatype.go` but lack a `.v1` in the type string.

**Comment by glestaris** [comment]
I think moving the `Descriptor` to v1 makes more sense to me. It feels odd to have everything else versioned except the descriptor.

**Comment by vbatts** [comment]
not opposed to moving it. Wondering whether it'd need the specs.Versioned fields as well.

**Comment by wking** [comment]
On Thu, Sep 22, 2016 at 11:01:46AM -0700, Vincent Batts wrote:
> Wondering whether it'd need the specs.Versioned fields as well.

In almost all cases we can version using the media type stored on the
referencer.  For example, if blob A is (or contains) a descriptor
pointing to blob B, we can look at A.mediaType to figure out B's media
type without having to inspect B itsefl (e.g. trying to decode it into
specs.Versioned).

That approach doesn't work for refs though (since they don't have
descriptors pointing at them), and you'd have to tie the ref-payload
media type to the image-layout oci-layout file and its
imageLayoutVersion (bumping that version whenever you change the
ref-payload media type, e.g. to
application/vnd.oci.descriptor.v1.1+json, or
application/vnd.oci.descriptor.v2.0+json, or whatever).

So as long as future descriptor types still include information about
the media type of the referenced blob (and I think future descriptor
formats should still include that information), I don't think we need
to include specs.Versioned, and I'd rather avoid it and the implied
need for some initial blind inspection of the referenced blob.
