### ISSUE TITLE
Create golden standards to test against json schema

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#34]
We need a few "golden standards" to test against the json schema specs to catch unintentional changes. It will also help in having them as part of PRs that show the schema change and how it affects the "golden standard".

@vbatts Thoughts?

**Comment by philips** [comment]
+1 on that. It would be nice to have it test both the markdown embedded and examples but that is more of a nice to have.

**Comment by vbatts** [comment]
So we could add the files from the embedded markdown examples as files, and have a test target against them.
https://gist.github.com/vbatts/b3e4fc231fbc92a9cbc28b9184f0b2d2 is what I was using when writing the schema.

I'm not really sure of a clean way to work with the examples while they're embedded in the markdown though.

**Comment by wking** [comment]
On Sat, Apr 16, 2016 at 07:57:13AM -0700, Vincent Batts wrote:
> I'm not really sure of a clean way to work with the examples while
> they're embedded in the markdown though.

Probably just make sure all embedded examples are subsets of the
stand-alone example JSON.  It shouldn't be too hard to pull out the
JSON blocks by looking for ‘```json’ and ‘```’ delimiters, and then
checking to see if that snippet is contained in one of a set of
stand-alone files.  If this approach sounds useful, I'm happy to write
tooling for it (although it would probably be in Python ;).

**Comment by philips** [comment]
@stevvooe Are you going to work on this?

**Comment by stevvooe** [comment]
I can look into it, but I'm not very familiar with JSONSchema. If anyone could suggest tools or an approach, that would be helpful.

I'll probably just use a Go package and a Makefile, barring common tools above.

**Comment by wking** [comment]
On Wed, Apr 20, 2016 at 03:56:44PM -0700, Stephen Day wrote:
> I can look into it, but I'm not very familiar with JSONSchema. If
> anyone could suggest tools or an approach, that would be helpful.

#18 and #32 already landed the JSON Schema and Go tooling for
validating stand-alone JSON [1], so you probably don't need to write
new stuff there.  There's a README for that approach in [2], if that
helps get you started.

You will need to add the example JSON manifests, etc. that are used to
test the schema, and some tooling to run validate.go against the
example manifests, etc.

[1]: https://github.com/opencontainers/image-spec/tree/master/schema
[2]: https://github.com/opencontainers/runtime-spec/blob/48428a49ff3f943efd284835256f1c2448bb554c/schema/README.md

**Comment by stevvooe** [comment]
@wking Thanks!

validate.go should be sufficient to get started. Do we want to consider the specification to be the source of all golden standards?

**Comment by stevvooe** [comment]
Took a small pass at this in #41.

#41 proposes maintaining examples in specifications. All examples are a part of the specification, rather than maintaining them in external files.

If we like that approach, I can round out that PR and we can move forward.

**Comment by vbatts** [comment]
I like it.

**Comment by vbatts** [comment]
Also, it would dictate that a new item for the `style.md` showing how to do
the mime-type json examples.
