### ISSUE TITLE
content of manifest doesn't match the spec with image files build-diagram.png and run-diagram.png

### ISSUE THREAD

**Issue by TrumanLing** [opencontainers/image-spec#343]
From the spec definition and according to my understanding of this spec, it should not appear field for ```manifests``` array.

**Comment by vbatts** [comment]
I noticed this too. It produces the right then when `make docs` is run, but it ought to be checked in

**Comment by TrumanLing** [comment]
@vbatts I have tried to run `make docs`, it didn't make sense. Also, I checked `Makefile`, there is no any option with image files `build-diagram.png` and `run-diagram.png`.

@philips I found you checked in these two image files on May 24,2016, would please update them? Of course, I am willing to do it, but I have no the original and editable file.

**Comment by wking** [comment]
On Tue, Sep 27, 2016 at 11:40:19PM -0700, TrumanLing wrote:
> @philips I found you checked in these two image files on May
> 24,2016, would please update them? Of course, I am willing to do it,
> but I have no the original and editable file.

The commit message and PR landing them point at Google docs (74114b73,
#86).  I pinged @philips asking for a change [1], because I can't edit
those docs.

[1]: https://github.com/opencontainers/image-spec/issues/322#issuecomment-247910829

**Comment by philips** [comment]
Fixed in #357.

**Comment by TrumanLing** [comment]
@vbatts @philips is it OK for an OCI image taking a manifest list? And I think it is mismatched with description ```This specification defines how to create an OCI Image, which will generally be done by a build system, and output an image manifest, a set of filesystem layers, and an image configuration``` in the specification.

**Comment by wking** [comment]
On Mon, Oct 17, 2016 at 06:36:20PM -0700, TrumanLing wrote:
> @vbatts @philips is it OK for an OCI image taking a manifest list?
> And I think it is mismatched with description ```This specification
> defines how to create an OCI Image, which will generally be done by
> a build system, and output an image manifest, a set of filesystem
> layers, and an image configuration``` in the specification.

I'd like to see a manifest in the image too [1], and it's good to have
the image match the surrounding text.  @jonboulle feels like the
manifest link in the “high-level components” line a bit futher down is
complicated enough without mentioning manifest lists [2].  Maybe we
could have a new entry in the “high-level components” list talking
about multi-platform images and linking to manifest-list.md?

[1]: https://github.com/opencontainers/image-spec/pull/357#issuecomment-250849422
[2]: https://github.com/opencontainers/image-spec/pull/367#discussion_r81938498
