### ISSUE TITLE
bburns need an email update

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#355]
@brendandburns what is your new email, for the MAINTAINERS file?

**Comment by wking** [comment]
On Fri, Sep 30, 2016 at 10:01:25AM -0700, Vincent Batts wrote:
> @brendandburns what is your new email, for the MAINTAINERS file?

Somewhat recent, if you have a local, unobfuscated copy: [1].

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/XwIb5czltSE/a9vpJN7oCwAJ
     Subject: Re: [image-spec VOTE]: Tag 2bae0dc as v0.4.0 (closes 2016-08-07 16:20 UTC)
     From: brendan...@gmail.com
     Date: Tue, 16 Aug 2016 12:44:47 -0700 (PDT)
     Message-Id: <30e3ab0e-75c9-4526-95ae-f425a4ba17c7@opencontainers.org>

**Comment by jonboulle** [comment]
bburns@microsoft.com

W. Trevor King <notifications@github.com> schrieb am Fr., 30. Sep. 2016,
19:14:

**Comment by RobDolinMS** [comment]
I'll take care of this one

**Comment by RobDolinMS** [comment]
Submitted #356 to resolve this issue
