### ISSUE TITLE
Consider a packed archive format for content addressable content

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#38]
With `docker save`, we typically have a complete image that can be transported independent of a registry. It includes configuration, layers and pointers to the actual content.

For OCI, we should define a similar tree-structured format focused on distributing OCI manifests and constituent content addressable content. The resulting archive can be used to transport complete OCI images based on manifests.

**Comment by philips** [comment]
I am certain that this is the same spirit of @vbatts issue on https://github.com/opencontainers/image-spec/issues/23

**Comment by stevvooe** [comment]
@philips No, it is quite different. I understood his issue is identifying the actual artifacts involved in an image, whereas this is a format for packing them into a single file.

Using multimedia encoding as an example, imagine #23 as being the video encoding format and this issue as defining the container format, such as mkv or mp4.

**Comment by vbatts** [comment]
I'm confused. This sounds like what I was (poorly) attempting to arrive at. 
With a user story like "As an opensource project, I want to produce an OCI image for the world to consume" what do I do to get this packed archive?

**Comment by stevvooe** [comment]
@vbatts Perhaps, with the original title. The new title is now "Outline the transportable objects". I saw that as defining the inner components (manifests, layers, image config, etc.).

I was imagining it like this:

```
[runtime bundle] -> [image spec components] --+----> [pack] --> [transports]
                                              |
                                              +----> [transports]
```

Are separate these concerns?

**Comment by crimeminister** [comment]
I am curious as to whether or not OCI is committed to tar as the only export format for images. Is there any value in looking at other options, e.g. 7z, SquashFS, etc.?

**Comment by wking** [comment]
On Wed, Apr 20, 2016 at 02:28:56PM -0700, Robert Medeiros wrote:
> I am curious as to whether or not OCI is committed to tar as the
> only export format for images. Is there any value in looking at
> other options, e.g. 7z, SquashFS, etc.?

I think the OCI specifying a particular family of serializations and
distribution APIs is independent of whether a discovery registry
*requires* those serializations and distribution APIs [1].  In that
case, OCI work like this issue doesn't exclude alternative
serializations from the discovery-registry ecosystem (although a
particular fetcher may not end up supporting all protocols).

[1]: https://github.com/opencontainers/image-spec/issues/15#issuecomment-209090608
     See the “registered protocol” stuff.

**Comment by kamalmarhubi** [comment]
@crimeminister I'd be interested in having SquashFS usable for this purpose on Linux. It would allow building the runtime layout via mount which is a nice property.

**Comment by vbatts** [comment]
@crimeminister I do like the use-cases using squashfs. They enforce read only, the kernel supports them nicely, and they compress well for transport.
Tar archives are also surprisingly widely support and are the current primary packaging format for containers. While I hope to see more innovation in this area, I expect things may stay partially favoring to tar archives.

**Comment by stevvooe** [comment]
While SquashFS may be an appropriate target, "the kernel" assumes linux.

However, I am not sure that this is relevant to this issue. In this issue, we are more focused on how the target artifacts are shipped. Whether or not they are SquashFS is irrelevant. This may make more sense to discuss in #23, where a SquashFS artifact could be a possible element of an image.

**Comment by philips** [comment]
I am still not seeing how this discussion is different than #23. Can someone give me a concrete straw man example? @stevvooe? Or maybe we can chat on the call tomorrow about it?

**Comment by wking** [comment]
On Tue, May 24, 2016 at 01:52:25PM -0700, Brandon Philips wrote:
> I am still not seeing how this discussion is different than #23.

Based on [1], my guess is that @stevvooe expected #23 to be about
“what are our fundamental objects?” (e.g. layer blobs, configs,
manifests, tags, …) while this issue would be about “how do we pack
those objects into an archive format?” (e.g. make a tarball with the
blobs at blobs/{algo}:{digest}, the manifests at manifests/{name}, …).
Since #23 is attempting to address both of those issues at once, I
expect this issue can be closed.

On the other hand, if #23 gets refocused on *what* is getting
distributed (ignoring how that gets packed into a file), I think that
would let it settle down faster.  And once it settles down, figuring
out how to pack it into a file will be less contentions (since that's
just about performance, instead of also being about the modeling).

[1]: https://github.com/opencontainers/image-spec/issues/38#issuecomment-212605856

**Comment by stevvooe** [comment]
@philips @wking hit the nail on the head. These are different concepts. Defining them at the same time will lead to over-coupling of this format and the components. Content-addressable native systems may not even want to use this component of the specification to do distribution.

Albeit, the discussion in #23 has centered around the archive format described in this issue's description.

#23 should really focus in on outlining the system objects and not how they are packaged. This will ensure flexibility and consistency as future components are added.

This issue should focus on finding an abstraction for the objects outlined in #23 and how to discover them within the archive. This abstraction could even be used to define the generic tree mapping for filesystem layout and archive packing for at-rest image content.

**Comment by philips** [comment]
@stevvooe I think we need to refile these tickets because I am not seeing the difference. There are likely some tactical things that need to get done to make this spec useful in the context of todays use cases and tech. And then some architectural things that can be done to make abstractions beautiful and generic. 

Perhaps we can close this issue and a concrete proposal can be made in a new issue or PR? A large amount of this issue is centered around confusion and probably should just be restarted.

**Comment by vbatts** [comment]
So, given the removal of combined #95, and the progress of #94, it seems like this issue would just be permutations of the layout defined in #94. Right?

**Comment by philips** [comment]
@vbatts right, I think this issue is now just about here is the image-layout as a zip, here it is as a tar gz, etc.

@stevvooe Does that make sense to you?

**Comment by wking** [comment]
Doesn't #94 exactly solve this issue [1]?  Now that we have a clear
way to pack blobs and refs into a tar/zip/…, I don't think there's
anything left to do for this issue (and we can close it).

[1]: https://github.com/opencontainers/image-spec/issues/38#issuecomment-221431302

**Comment by stevvooe** [comment]
@philips @vbatts I think the original concern here is covered by #94. We can close this.

There may be a gap for laying out files in arbitrary trees, such as mapping to a zip. This would include a simplified resource model (read: only files and directories). I see this as being the model layout for ssh/sftp and other file-based transports, if possible.

Do we have an issue for this? If not, I'll file one. This is probably outside of 1.0, but may require a pass of the image layout to ensure it doesn't prevent us from mapping to other archives in the future, before 1.0.

**Comment by philips** [comment]
@stevvooe I don't know of a image-layout serialization/mapping issue. I will let you close this out once you file a new issue.

**Comment by stevvooe** [comment]
Filed #140, closing
