### ISSUE TITLE
"Layer" is not the right term

### ISSUE THREAD

**Issue by kamalmarhubi** [opencontainers/image-spec#39]
Given the discussion on #37 and [on the mailing list](https://github.com/opencontainers/image-spec/issues/37#issuecomment-212637246), non-chain topologies of "layers" are possible and parents are in fact optional. Given this, I think the term "layer" is not ideal. I think it comes directly from Docker's implementation and particularly from the Dockerfile build mechanism. For this spec, I think these should be considered historical, and not have a strong bearing on how images are defined, and what terminology is used.

As a use case, it should be possible to define an image as a collection of disjoint archives. Say I have a statically linked server binary, and a tree of files for it to serve. I would like to specify an image as combining these two, with neither the parent of the other. The ideal here would be to allow
- changing the binary without needing to redistribute the data
- changing the data without needing to redistribute the binary

In this setup, I'd find the term "layer" confusing.

**Comment by wking** [comment]
On Wed, Apr 20, 2016 at 07:51:49PM -0700, Kamal Marhubi wrote:
> Given the discussion on #37 and [on the mailing
> list](https://github.com/opencontainers/image-spec/issues/37#issuecomment-212637246),
> non-chain topologies of "layers" are possible and parents are in
> fact optional.

While I don't think baking parent information into a layer is
necessary [1], all Docker-like serialization formats I've seen use a
single, ordered array of tarballs (with whitelist/blacklists?).  I'm
personally a fan of the increased granularity (sub-file!) of IPFS's
unixfs objects (to avoid issues like [2]), but as long as the
serialization is based on an ordered array of tarballs I think the
“layer” term is fine.

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/Lvv4eZd4BXU/pCj4qvO6DgAJ
     Subject: Re: image-spec: Can layer parents be omited? Are non-chains possible?
     Date: Wed, 20 Apr 2016 14:20:09 -0700
     Message-ID: <20160420212009.GV22888@odin.tremily.us>
[2]: https://github.com/docker/docker/issues/3156#issuecomment-30345313
     Subject: host-mounted volumes in Dockerfile's VOLUME

**Comment by philips** [comment]
I agree this is something we should discuss and address. I am making it a post v1.0.0 item though.

**Comment by vbatts** [comment]
[Appc/spec](https://github.com/appc/spec) allows this. In fact the folks at BlaBlaCar are doing this in https://github.com/blablacar/dgr
It's something I feel ought to be allowable, but not immediately if it's going to break compatibility in this initial v1 release.

**Comment by kamalmarhubi** [comment]
@vbatts 
> but not immediately if it's going to break compatibility in this initial v1 release.

I find this notion of breaking compatibility in a v1 to be odd. I opened #42 to make sure I'm understanding correctly that v1 is meant to be compatible with Docker's current spec.

**Comment by vbatts** [comment]
@kamalmarhubi It seems odd, granted, and I would like it to not be the case either. The intention of the spec is to carry forward lessons learned, and build on the pervasive industry standards. So some changes that would break much infrastructure need to be planned and coordinated. It's not an entirely clear line.

**Comment by vbatts** [comment]
@kamalmarhubi would you say that #102 is more articulately the same as your issue?

**Comment by kamalmarhubi** [comment]
Yes I think so! Closing this because the important part is that feature and less so the name.
