### ISSUE TITLE
Build story: producing an OCI image

### ISSUE THREAD

**Issue by TomasTomecek** [opencontainers/image-spec#396]
The image spec is really awesome and I can't wait to see a stable release of the spec, integrated everywhere.

What I'm personally missing right now is a way to produce (build, compose, orchestrate; name it the way you want) an image: I mean a spec for steps needed to create an image. I'm sure that's very much out of scope of this project. What I'm interested in is
1. if such spec will ever be part of OCI
2. or if there are any plans in this area
3. or if this topic is really up to vendors to deal with

I really would like to know @vbatts' ideas about this.

**Comment by amitsaha** [comment]
You can learn a bit more about it here  https://github.com/opencontainers/image-spec/issues/126

**Comment by TomasTomecek** [comment]
@amitsaha thanks for the link! I think that this issue goes even one step further: it's not just about implementing the spec, it's also about producing images valid in this spec.

**Comment by wking** [comment]
On Tue, Oct 18, 2016 at 11:43:49PM -0700, Tomas Tomecek wrote:
> What I'm personally missing right now is a way to produce (build,
> compose, orchestrate; name it the way you want) an image: I mean a
> spec for steps needed to create an image.

I'm not sure if @cyphar is actively maintaining it (he's getting
pulled in quite a few directions at the moment ;), but there's also
[1].

I've also posted a rough sketch [2] using the API that's in flight in
opencontainers/image-tools#5.  I haven't kept that sketch up to date
with recent image-tools changes, but the basic idea still applies.

And the in-flight opencontainers/image-tools#8 makes creating layers
easier, although you can find very similar code in containers/storage
(from which opencontainers/image-tools#8 sourced its layer-creation
logic) and docker/docker (from which containers/storage sourced its
layer-creation logic).

[1]: https://github.com/cyphar/oboci
[2]: https://github.com/wking/image-spec/commit/2886c655edec1a22d2b246324d5a00c645e57a9f

**Comment by cyphar** [comment]
> I'm not sure if @cyphar is actively maintaining it (he's getting pulled in quite a few directions at the moment ;), but there's also [1].

Yeah, I'm having a busy month. Currently we at SUSE are planning on integrating some kind of OCI-image-building support into [KIWI](https://github.com/suse/kiwi) once image-spec 1.0 is released. I'm going to be heavily involved with that work (which will involve essentially all of the same background work required for oboci). Once the KIWI integration is somewhat working (at least my bits) I'll then work on porting that work over to oboci. My plan was to make oboci the core of the KIWI integration, but we agreed that it's better to keep the two ideas separate (KIWI has a very different methodology when it comes to building images).

**Comment by jonboulle** [comment]
FWIW, the intention is that [acbuild](https://github.com/containers/build) will support OCI images, but this is still a WIP: https://github.com/containers/build/issues/249

**Comment by cyphar** [comment]
The more the merrier. :wink:

**Comment by TomasTomecek** [comment]
Thanks everyone for all the pointers, this is what I was hoping to get.

**Comment by vbatts** [comment]
cc @erikh has mentioned adding support to [box](https://github.com/erikh/box)
I think this issue is able to be closed

**Comment by jonboulle** [comment]
Preliminary support also added in containers/build . I think we can close this out for now and keep ongoing track of implementations via the doc added in #602.
