### ISSUE TITLE
Should we move examples near the top of their sections?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#425]
I sat down with a paper copy of the Image spec over lunch yesterday and one of the things that struck me was that it would be more readable if the examples were at the top and then descriptions of each element followed.

Do others think this would be useful for understandability / readability?

**Comment by wking** [comment]
On Fri, Oct 28, 2016 at 02:26:49PM -0700, Rob Dolin (MSFT) wrote:
> … it would be more readable if the examples were at the top and then
> descriptions of each element followed.

Are there other examples of specs that lead with informative examples?
I think it might just be a sign that we need to keep working on
readability for the normative parts ;).

**Comment by caniszczyk** [comment]
I personally find it useful to see the examples up front, but that's just my pedagogical preference :)

**Comment by RobDolinMS** [comment]
>Are there other examples of specs that lead with informative examples?

A few examples that I'm aware of:
* (IETF) Atom 1.0: https://tools.ietf.org/html/rfc4287
* (W3C) Web App Manifest: http://www.w3.org/TR/appmanifest/ 
* Facebook Graph API: https://developers.facebook.com/docs/graph-api/overview/

**Comment by wking** [comment]
On Fri, Oct 28, 2016 at 03:46:27PM -0700, Rob Dolin (MSFT) wrote:
> >Are there other examples of specs that lead with informative examples?
> 
> A few examples that I'm aware of:
> * (IETF) Atom 1.0: https://tools.ietf.org/html/rfc4287
> * (W3C) Web App Manifest: http://www.w3.org/TR/appmanifest/ 
> * Facebook Graph API: https://developers.facebook.com/docs/graph-api/overview/

So we wouldn't be breaking new ground with examples-first, in which
case I'm fine either way.

**Comment by RobDolinMS** [comment]
Sounds like @caniszczyk and I prefer examples first and @wking does not have a preference.  

How do others feel?

**Comment by stevvooe** [comment]
@RobDolinMS Do we have a PR for this?

**Comment by RobDolinMS** [comment]
Closing this old issue for now.  If folks feel strongly it can be re-opened in the future.
