### ISSUE TITLE
oci-image-tool: rough sketch

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#43]
We need a tool to make it easy for people to validate and play with an OCI Image. 

Basic validation tool that can parse and inspect all of the objects inside of the OCI Image spec

```
$ oci-image-tool validate serialized-image.tar
$ oci-image-tool validate manifest.json
$ oci-image-tool validate config.json
json: cannot unmarshal object into Go value of type types.Env
```

Unpack an image on disk (dependency on https://github.com/opencontainers/image-spec/issues/23)
 to a OCI [runtime bundle](https://github.com/opencontainers/runtime-spec/blob/master/bundle.md):

```
$ oci-image-tool create-runtime-bundle path/to/image path/to/bundle
$ oci-runtime path/to/bundle
```

Details: 

- We should probably use the bog standard cobra CLI library: https://github.com/spf13/cobra
- We can steal some of the code form the actool: https://github.com/appc/spec/tree/master/actool

**Comment by vbatts** [comment]
not to be confused with https://github.com/opencontainers/ocitools ?

**Comment by philips** [comment]
@vbatts I think we should rename ocitools to ocirtool or something. It is already focused on the runtime.

**Comment by philips** [comment]
@vbatts I will work on renaming it oci-runtime-tool with @mrunalp

**Comment by philips** [comment]
@s-urbaniak is going to work on this one

**Comment by philips** [comment]
@s-urbaniak you can steal validation code from here: https://github.com/opencontainers/image-spec/pull/41

**Comment by s-urbaniak** [comment]
@philips great, thanks, this will keep me busy the next few days. Mind assigning this to me (or give privileges to do so)

**Comment by s-urbaniak** [comment]
@vbatts @philips How about moving `github.com/opencontainers/ocitools` to `github.com/opencontainers/runtime` and create a `github.com/opencontainers/image` repo for the implementation of this very issue?

The directory structure could be:
```
$GOPATH/src/github.com/opencontainers/runtime
 ├─ cmd
 │  ├─ runtimetest
 │  └─ oci-runtime-tool
 └ ... oci runtime pkg API src ...
```
and for the image concerns an equivalent:
```
$GOPATH/src/github.com/opencontainers/image
 ├─ cmd
 │  ├─ oci-image-examples
 │  ├─ oci-image-json
 │  └─ oci-image-tool
 └ ... oci image pkg API src ...
```

**Comment by philips** [comment]
@s-urbaniak I think keeping the tool with the spec is good. It means overtime spec changes come with working code for handling the schema. Honestly I hope we can merge ocitool back into the runtime repo at some point.

**Comment by s-urbaniak** [comment]
@philips I am writing a basic validation function now, stealing ideas from `actool`.

Validation in a first rough sketch would include:
- `oci-image-tool validate --type config`: simple validation of _application/vnd.oci.image.serialization.config.v1+json_
- `oci-image-tool validate --type manifest`: simple validation of _application/vnd.oci.image.manifest.v1+json_, or _application/vnd.oci.image.manifest.list.v1+json_ (auto-detected)
- `oci-image-tool validate --type image`: as sketched in per https://github.com/opencontainers/image-spec/issues/23#issuecomment-212636147

I am implementing it using auto-detection in mind as per `actool` such that the user can actually omit `--type ...`.

Next commands to implement would be:
- `unpack`: as discussed per OOB this would be a simple deflate mechanism considering all the layers in an image file.
- `create-runtime-bundle`: Create a runtime bundle as per https://github.com/opencontainers/runtime-spec/blob/master/bundle.md

**Comment by philips** [comment]
@s-urbaniak LGTM, LMK when you get something going and I can look at a branch or WIP PR.

**Comment by philips** [comment]
Moving to v0.2.0 as we are fixing upstream packages like the go json schema library and I don't want to block a release.

**Comment by philips** [comment]
@s-urbaniak are you working on create-runtime-bundle next?

**Comment by s-urbaniak** [comment]
@philips yes, that's the plan :-)

**Comment by philips** [comment]
Closing this out in favor of #99 as most of the features except that one have landed.
