### ISSUE TITLE
Version ought to be included in the docs

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#435]
Presently the tagged version of the specification is only available in `./specs-go/version.go`, but the generated PDF or HTML docs do not hold any reference to the version.

Perhaps either generate a *.md file with this info and/or include header/footer with the version info.

**Comment by RobDolinMS** [comment]
It looks like the runtime-spec has code in the makefile and specs-go/version.go to generate a version.md file and concatenate it as the first text in the HTML and PDF outputs.

Would the same approach work for the image-spec?

**Comment by vbatts** [comment]
yep. I've just been reading to see if there wasn't a simple flag or such to add a header/footer to each page rendered by pandoc.
But the same approach as runtime-spec ought to be fine.

**Comment by philips** [comment]
@vbatts Are you taking this one?

**Comment by RobDolinMS** [comment]
@vbatts Would you want to take this one?

**Comment by vbatts** [comment]
https://github.com/opencontainers/image-spec/pull/545 addresses this
