### ISSUE TITLE
Define URLs' scheme

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#436]
Descriptor's props at https://github.com/opencontainers/image-spec/blob/master/descriptor.md#properties do not talk about which scheme a URL should have.
Should we define that URLs SHOULD have either http or https scheme? leaving other scheme (ftp, file) to be used as well, but enforcing http[s]? or should we leave it as is and maybe link https://tools.ietf.org/html/rfc1738?

/cc @vbatts @philips @jonboulle

**Comment by wking** [comment]
#431 is using JSON Schema's [`uri` format][1], which requires [RFC 3986][2].  I think we should make that requirement explicit in the Markdown.

[1]: https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7.3.6
[2]: https://tools.ietf.org/html/rfc3986

**Comment by vbatts** [comment]
interesting. Having it as URI is well known and supported by many libraries. Then having "a SHOULD support http/https" seems like a decent approach.

**Comment by wking** [comment]
On Thu, Nov 03, 2016 at 01:44:00PM -0700, Vincent Batts wrote:
> Then having "a SHOULD support http/https" seems like a decent approach.

Sounds like a consensus :).  I've filed #442 with suggested wording.
