### ISSUE TITLE
Annotations for descriptors?

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#440]
In #438, @vbatts proposed [optional ref annotations][1]:

```json
{
  "ref": "stable",
  "annotations": {
    "org.waffles.with": "syrup,raspberries",
    "io.flatpak.app.name": "org.gnome.gedit"
  }
}
```

to support [“top level views” in tooling that may publish or fetch from an OCI image-layout][2].  I'm not entirely clear on that use case, but it brings up two questions:

1. Do we need annotations for refs?  Basically, can someone explain the “top level views” use-case in more detail.
2. After establishing (1), can we accomplish that same goal by adding `annotations` to our descriptor model?  This would allow us to support ref (and other) annotations even for refs accessed by the `ref/` directory or other ref engine.

[1]: https://github.com/opencontainers/image-spec/pull/438/commits/7cffab1a17090f7392cab295f81cf386e0a9a1c5#diff-99bfcb610f238b942638d49d1ff2eaf4R133
[2]: https://github.com/opencontainers/image-spec/pull/438/commits/7cffab1a17090f7392cab295f81cf386e0a9a1c5#r86392580

**Comment by vbatts** [comment]
I've just done something like this in https://github.com/opencontainers/image-spec/pull/438#issuecomment-263718993

**Comment by wking** [comment]
On Tue, Nov 29, 2016 at 02:22:18PM -0800, Vincent Batts wrote:
> I've just done something like this in
> https://github.com/opencontainers/image-spec/pull/438#issuecomment-263718993

I don't see #438 (as it stands with 9b6dd3d3) adding annotations to
the descriptor type.  And I think that's one of the things @stevvooe
was proposing [1].

[1]: https://github.com/opencontainers/image-spec/pull/438#issuecomment-264023647
     > 2. Add an annotations field to descriptor.
