### ISSUE TITLE
Separate versioning for refs and CAS portions of image-layout?

### ISSUE THREAD

**Issue by wking** [opencontainers/image-spec#441]
Spun off from #438, where I floated:

```
$ cat oci-layout
{
  "refsLayoutVersion": "1.0.0",
  "casLayoutVersion": "1.0.0"
}
```

The CAS and ref engines are completely orthogonal, and versioning them independently means that versions for a given component are bumped less frequently (e.g. a refs bump no longer triggers a CAS bump).  That's less noise for implementers who are only focused on one or the other, but maybe the set of such implementers is empty?

**Comment by wking** [comment]
There's also some discussion about the semantics of version-bumping `oci-layout` in #434 which is tangentially related to this.

**Comment by vbatts** [comment]
IMO, this topic is distracting and adds to confusion.

**Comment by wking** [comment]
On Thu, Nov 03, 2016 at 01:57:22PM -0700, Vincent Batts wrote:
> IMO, this topic is distracting and adds to confusion.

You can close it wontfix if the argument doesn't hold water (e.g. “All
implementers will care about both, so it's not noise”).

Otherwise tag it priority/Pmaybe and forget about it until we hear
complaints (possibly never).

**Comment by stevvooe** [comment]
I'm not sure I see the benefit of this.

Closing, per @vbatts.
