### ISSUE TITLE
Is the value of "Labels" in image configuration required?

### ISSUE THREAD

**Issue by qianzhangxa** [opencontainers/image-spec#471]
Hi,

I see there is "Labels" field in image configuration:
> Labels object, OPTIONAL
> The field contains arbitrary metadata for the container. Labels MUST be a key-value map where both the key and value MUST be strings. Keys MUST be unique within this map, and best practice is to namespace the keys. Keys SHOULD be named using a reverse domain notation - e.g. com.example.myKey. Keys using the org.opencontainers namespace are reserved and MUST NOT be used by subsequent specifications. If there are no annotations then this property MAY either be absent or an empty map. Implementations that are reading/processing this configuration file MUST NOT generate an error if they encounter an unknown annotation key.

So it is kind of string-string map like the "annotations" field in image manifest. In the spec of image manifest, I see it is clearly mentioned the value of each annotation must be present, but I do not see the similar statement in the spec of image configuration, so can anyone please let me know if the value of image configuration's label is required? E.g., can I have the labels like below in an image configuration?
```
"Labels": {
            "com.example.project.a",
            "com.example.project.b"
}
```

**Comment by jonboulle** [comment]
That's not a valid JSON map - you need a `: value`. And "Value MUST be
strings" states that they, well, must be strings.

**Comment by qianzhangxa** [comment]
Thanks @jonboulle for your reply, so that means similar with the annotations in image manifest, the value of the labels in image configuration must be present too, right?

**Comment by jonboulle** [comment]
Yes.
