### ISSUE TITLE
Labels field missing from exported struct

### ISSUE THREAD

**Issue by dgonyeo** [opencontainers/image-spec#478]
https://github.com/opencontainers/image-spec/pull/371 added in the labels field to [this doc](https://github.com/opencontainers/image-spec/blob/master/config.md#properties), but didn't update the struct exported by this repo ([here](https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/config.go#L18)) to include the new field. It should be added.

**Comment by vbatts** [comment]
like https://github.com/opencontainers/image-spec/pull/460 ?

**Comment by dgonyeo** [comment]
Oh hey there's a PR for this! Sorry, missed it before opening this. I'll close this then.
