### ISSUE TITLE
config: document how to translate image config into runtime config

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#479]
There are several fields in the OCI Image Config that directly translate to a fields on the Runtime Config. We should document how those fields translate.

The obvious ones:

- User
- Env
- Entrypoint
- Cmd
- WorkingDir

UX ones (used to help users but not automatically mapped):

- ExposedPorts
- Volumes

Optional as they depend on the user and largely shouldn't be dictated by image author:

- Memory
- MemorySwap
- CPUShares

**Comment by philips** [comment]
As discussed @wking @stevvooe

**Comment by philips** [comment]
@cyphar could you take a swing at adding this language?

**Comment by wking** [comment]
See also #454, which would set the required runtime-spec config version.

**Comment by cyphar** [comment]
@philips Yeah, I'll give it a shot.

**Comment by cyphar** [comment]
I've done this in #492.

**Comment by RobDolinMS** [comment]
@philips Can this Issue be closed with active discussion now happening in PR #492 ?

**Comment by stevvooe** [comment]
@RobDolinMS We should really wait for the issue to get resolved before closing it.
