### ISSUE TITLE
Add "source" back in the OCI Image Manifest

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/image-spec#498]
It looks like we dropped "source" as part of the "Pre-Defined Annotation Keys"

See this previous commit from @gregkh 
https://github.com/opencontainers/image-spec/commit/88ef945196cc5d6b1e5249470fef752a06fa96e8#diff-bf8d9e5146f89ef0a8b9bf8cd1026901

I suggest adding "org.opencontainers.source" = "URL to get the source code for the binary files in the image (string, must be a URL with scheme HTTP or HTTPS)"

**Comment by gregkh** [comment]
I don't understand, what got "dropped"?

**Comment by caniszczyk** [comment]
@gregkh unless I'm crazy, I don't see the mention of "source" in the current manifest schema:
https://github.com/opencontainers/image-spec/blob/master/manifest.md

**Comment by gregkh** [comment]
@caniszczyk ugh, ok, let me dig through the git history to figure out who to go yell at!

**Comment by gregkh** [comment]
Ah, found it, @duglin , you dropped source with your commit 873b9b64fda6eedc076e358d8c3a9056212dacb1 any reason why?

**Comment by gregkh** [comment]
let me go add it back...

**Comment by gregkh** [comment]
Now added back in PR #499

**Comment by wking** [comment]
On Wed, Dec 14, 2016 at 02:56:01PM -0800, Greg Kroah-Hartman wrote:
> Now added back in PR #499

#499 landed, so this issue can be closed.
