### ISSUE TITLE
specs-go: Image.Created uses a string type

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#517]
We have a [time field](https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/config.go#L75) that is a `string`. Let's help ourselves not make mistakes and make sure this is a proper `time.Time` or derivative type that does the right validation.

**Comment by stevvooe** [comment]
Looks like https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/config.go#L56 also has this issue.

**Comment by stevvooe** [comment]
Not that the default `time.Time` is sufficient here, since it [uses rfc3339](https://golang.org/src/time/time.go?s=26891:26934#L918).

**Comment by jlbutler** [comment]
I'm working on this.

**Comment by vbatts** [comment]
#534 is merged
