### ISSUE TITLE
ambiguity of manifest.json in Combined Image JSON + Filesystem Changeset Format

### ISSUE THREAD

**Issue by s-urbaniak** [opencontainers/image-spec#54]
https://github.com/s-urbaniak/image-spec/blob/master/serialization.md#combined-image-json--filesystem-changeset-format specifies a couple of files, none of which have any media types defined:

- `VERSION` (plain text file) schema version of the following `json` file
- `json` (json file), pointing to a "version 1" metadata format of the, which show 404.
- `repositories` (json file)
- `layer.tar` (layer tar file)
- `manifest.json` (json file) (is this the "combined Image JSON"?)

It is not clear to me how this relates to the Image Manifest file (https://github.com/s-urbaniak/image-spec/blob/master/manifest.md#image-manifest) and how we can reference a combined image from the "Image Manifest".

Also it is unclear to which of the above files the specified `application/vnd.oci.image.serialization.combined.v1+json` media type points to, the `+json` indicates a JSON format, is it `manifest.json`?

**Comment by s-urbaniak** [comment]
xref https://github.com/opencontainers/image-spec/issues/56

**Comment by vbatts** [comment]
This is unclear to me too.

**Comment by philips** [comment]
@stevvooe Can you help clear this one up?

**Comment by stevvooe** [comment]
@philips @vbatts This is the specification for the "docker save" format. 

Here is what they are, in relation to docker:

- The `json` file is just the image config corresponding to the specified layer. Used pre 1.10
- `VERSION` is the version of the `json` file, which is just as useful as `json` itself. Used pre 1.10.
- `repositories` links names to tags. Used pre 1.10.
- `manifest.json` identifies configs by tag at the top-level in 1.10+. The file `manifest.json` has nothing to do with the https://github.com/s-urbaniak/image-spec/blob/master/manifest.md#image-manifest.
- `<id>.json` are the 1.10 updated image configurations

In relation to OCI, there are few options:

1. Try to adopt everything here. It is not wildly impossible, but there are several layers. Basically, you have a pre-1.10 layer (`json`, `repositories`) and a post-1.10 layer (`manifest.json`, `<id>.json`) that need to be handled.
2. Specify 1.10 layer, removing `json`, et al.
3. Diverge from `docker save` approach and use something similar to that discussed in #38.

I hope that helps.

I am not sure where I lean here, but likely more towards the 2-3 spectrum.

**Comment by philips** [comment]
@s-urbaniak can you take @stevvooe and offer a cleanup PR?

**Comment by philips** [comment]
I think we should just drop the "combined mime-type". The format has too much history and has conflicting terminology like a "manifest.json" as @stevvooe pointed out. I am going to put up a PR to drop it and file an issue for a "image layout" (see https://github.com/opencontainers/image-spec/issues/92)

**Comment by philips** [comment]
#92 is merged. Closing this issue out.
