### ISSUE TITLE
JSON schema for the serialization formats

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#56]
Carrying over from #7 but specifically for the serialization formats.

* [x] [image JSON](https://github.com/opencontainers/image-spec/blob/master/serialization.md#image-json-description)
* [x] [`repositories` JSON](https://github.com/opencontainers/image-spec/blob/master/serialization.md#combined-image-json--filesystem-changeset-format)
* [x] [`manifest.json`](https://github.com/opencontainers/image-spec/blob/master/serialization.md#combined-image-json--filesystem-changeset-format)
* [x] [`<sha256 id>.json`](https://github.com/opencontainers/image-spec/blob/master/serialization.md#combined-image-json--filesystem-changeset-format)

**Comment by philips** [comment]
@vbatts deadbeef.json?

**Comment by vbatts** [comment]
poor name for a hexidecimal... i'll change it

**Comment by philips** [comment]
@vbatts this is referring to the "json" next to layer.tar?

**Comment by vbatts** [comment]
@philips nope. It's part of the next generation single config file, post docker-1.10 format.
```
vbatts@bananaboat ~ (master) $ docker pull alpine:latest
latest: Pulling from library/alpine                                                                                                                                                                                
                                                                                                                                                                                                                   
420890c9e918: Pull complete 
Digest: sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0                                                                                                                                    
Status: Downloaded newer image for alpine:latest                                                                                                                                                                   
vbatts@bananaboat ~ (master) $ docker save !$ | tar tv                                                                                                                                                             
docker save alpine:latest | tar tv                                                                                                                                                                                 
-rw-r--r-- 0/0            1145 2016-04-01 16:53 d7a513a663c1a6dcdba9ed832ca53c02ac2af0c333322cd6ca92936d1d9917ac.json                                                                                              
drwxr-xr-x 0/0               0 2016-04-01 16:53 eeb44f9ddc5f4336a1282f8ceef0ab934442de7b57472cdb5b058fd0926b3475/                                                                                                  
-rw-r--r-- 0/0               3 2016-04-01 16:53 eeb44f9ddc5f4336a1282f8ceef0ab934442de7b57472cdb5b058fd0926b3475/VERSION                                                                                           
-rw-r--r-- 0/0             934 2016-04-01 16:53 eeb44f9ddc5f4336a1282f8ceef0ab934442de7b57472cdb5b058fd0926b3475/json                                                                                              
-rw-r--r-- 0/0         5040640 2016-04-01 16:53 eeb44f9ddc5f4336a1282f8ceef0ab934442de7b57472cdb5b058fd0926b3475/layer.tar                                                                                         
-rw-r--r-- 0/0             202 1969-12-31 19:00 manifest.json                                                                                                                                                      
-rw-r--r-- 0/0              89 1969-12-31 19:00 repositories
```

see also https://github.com/opencontainers/image-spec/issues/54#issuecomment-216709649

**Comment by stevvooe** [comment]
Probably should carry `repositories` and `json`, as they are for pre-1.10.

**Comment by vbatts** [comment]
my big issue is that this flattens layers. Images need to be a federated DAG. This `<sha256>.json`/`manifest.json` layout requires condensing the parent config into the image.

Unless these combined layout can themselves also be layered.
But then there is no point in having multiple tar layers.

**Comment by stevvooe** [comment]
@vbatts How does this flatten layers? What we want to avoid here is having the DAG degrade to a linked list.

We can still federate with this approach. We lose the intermediary configs, but it is surprising when a single image carries all intermediary configurations. If one does want to ship the intermediaries, each intermediate can be include in the manifest.

**Comment by vbatts** [comment]
@stevvooe I understand avoiding the linked list. Perhaps it will be worth the exercise to work out the example of having a manifest, that references two of `application/vnd.oci.image.serialization.combined.v1+json` types. This is something that appc *.aci allows and would be powerful to bring in here.

**Comment by stevvooe** [comment]
I'm not sure why this requires another manifest type. Just reference each root config in the tag index. There is no need to maintain the linked the list -- this can be recovered by identifying common layers. `aci` suffers from the same "parent" degrading to linked list problem and it should be avoided for OCI.

**Comment by vbatts** [comment]
Oh sorry. I wasn't thinking of another manifest type, but rather an example
of a manifest that can allow more than one of the combined types as
objects, so those independent images do not have to be squashed and lose
the digest of their parentage.

**Comment by vbatts** [comment]
So this is all together done or N/A
Only this notion of descriptor is needed now. See https://github.com/opencontainers/image-spec/issues/92
