### ISSUE TITLE
spec: namespace image-spec labels with "org.opencontainers.image"

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#600]
When labels from images land elsewhere through propagation, it is hard to tell their source. Let's add `.image` to annotation prefix to make it clear when a label is part of an image. 

Please see https://github.com/opencontainers/image-spec/pull/492#discussion_r105034418 for the original issue.

cc @cyphar @vbatts

**Comment by cyphar** [comment]
:+1:

**Comment by vbatts** [comment]
i like the provenance, though does this include the reference to that image's manifest digest as well?

**Comment by jonboulle** [comment]
@vbatts hmm, you mean so one can reverse-trace from a runtime-spec config.json to an image?

**Comment by vbatts** [comment]
@jonboulle maybe that too, but not what i was originally thinking. More like "i have ubuntu LTS image (sha256:deadbeefface..), and add my software on top" as only the ubuntu LTS _layers_ stay referenced, but not the original manifest. This would allow a pointer to those objects.

**Comment by stevvooe** [comment]
@vbatts This was not intended to go that far. I placed a comment in #600 clarifying the possible link.

I'll create a PR for this one today.

**Comment by vbatts** [comment]
oh oh. this is just an addition onto the prefix, not an `.image` name. sorry
