### ISSUE TITLE
Check up on maintainers absenteeism and desire to be a maintainer

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/image-spec#603]
via @stevvooe :

> I think we need to give the current maintainers a chance to respond on the issue of absenteeism. 

Hey @opencontainers/image-spec-maintainers if you desire to continue to be a maintainer with the time commitments expected, please let us know. I'll leave this issue open for a couple of weeks to get feedback before we decide to add more maintainers:

https://github.com/opencontainers/image-spec/issues/590#issuecomment-285179960

**Comment by jonboulle** [comment]
I'd like to stay involved (and participate more actively, I haven't given a lot of PRs as much attention as I'd like). A significant issue for me has been the weekly call time, but fortunately seems like we're figuring that out in the [associated mailing list thread](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/p0mTOspVgd0)

**Comment by stevvooe** [comment]
@jonboulle Thank you for your increased participation!

@caniszczyk I think since we are on track now, we can close this. Any objections? @opencontainers/image-spec-maintainers

**Comment by caniszczyk** [comment]
@stevvooe SGTM however I think we should consider adding some folks based on their contribution rate by asking if they want to be nominated as a maintainer and assume responsibilities (https://github.com/opencontainers/image-spec/issues/590#issuecomment-285109834) but I leave it up to you and the @opencontainers/image-spec-maintainers to decide :)
