### ISSUE TITLE
FINAL v1.0 RELEASE BURN DOWN

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#615]
- [x] implementations on latest RC (need some citations here)
- [x] final sanity check (build consistency, terminology consistency) ( err'body )

**Comment by vbatts** [comment]
cc @caniszczyk

**Comment by caniszczyk** [comment]
@vbatts sounds good, how do other @opencontainers/image-spec-maintainers feel?

**Comment by RobDolinMS** [comment]
AFAIK, the image spec needs hyperlinks to sections.  @vbatts - Would you please add that to the release burndown checklist?

**Comment by erikh** [comment]
I'm going to take a stab at rewriting the bottom of spec.md here in a
minute which should resolve this.

**Comment by erikh** [comment]
#621 created for @RobDolinMS's issue

**Comment by philips** [comment]
Are there updates on this burndown? Are these the only two remaining issues everyone agrees upon? https://github.com/opencontainers/image-spec/milestone/3

If so +1 on getting this shipped.

**Comment by wking** [comment]
On Thu, Apr 13, 2017 at 01:26:43PM -0700, Brandon Philips wrote:
> Are these the only two remaining issues everyone agrees upon?
> https://github.com/opencontainers/image-spec/milestone/3

I was expecting an rc6 [1] before the v1.0.0 milestone [2].

[1]: https://github.com/opencontainers/image-spec/milestone/13
[2]: https://github.com/opencontainers/image-spec/milestone/3

**Comment by stevvooe** [comment]
I would expect we do an rc6 before a 1.0. The [rc6 milestone](https://github.com/opencontainers/image-spec/milestone/13) has a few issues we need to work out, as well.

**Comment by mattspencer-arm** [comment]
Hi Guys
I know this may be a bit late in the day, but ARM would like to get involved in the discussion around the arch/variant/features attributes used to identify ARM images.  I am working through a sane schema at the moment and will have something to post here later today/tomorrow morning that should allow the correct description of images containing ARM binaries.
Is my best route to add an issue to enable discussion, and what are the chances of getting our proposal discussed ahead of the v1.0 release?
Cheers
Matt

**Comment by wking** [comment]
> Is my best route to add an issue to enable discussion...

Maybe chime in on #650 and #652?

**Comment by caniszczyk** [comment]
@stevvooe how are you feeling about this getting close to RC6 and v1.0 FINAL? now that runtime-spec is getting close, it would be great to have both of the specs go out close to the same time (at least it will make my life easier with PR planning) https://github.com/opencontainers/runtime-spec/issues/726

**Comment by stevvooe** [comment]
> @stevvooe how are you feeling about this getting close to RC6 and v1.0 FINAL? now that runtime-spec is getting close, it would be great to have both of the specs go out close to the same time (at least it will make my life easier with PR planning) opencontainers/runtime-spec#726

I think we can release an rc6, but we still need to work out some issues with the platform fields before 1.0.
