### ISSUE TITLE
merge "ManifestDescriptor" and "Descriptor" types

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#618]
Currently, we have `ManifestDescriptor` and `Descriptor` types. The only difference is the inclusion of the platform field. For making generic processors that filter based on platform type, this creates a number of complexities (see https://github.com/docker/containerd/pull/638 for an example of this pattern).

We'll simply need to merge these types in the specification and struct definitions.

**Comment by qianzhangxa** [comment]
@stevvooe @jbouzane Based on the description of this ticket:
> We'll simply need to merge these types in the specification and struct definitions.

We need to update both spec and struct definition, however I think #620 only updates the struct definition, we need another PR to update spec (descriptor.md and image-index.md)?

**Comment by jonboulle** [comment]
@qianzhangxa oops, for some reason I thought that had already been done, sorry. Feel like putting up a PR?

**Comment by stevvooe** [comment]
> We need to update both spec and struct definition, however I think #620 only updates the struct definition, we need another PR to update spec (descriptor.md and image-index.md)?

Actually, this was a conscious decision not to. The alternative fields can be ignored outside the context of processing a manifest index. We only merge the Go datatype to make usage easier in practice.

**Comment by stevvooe** [comment]
@jonboulle Can we close this or did you want me to add some clarification on the difference between the spec and datatype?

**Comment by stevvooe** [comment]
@jonboulle Ping.

**Comment by jonboulle** [comment]
I'd still like to see the [tweak](https://github.com/opencontainers/image-spec/pull/638#pullrequestreview-31021778) discussed in #638 - @qianzhangxa @q384566678 either of you feel like taking this on?

**Comment by qianzhangxa** [comment]
Sure. I have submitted #649 for it.

**Comment by q384566678** [comment]
I think it should be explained for the difference. #649 looks good to me.

**Comment by q384566678** [comment]
I think the `json` file needs to be updated to coincide with the `specs-go / v1` file, just as I do [here.](https://github.com/opencontainers/image-spec/pull/638/files#diff-6f11672cc3c0cd49052d926e2ca5a82aR22)

**Comment by vbatts** [comment]
@stevvooe does #649 fix this issue?

**Comment by stevvooe** [comment]
> @stevvooe does #649 fix this issue?

This was already fixed by #620. This was never meant to have bearing on the specification.

**Comment by vbatts** [comment]
right on
