### ISSUE TITLE
specs-go/v1/config: `omitempty` is ineffective on Created

### ISSUE THREAD

**Issue by lucab** [opencontainers/image-spec#626]
https://github.com/opencontainers/image-spec/pull/534 changed `Created` from string to time.Time field. This neutered the `omitempty` property on it, as a missing field is now populated as the default time.Time value (0000-01-01).

Ref: https://github.com/golang/go/issues/11939

/cc @jlbutler as #534 author

**Comment by jonboulle** [comment]
@lucab how about submitting a patch to pointer-ify this one?

**Comment by lucab** [comment]
Ack, up at https://github.com/opencontainers/image-spec/pull/633.
