### ISSUE TITLE
The "image JSON"/"Container config JSON" does have a media-type but no schema, no headers

### ISSUE THREAD

**Issue by s-urbaniak** [opencontainers/image-spec#63]
The "image JSON" also described as "Container config JSON" https://github.com/opencontainers/image-spec/blob/master/serialization.md#image-json-description does have a media-type `application/vnd.oci.image.serialization.config.v1+json` but no schema defined.

Also the example image/config JSON does not have the `schemaVersion` and `mediaType` headers defined. I am aware this was taken over, but it seems not to be consistent with the manifest/manifest list schemas.

Finally I suggest to have a unique wording for this JSON file, either "Image JSON" or "Container config JSON" and use this wording consistently across the spec.

**Comment by philips** [comment]
@s-urbaniak is this a dupe of #56?

**Comment by s-urbaniak** [comment]
@philips yep, good catch. #56 refers to all the JSON formats in `serialization.md` which is even better, hence closing this in favor of #56.
