### ISSUE TITLE
Clarification of Image.Config.Volumes

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#682]
the spec reads:

> A set of directories which SHOULD be created as data volumes in a container running this image.

How should runtimes handle/translate volumes? is there any _correct_ way? what's the definition of a **_data volume_**? Is it a directory on the host (bind)mounted in the container?

/cc @cyphar @vbatts

**Comment by runcom** [comment]
probably related to https://github.com/opencontainers/image-spec/pull/492

**Comment by cyphar** [comment]
Feels like a dup of #496, where I was trying to get some sort of explanation of how volumes should act with regards to layers.

**Comment by cyphar** [comment]
And #504 is the PR with some wording but I haven't touched that in a while.

**Comment by jonboulle** [comment]
IMO this is covered by https://github.com/opencontainers/image-spec/pull/492/files#diff-8aafbe2c3690162540381b8cdb157112R91 ; @runcom if you disagree feel free to reopen.
