### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/image-spec#684]
https://github.com/opencontainers/image-spec/blob/master/ChangeLog
The file has not been maintained since 0.4.0.

Can we just remove this file in 1.0.0 and revive it in 1.0.1?

**Comment by vbatts** [comment]
I like ChangeLog's, but not when they're not maintained. I'm ok with
removing it.

**Comment by wking** [comment]
Previous discussion in #326.
