### ISSUE TITLE
README:  Improved introductory text

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#69]
We need to factor the spec for top to bottom reading with three audiences in mind:

- Build system creators
- Image registry creators
- Container engine creators

I will try and solicit feedback from folks on what they would like to see from the spec. And it would great if other @opencontainers/image-spec-maintainers could help out here now that we have a v0.1.0 out the door.

**Comment by vbatts** [comment]
@duglin was just mentioning this on IRC too

**Comment by philips** [comment]
I will take this one.

**Comment by philips** [comment]
Merged!
