### ISSUE TITLE
Test failing with go-digest@4ca13015b68d8b53802e6c9049953cdfc9a102ce

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/image-spec#697]
df6f3c57dafbbf39d98c24fa6ab509183cfa3efc fails with opencontainers/go-digest@4ca13015b68d8b53802e6c9049953cdfc9a102ce

(Sorry this seems my mistake)

```
--- FAIL: TestDescriptor (0.01s)
        descriptor_test.go:300: test 14: expected validation failure true but got false, err <nil>
FAIL
FAIL    github.com/opencontainers/image-spec/schema     0.045s
```

Test 14 is https://github.com/opencontainers/image-spec/blob/5302569ce491eb693c7299adff844b9ef660d542/schema/descriptor_test.go#L194-L202

**Comment by AkihiroSuda** [comment]
seems tracked in #696

**Comment by stevvooe** [comment]
@AkihiroSuda Does that need to be fixed upstream in go-digest?

**Comment by AkihiroSuda** [comment]
IIUC no, CI passing in #696

**Comment by wking** [comment]
We can probably close this with #696 landed.
