### ISSUE TITLE
Allow layer changeset applied without running container

### ISSUE THREAD

**Issue by xiekeyang** [opencontainers/image-spec#698]
If OCI image spec should allow consumer to apply [layer changesets](https://github.com/opencontainers/image-spec/blob/master/layer.md#change-types) which is defined [file types](https://github.com/opencontainers/image-spec/blob/master/layer.md#file-types), without running container in advance?

That is because some users build their images just copying some user binaries and data into image, needn't run container. And sometimes their host is slow or existing bug to run container (because devicemapper, systemd, etc...).

So may I add words in [Applying Changesets section](https://github.com/opencontainers/image-spec/blob/master/layer.md#applying-changesets) that (coarse words):
`This can be done on simply copying case without running container, and MUST after running container on relation to parent layer cases.`

@opencontainers/image-spec-maintainers Do you think it makes sense? If it is, we can realize that functionality in image tools, to provide to OCI consumer, like:

```
oci-tools layer create --mount/--link tool:/usr/bin/tool <image-name>
```

ping @stevvooe @vbatts @cyphar

**Comment by xiekeyang** [comment]
And I know that it can be done when deploying container, like `docker run -v`. But I just talk about the case when user want to publish a image.

**Comment by xiekeyang** [comment]
it is some similar to https://github.com/opencontainers/image-spec/issues/190, but of course I think it is necessary to rebuild image, apply diffs, so on.

**Comment by cyphar** [comment]
> If OCI image spec should allow consumer to apply layer changesets which is defined file types, without running container in advance?

[`umoci`](https://github.com/openSUSE/umoci) already does this, and has for quite a while (we use it to build openSUSE and SUSE container images). There isn't any wording about delta layers that specifically references containers (and any such references are bugs and should be corrected). Images are just a storage format, which contain metadata that make it easy to use them as container rootfs-es. That definitely doesn't mean you need to use containers to create them.

**Comment by wking** [comment]
On Fri, Jun 16, 2017 at 01:40:52AM -0700, Aleksa Sarai wrote:
> There isn't any wording about delta layers that specifically
> references containers (and any such references are bugs and should
> be corrected).

I agree with this.  The spec has some hints about creating layers by
comparison [1], but it doesn't say you MUST create them that way.  And
the spec for applying layers is the usual tar logic + whiteouts [2];
nothing about containers there.  So I don't see a need for
@xiekeyang's proposed wording [3]; that use case is just part of the
“everything not explicitly forbidden is allowed”.

[1]: https://github.com/opencontainers/image-spec/blob/v1.0.0-rc6/layer.md#determining-changes
[2]: https://github.com/opencontainers/image-spec/blob/v1.0.0-rc6/layer.md#applying-changesets
[3]: https://github.com/opencontainers/image-spec/issues/698#issue-236411881

**Comment by stevvooe** [comment]
@xiekeyang Thanks for the report!

There is nothing in the specification that prevents this. I don't really see a need to call this out specifically. A runtime is not required to build an image and the specification doesn't need to address this matter.
