### ISSUE TITLE
JSON schema all the things

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#7]
Carrying over the approach from https://github.com/opencontainers/runtime-spec/tree/v0.4.0/schema
We might ought to have JSON schema for the structures defined in this project and easy validation of them.

**Comment by vbatts** [comment]
do other @opencontainers/image-spec-maintainers have an opinion on this?

**Comment by vbatts** [comment]
I do like this from the swagger/openAPI https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#info-object

**Comment by vbatts** [comment]
Now that #18 is merged, next steps might be:
* [ ] Schema for the serialization document
* [ ] Decide best way to have common definitions across OCI projects (i.e. `defs.json`, etc)
* [ ] Validation tooling for an OC image archive (e.g. https://github.com/opencontainers/ocitools )

**Comment by philips** [comment]
@vbatts can you give an update on where this is now? I think serialization doc is now covered, right?

**Comment by philips** [comment]
@vbatts perhaps open a new issue for sharing and then we can close this out?

**Comment by vbatts** [comment]
There is nothing done for the serialization.md file yet, but I can track that separately. It's a more intricate document than the manifests.
