### ISSUE TITLE
pandoc: issue with displaying images

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#70]
with https://github.com/opencontainers/image-spec/releases/tag/v0.1.0
The media-types.png caused issues in the `make docs` target. See https://github.com/opencontainers/image-spec/issues/66#issuecomment-217563622

As a make-shift effort, I switched it to inline html. While that caused pandoc to not fail, it did not render the image in the resulting document.
Here's the diff that let pandoc run successfully.
```diff
diff --git a/media-types.md b/media-types.md
index 3bf7221..de6cc3b 100644
--- a/media-types.md
+++ b/media-types.md
@@ -46,6 +46,6 @@ This section shows where the OCI Image Specification is compatible with formats
 
 The following figure shows how the above media types reference each other:
 
-![Media Types](media-types.png)
+<img src="media-types.png" alt="Media Types"/>
 
 A reference is defined as the target content digest, as defined by the [Registry V2 HTTP API Specificiation](https://docs.docker.com/registry/spec/api/#digest-parameter). The manifest list being a "fat manifest" references one or more image manifests per target platform. An image manifest references exactly one target configuration and possibly many layers.
```

Other option would be a full base64 inline of the image, in an html tag. 😛

**Comment by philips** [comment]
sounds like base64 it is! :)

**Comment by philips** [comment]
This is fixed now. Closing.
