### ISSUE TITLE
manifest.md and schema/image-manifest-schema.json have diffrent type: mediaType

### ISSUE THREAD

**Issue by tanyifeng** [opencontainers/image-spec#731]
manifest.md have definition of [mediaType](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions), but [image-manifest-schema.json](https://github.com/opencontainers/image-spec/blob/master/schema/image-manifest-schema.json) have not. What is the correct description?

**Comment by stevvooe** [comment]
From [manifest.md](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions):

> This property is reserved for use, to maintain compatibility. When used, this field contains the media type of this document, which differs from the descriptor use of mediaType.

This field is effectively reserved and deprecated. Don't use it.

**Comment by tanyifeng** [comment]
I know it, Thanks. Please close this issue.

**Comment by stevvooe** [comment]
@tanyifeng No problem. Let me know if you have other questions.
