### ISSUE TITLE
OCI images？

### ISSUE THREAD

**Issue by czm4514** [opencontainers/image-spec#738]
How do I determine if the image is OCI compliant? is there any tools for me ?

**Comment by czm4514** [comment]
@wking

**Comment by cyphar** [comment]
This is part of the conformance work that is being done by a few folks. I believe that the current status is that https://github.com/opencontainers/image-tools has a `validate` subcommand which validates images. I use that in the integration tests for https://github.com/openSUSE/umoci to ensure that our images are "good".

**Comment by czm4514** [comment]
Thanks a lot ,your answer solved my problem
