### ISSUE TITLE
Official name for image format

### ISSUE THREAD

**Issue by abitrolly** [opencontainers/image-spec#754]
Is there a shorter name to this image format to compare it to other deployable artifacts and test tools for compatibility? OCI name means initiative itself, it also means runtime and it also means image. From outside it looks confusing, especially for people who are not aware of this distinction.

`rkt` is a name, `snap` is a name, even `docker( container)?' is a name. Is there an easy addressable name for "deployable artifact" covered by `image-spec`?

**Comment by abitrolly** [comment]
I am thinking in files and I like the idea that I can save deployable artifact to file and inspect it. If it was something that I can save to disk as a single file, what would be the file extension to make it stand out from the other files?

**Comment by vbatts** [comment]
@abitrolly i understand that confusion, but these files are largely content addressable objects.
so, like @cyphar said, it is largely an "OCI image". The closest thing to a file that would be _the_ artifact to deploy would be an OCI image layout inside a *.tar.
I'm going to close this for now. If you see where there this could be documented more clearly in the spec, I welcome the changes.
