### ISSUE TITLE
oci-image-tool: vendor dependencies

### ISSUE THREAD

**Issue by s-urbaniak** [opencontainers/image-spec#76]
Use a vendoring tool, i.e. glide to vendor all external dependencies

**Comment by philips** [comment]
@s-urbaniak are you still intending to work on this or can we wait until a future release?

**Comment by s-urbaniak** [comment]
sure thing! I'll take over the learnings from the glide transition in rkt and prepare a PR today. I guess we'll treat image-spec as a "cli" go project only not expecting others to vendor this?

**Comment by philips** [comment]
@s-urbaniak correct, we won't expect vendoring of the image-tool
