### ISSUE TITLE
Which SHA256 value can represent this image only？

### ISSUE THREAD

**Issue by 1412904892** [opencontainers/image-spec#769]
If I want to get a sha256 value for a Image, do I recalculate it or can I get it from an existing file?

**Comment by cyphar** [comment]
What do you mean by "image" in this context? Are you talking about an OCI layout, or the individual `ImageManifest` for a particular image?

**Comment by 1412904892** [comment]
> What do you mean by "image" in this context? Are you talking about an OCI layout, or the individual `ImageManifest` for a particular image?


The individual Image Manifest for a particular image

**Comment by 1412904892** [comment]
> > What do you mean by "image" in this context? Are you talking about an OCI layout, or the individual `ImageManifest` for a particular image?
> 
> The individual Image Manifest for a particular image

For Example，the images like Ubuntu，I pull it from docker hub , and there are many sha256 ,but I don't know which one can represent this image only.

**Comment by cyphar** [comment]
The `sha256` of the image manifest is in `index.json` -- it's the top-level manifest. This is a hash of the JSON for the image manifest, but because it contains the sha256 hashes of all the layers (and the config) this hash is enough to represent the entire image.

**Comment by 1412904892** [comment]
> The `sha256` of the image manifest is in `index.json` -- it's the top-level manifest. This is a hash of the JSON for the image manifest, but because it contains the sha256 hashes of all the layers (and the config) this hash is enough to represent the entire image.

Thanks
