### ISSUE TITLE
Spec out image directory layout

### ISSUE THREAD

**Issue by s-urbaniak** [opencontainers/image-spec#77]
The oci-image-tool image unpacker will rely on a in-flux discussion starting from https://github.com/opencontainers/image-spec/issues/23#issuecomment-212636147. The proposed layout should be spec'ed out in markdown format and be part of this specification.

xref https://github.com/opencontainers/image-spec/issues/75

**Comment by s-urbaniak** [comment]
ignore this, jet lag plays tricks with me, #23 actually addresses this.

**Comment by stevvooe** [comment]
@s-urbaniak I was trying to cover this in #38, actually, albeit #23 has discussion around this topic.
