### ISSUE TITLE
Clarify image index usage with same-platform manifests

### ISSUE THREAD

**Issue by hendrikhalkow** [opencontainers/image-spec#776]
I think the image index needs a bit more clarification on how an image is intended to be processed by a runtime spec when there are multiple manifests within one image. While it is clear what is meant when there is exactly one manifest within an image or two manifests for different platform or architectures within an image, it is unclear when there are manifests for the same platform and architecture within an image. As of now, it is not forbidden.

Is it intended that there is no restriction of having multiple manifests for the same architecture and platform within an image?

Or, is it up to the runtime-spec implementation on how to handle situations like this, e.g. by adding some annotation-based selector like

`podman run --select org.opencontainers.image.ref.name=myref myimage:latest`

or a sub-image dressing scheme like `podman run myimage:latest/myref` ?

Even if this is intentional, there should be a few more sentences in the [image index spec](https://github.com/opencontainers/image-spec/blob/master/image-index.md) on how to handle this.

**Comment by jonjohnsonjr** [comment]
There is a lot of discussion in https://github.com/opencontainers/image-spec/issues/581 that is relevant. It's a long one, but I believe the general consensus is that it's up to the implementation to decide if it should return an error or just pick an arbitrary entry in the face of ambiguity, e.g. [this algorithm](https://github.com/opencontainers/image-spec/issues/581#issuecomment-304668722) "looks about right".
