### ISSUE TITLE
image index cycles

### ISSUE THREAD

**Issue by glyn** [opencontainers/image-spec#778]
The spec is silent about whether cyclic collections of image indexes are permitted and what implementations should do when they encounter cycles. For instance, implementations could detect cycles and raise errors if cycles are not permitted. Alternatively, implementations could ignore cycles or issue warnings.

**Comment by cyphar** [comment]
Assuming sha256 is a secure hash function it should be impossible for you to form a cycle -- all the pointers require a hash of the target object and so you would need to have an object which contains (in a way) its own sha256 hash.

**Comment by glyn** [comment]
Good point. Let's assume SHA-256. Closing.
