### ISSUE TITLE
Size limit for Index's Array of Manifests

### ISSUE THREAD

**Issue by jzelinskie** [opencontainers/image-spec#781]
Similar to #780, there should be a fundamental limit for the manifests in an Index.

**Comment by SteveLasker** [comment]
Same comment on #780: should this be in the spec, or up to each registry operator to specify?

**Comment by vrothberg** [comment]
Could it be generalized further to also limit the size of manifests and configs (i.e., blobs of unknown sizes)?

We've seen situations/attacks where a registry would continue streaming a manifest/config trying to bring down the client in hope they're writing to memory.

> should this be in the spec, or up to each registry operator to specify?

I prefer the spec as this would simplify the lives of container engines (Podman, Docker, etc.) which practically already need to set some limits to protect from being DOSed.

**Comment by cyphar** [comment]
> We've seen situations/attacks where a registry would continue streaming a manifest/config trying to bring down the client in hope they're writing to memory.

That shouldn't be a problem -- descriptors have the size of the blob embedded in them. If the source you're getting blobs from is streaming more bytes than that, just kill the connection and fail. That's the entire reason they're in the spec. And you can add an artificial limit to blob sizes in your client if that's what you need.

**Comment by josephschorr** [comment]
@cyphar True, but on the flip side blobs are uploaded before the manifests and descriptors are pushed. Quay has its own defined limits on blob sizes (configurable for our end users), but it does show we've already had to put some reasonable limits into place.

**Comment by SteveLas** [comment]
As I think this is all based on the same discussion as #780, can I suggest we track the discussion there, until we think there's a difference between the two?
It's good to have two issues for final closure.

**Comment by sudo-bmitch** [comment]
distribution-spec has included a recommended 4MB limit:

> Client and registry implementations SHOULD expect to be able to support manifest pushes of at least 4 megabytes.

https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-manifests

Which means that registries and container engines are free to reject manifests exceeding this limit and image producers should avoid exceeding this size limit.

Is a separate limit definition needed for image-spec, or are we comfortable deferring to distribution-spec for this?

**Comment by tianon** [comment]
IMO deferring to distribution-spec is sane (just to echo my comment from https://github.com/opencontainers/distribution-spec/pull/293#issuecomment-1452780554, that's 4M*i*B, or more specifically, 4194304 bytes).

**Comment by tianon** [comment]
Looking at this again during the meeting today, and any use case we can think of for limits here is grounded more in the distribution use case than what's described by the image spec alone, so I'm going to close this in favor of (slash "via") https://github.com/opencontainers/distribution-spec/pull/293.  If you've got a compelling use case for why the image specification alone should _also_ include limits (which then gets even more confusing for consumers to have to dance around multiple limits from separate specs), please feel free to raise it. :+1:
