### ISSUE TITLE
add application/vnd.oci.image.layer.v1.tar+zstd to official media type?

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/image-spec#787]
https://github.com/containers/image/pull/639#issuecomment-505473848

@vbatts @giuseppe

**Comment by vrothberg** [comment]
:+1: from my side

FYI @mtrmac @mrunalp @rhatdan

**Comment by rhatdan** [comment]
:+1:

**Comment by cyphar** [comment]
Sounds like a good idea to me, the main question is whether we should require support or define it as a `SHOULD` (such that we define `+zstd` to mean something specific without requiring everyone implement support).

Though, given there is a C library (used fairly widely now) and implementations for Go and Rust, I'd be willing to argue that implementing support shouldn't be an onerous requirement for image consumers.

Does anyone want to volunteer to do the PR, or should I?

**Comment by vbatts** [comment]
I would welcome a PR on this. The language for this kind of extensibility
ought to allow for future permutations as well, even if it calls out
explicitly `+zstd` for now.

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/opencontainers/image-spec/pull/788
