### ISSUE TITLE
Add Index Support for Artifact Type

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/image-spec#806]
See: [OCI Artifacts issue 25](https://github.com/opencontainers/artifacts/issues/25)

**Comment by sudo-bmitch** [comment]
Can this be closed?

**Comment by SteveLasker** [comment]
I was on the fence for a while as I was hopeful https://github.com/opencontainers/artifacts/pull/37 would be the "one manifest to rule them all".
With the latest conversations, you've helped with on identifying loops, I think we've come to the conclusion that we need two types of manifests
- An "artifact" manifest that represents a single thing (container image, signature, sbom, scan result, helm chart)
- A list of artifacts, that pivots across platform, or other pivots. For instance, a CNAB can't be represented as a single thing as it's an aggregate of several images.

If you have an artifact type that is a collection of manifests (CNAB, possibly helm), we'd still need an index replacement. 

So, at this point, I'd say we should keep this open and see where the result of the wg-reference types to see when we're ready to take on this problem space.

**Comment by sudo-bmitch** [comment]
Resolved by #1066.
