### ISSUE TITLE
schema: define "negative" schema examples

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#83]
We have several examples of well-formed JSON objects that pass schema validation, but no examples that fail. We need several for the following reason:

1. Ensure that schema validation is actually working.
2. Clarify aspects of the specification.

Ideally, these could be part of the specification and marked as bad, in congruence with the approach of having the examples validated.

Please see https://github.com/opencontainers/image-spec/pull/81#discussion_r64127544.

cc @s-urbaniak

**Comment by vbatts** [comment]
+1 though it could mean some churn until a 1.0

**Comment by stevvooe** [comment]
We can avoid making a bunch of these till before 1.0. For now, we just need to make the schema validation is operating correctly.

**Comment by wking** [comment]
On Mon, May 23, 2016 at 02:18:50PM -0700, Stephen Day wrote:
> For now, we just need to make the schema validation is operating
> correctly.

That's probably just “test any *approach* that someone questions”, and
not “test all instances of all approaches”.  So @stevvooe wonders
about $ref between files, and we give that one test case.  I expect
that will be light enough to be feasible even with pre-1.0 churn.

**Comment by wking** [comment]
And it would also help avoid sinking too much time into broken
approaches ;).

**Comment by philips** [comment]
Unless someone volunteers earlier I am making this a post-v1.0.0 milestone.

**Comment by stevvooe** [comment]
@philips We can't release a 1.0 without ensuring validation is correct.

**Comment by philips** [comment]
@stevvooe OK, are you volunteering to do that work?

**Comment by stevvooe** [comment]
@philips Looking into a fix but here is what I found:

1. Type validation seems to work. For example, if you change an int to a string, it is caught.
2. The regular expression validation seems to be broken. For example, the following passes, when there are not accepted characters:

  ```diff
diff --git a/manifest.md b/manifest.md
index 0b81f1d..1660f12 100644
--- a/manifest.md
+++ b/manifest.md
@@ -104,7 +104,7 @@ A client will distinguish a manifest list from an image manifest based on the Co
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
       "size": 7143,
-      "digest": "sha256:e692418e4cbaf90ca69d05a66403747baa33ee08806650b51fab815ad7fc331f",
+      "digest": "----sha256:e69241---8e4cbaf90ca69d05a66403747baa33ee08806650b51fab815ad7fc331f",
       "platform": {
         "architecture": "ppc64le",
         "os": "linux
```

We may be able to go live with a 1.0 in this condition, but there could be issues.

**Comment by vbatts** [comment]
Those can be tricky. When I was doing the schema for runtime-spec, I had to constantly test passing and failing cases for each field. But that was all by hand.
