### ISSUE TITLE
`make test` broken on master

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#84]
https://travis-ci.org/opencontainers/image-spec/builds/132403826

0aafcefaae646c29d3e0fe9b570962d2329b43ae

**Comment by s-urbaniak** [comment]
wat, I cannot reproduce this here, also it wasn't present on the PR, do you mind rebuilding?
@stevvooe any idea?

**Comment by vbatts** [comment]
I was able to reproduce on master, on my desktop

**Comment by s-urbaniak** [comment]
ok, I am able to reproduce it locally with a fresh GOPATH. so apparently blackfriday changed upstream, time to do vendoring.

I'll dig into it.

**Comment by s-urbaniak** [comment]
correction: it was transiently introduced by https://github.com/pkg/errors/pull/27

**Comment by stevvooe** [comment]
Wow. An error value that cannot be compared... what a minefield.

Filed pkg/errors#29.

**Comment by s-urbaniak** [comment]
ok, pkg/errors is fixed upstream, that was quick :-) "Works on my machine" with a fresh gopath.

**Comment by stevvooe** [comment]
@s-urbaniak Great! Kicking off a new build. Hopefully it works.

Do we close this and open a vendoring issue? I'd rather not go to vendoring quite yet...

**Comment by stevvooe** [comment]
Build recovered. Closing.
