### ISSUE TITLE
Documentation Question on Whiteout vs OpaqueWhiteout

### ISSUE THREAD

**Issue by AJRepo** [opencontainers/image-spec#840]
Something doesn't make sense to me in the  documentation regarding Whiteouts and Opaque Whiteout as written in  [layer.md](https://github.com/opencontainers/image-spec/blob/master/layer.md#image-layer-filesystem-changeset) 

The documentation states  for a "Whiteout"  states 

----BEGIN QUOTE--------------

> A whiteout filename consists of the prefix .wh. plus the basename of the path to be deleted.
> 
> The following is a base layer with several resources:
> 
> ```
>  a/
>  a/b/
>  a/b/c/
>  a/b/c/bar
> 
> ``` 
> 
> When the next layer is created, the original a/b directory is deleted and recreated with a/b/c/foo:
> 
> ```
>  a/
>  a/.wh..wh..opq
>  a/b/
>  a/b/c/
>  a/b/c/foo
> 
> ``` 

----END  QUOTE--------------

But that makes no sense and conflicts with the examples given later in that same documentation page using /bin/tools for OpaqueWhiteout. This seems to indicate to me that perhaps the documentation is meant to be written as 

-----BEGIN SHOULD DOCUMENTATION BE THIS? --------------------
The following is a base layer with several resources:

```
 a/
 a/b/
 a/b/c/
 a/b/c/bar

``` 

When the next layer is created, the original `a/b` directory is deleted and recreated with `a/.wh.b`

```
 a/
 a/.wh..wh..opq
 a/.wh.b/
 a/.wh.b/c/
 a/.wh.b/c/bar

``` 
whereas for an opaque whiteout one would continue that .wh.resource_name replacement for all subsequent files and directories. 

----END  SHOULD DOCUMENTATION BE THIS? ------------

Or is there something else I'm missing?

**Comment by cyphar** [comment]
No the documentation as-written is correct. `.wh..wh..opq` has a different meaning to regular `.wh.` files. An opaque whiteout indicates that you need to remove all of the old contents of the directory before adding the contents of the current layer. Think of it as an implicit `rm -rf` of that directory before you apply the directory contents in the layer.

**Comment by AJRepo** [comment]
I see, so  a/.wh..wh..opq just indicates that everything under a/ has been deleted.

**Comment by cyphar** [comment]
Yup, that's correct.

**Comment by AJRepo** [comment]
Yes - it wasn't clear to me. Closing.
