### ISSUE TITLE
Switch from travis to Github Actions

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#847]
Let's migrate off of travis for checking the docs and lint. :cat:

**Comment by vsoch** [comment]
I can take a first shot at this! I'll open a PR a little after 5pm today - I might need a few tries to get the action working, but it looks pretty straight forward.

**Comment by vbatts** [comment]
Oh nice

**Comment by vsoch** [comment]
https://github.com/opencontainers/image-spec/pull/848

**Comment by imjasonh** [comment]
Was this fixed by https://github.com/opencontainers/image-spec/pull/848? Is there anything else that needs to be done?

**Comment by vsoch** [comment]
If there is, I can offer to help again. I can't make the meeting now but please ping me here (and on any other issues!)
