### ISSUE TITLE
A reliable way to detect a docker image which doesn't have  an OS-file system (package manager)

### ISSUE THREAD

**Issue by tanvi0692** [opencontainers/image-spec#861]
Currently the best way I could find to detect the existence of a linux OS is by look for a  "release" or a "version" file in the /etc/*release or /etc/*version path. But this is not the most reliable way to detect. 

Would really appreciate any help in figuring out a way to detect a existence of a OS File system in a docker image without running it on a container.

**Comment by imjasonh** [comment]
You'll have to look for that filepath in each layer's tarball, taking care to handle whiteout files in case a higher-up layer deleted the file present in a lower-down layer.

There are probably a few tools that bundle this layer-aware extracting logic, my favorite is `crane` which exposes this as a [CLI](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_export.md) and [Go package](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/crane#Export), and can even be called like so:

```
$ crane export ubuntu - | tar -Oxf - usr/lib/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
...
```

(from [recipes](https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#extract-a-single-file-from-an-image))

nb: `crane export` doesn't follow symlinks, which `/etc/os-release` is on Ubuntu.

**Comment by jonboulle** [comment]
As Jason describes you'll need to walk through a view of the image's "rendered" filesystem to figure this out - there's nothing more direct in the image-spec per se to help with this I'm afraid.

I'm going to close this out but if you think there's something that should be addressed in the spec itself feel free to reopen and add some more detail of what you'd propose.
