### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by cardil** [opencontainers/image-spec#895]
Is the support for other languages planned? Or, if someone provides it, it may change to be merged?

I'm interested in particular on Rust implementation. As a minimum for cross-language support, some external standard could be provided - like for ex.: [OpenAPI](https://swagger.io/specification/). I think such an artifact could easily be computed (see: [openapi-go](https://github.com/swaggest/openapi-go)) and attached to the releases page. That would allow building upon this spec, in other languages.

**Comment by cardil** [comment]
Scratch this issue, in favor of https://github.com/containers/oci-spec-rs

**Comment by vbatts** [comment]
good call out. I've opened #896 to reference it
