### ISSUE TITLE
can `skopeo inspect` output the images size?

### ISSUE THREAD

**Issue by tanguofu** [opencontainers/image-spec#904]
when docker inspect will print the images size:
```
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 584177382,
        "VirtualSize": 584177382,
````
can `skopeo inspect` output the images size, and the  `skopeo inspect`  --raw only print each layersize

**Comment by cyphar** [comment]
This is the wrong place to request this feature. This is the repository for the OCI image specification. Please resubmit your issue [here](https://github.com/containers/skopeo).
