### ISSUE TITLE
Minimum criteria for new maintainers?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/image-spec#912]
Is there any minimum criteria/qualifications for a new maintainer to be added to this project?

For example:

- number of community calls attended
- involvement in mailing list
- involvement in WG efforts
- number of commits
- comment history

?

**Comment by sudo-bmitch** [comment]
For myself, I held off saying I'd be interested in being a maintainer until I had gone through the process of submitting a PR since I feel that helps understand the project and the other side of what maintainers do. That's my personal criteria, and I think exceptions make sense, particularly for anyone that participates in PRs without authoring the commit.

I do think it would be useful for OCI to consider the various roles in the spec and try to seek out maintainers to represent those roles. E.g. major SaaS provider, self hosted vendor, runtime author, and other client tooling each come to mind.

**Comment by jdolitsky** [comment]
cc @rnjudge who had some previous thoughts/questions here

**Comment by rnjudge** [comment]
Thanks for the tag @jdolitsky! My two cents:

At a minimum:
- Participation in the weekly community meetings
- Involvement in mailing list when applicable (hard to quantify this)
- Involvement in WG efforts (also hard to quantify this beyond showing up to general meetings)

I'm not sure you want to quantify a specific number of commits or comments. There's not really a lot of commits going into this project all the time so if someone wanted to be a new maintainer it might be hard to get them onboard with a minimum number of commits required. I agree that they should at least have opened or co-authored a PR though. At least one seems reasonable. It also seems reasonable to expect that maintainers are reviewing PRs and providing feedback for issues.

I would also consider how many maintainers from each company there is. Typically you want a fairly even representation among companies. Assigning a number to this depends on how many maintainers there will be. Is there going to be a set number or is is it just however many fit the criteria? Other things to consider: are new maintainers nominated by existing maintainers or can someone self-nominate?

**Comment by AkihiroSuda** [comment]
> At a minimum:
> - Participation in the weekly community meetings

Sounds exclusive to timezone minorities 😞

**Comment by jdolitsky** [comment]
I've added this to the call agenda for this week. Will be sure to keep in mind the timezone issue @AkihiroSuda

**Comment by jdolitsky** [comment]
Consensus on todays call appeared to be:

- No one criteria qualifies/disqualifies a potential maintainer
- Only requirement is nomination must come from an existing OCI maintainer (any repo)
- Create a PR template for this where the nominator can fill out the individuals track record cc @nishakm 
  - add sections for various criteria such as what @rnjudge provided
  - no requirement for attending calls (timezone issue), but it can still be included in the PR @AkihiroSuda 
  - using https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository (thanks @flavianmissi)
- The existing maintainers should "feel good" about adding this person, based on recommendation, criteria, and personal experience working with them
