### ISSUE TITLE
RFC 2119 broken link 

### ISSUE THREAD

**Issue by ralphie79** [opencontainers/image-spec#913]
[Specification page](https://github.com/opencontainers/image-spec/blob/main/spec.md) contains [broken link for RFC 2119](http://tools.ietf.org/html/rfc2119); it should be [https://datatracker.ietf.org/doc/html/rfc2119](https://datatracker.ietf.org/doc/html/rfc2119) instead

**Comment by vbatts** [comment]
Might you open a PR for this?

**Comment by sudo-bmitch** [comment]
@vbatts Isn't this already resolved? The link to RFC 2119 works for me now.
