### ISSUE TITLE
Go 1.16 CI is failing

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/image-spec#916]
Even in PRs not modifying Go source, fails with:
```
Error: ../../../../pkg/mod/honnef.co/go/tools@v0.3.1/go/ir/builder.go:36:2: //go:build comment without // +build comment
Error: make: *** [Makefile:111: .install.lint] Error 1
Error: Process completed with exit code 2.
```

**Comment by sudo-bmitch** [comment]
Looks like `go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest` is no longer working with Go 1.16, and I suspect they won't fix that now that 1.18 is out. So our choice is to either cut support for 1.16, or pin to an older version of the linter. I opted for the latter.
