### ISSUE TITLE
New digest algorithms: `sha256+gunzip`, `sha256+unzstd`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/image-spec#925]
https://github.com/opencontainers/image-spec/blob/v1.0.2/descriptor.md#registered-algorithms

I suggest adding new algorithms `sha256+gunzip` and `sha256+unzstd`.
These algorithms compute the digest after uncompressing the blob.
The digests are stable regardless to the parameters of the compression algorithm (e.g., deflate block size) and should be useful for reproducible image building.

**Comment by jonjohnsonjr** [comment]
X-ref: https://github.com/opencontainers/distribution-spec/issues/235

IMO we should not add this as a new digest algorithm, but have manifests reference the uncompressed content and leave compression as an implementation detail of transport/storage.
