### ISSUE TITLE
Reference Types Working Group remaining tasks

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/image-spec#940]
We agreed to merge #934 with the following outstanding tasks:

- [x] Update image-spec spec.md definitions to match distribution-spec
- [x] refers naming
- [ ] MUST language
- [ ] potentially other restrictions / allowances for the use of the new fields (@mikebrow)

**Comment by nishakm** [comment]
"refers" alternatives below:

|Image|Distribution|
|--------|---------------|
|affects|affectors|
|connects|connectors|
|qualifies|qualifiers|

**Comment by vsoch** [comment]
I can't edit, so my vote is for the last one:

- relates_to and relationships

It's not the nicest looking one (the underscore!), but I think for the image it's the most obvious term to indicate a relationship (akin to how you'd see when working with graphs "this thing relates to...") and then relationships are also what graph/ontology communities use. This makes me think that having the others as "has X" would actually make them fit that criteria too.  "Attribute" is confusing with a kind of feature/descriptor, and qualifies suggests there is some criteria that one thing has that "qualifies" or validates the other. Affects makes me think of seasons, touching, it's just not the right word. So then my second and third choices would be refers and referrers, slight preference over connects/connectors which sounds like it's describing lego pieces.

**Comment by estesp** [comment]
Given most people in this community are not necessarily members of the image-spec repo, maybe it makes more sense to not require edit, but pick 6 of the more "positive" looking response emojis and assign them to the rows of your table @nishakm? That way people can just click an emoji response to vote, and it's easier to see totals anyway and who voted. Then we just have to make sure that whatever :heart: is is what @sudo-bmitch actually wants to vote for 😂

**Comment by vsoch** [comment]
I think discussions might have support for polls? https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/

**Comment by afflom** [comment]
A key named "attribute(s)" that contains an oci descriptor doesn't make much sense to me. I'm not sure if I get a vote, but "referrer" or "relates_to" are the only ones that form coherence about what that object might contain in my mind. 

If I do get a vote, then I agree with @vsoch's comment and vote for relates_to/relationships

**Comment by nishakm** [comment]
😅 Sorry everyone. Just comment here on which ones you like and I will count the thumbs up from others.

**Comment by nishakm** [comment]
@afflom you can totally vote!

**Comment by vsoch** [comment]
@nishakm could we AT` the usernames next to the voting grid so it's easier to count / see who voted?

**Comment by vsoch** [comment]
Thank you that is super helpful! So I’d only like to vote for one, my first choice “relates to and relationships” please! Otherwise I’m watering down my top vote.

**Comment by vsoch** [comment]
Perfecto thank you @nishakm ! And sorry for the multiple pokes, if you ever need some random help on something I will make time!

**Comment by Jamstah** [comment]
refers / referrers is fine for me

relates_to / relationships is good too

I don't like any of the others! Too many assumptions in them.

**Comment by mikebrow** [comment]
other...   @lachie83 's `subject` mention in slack drawing from proposal A... seems to me to make it very clear.  Otherwise refers is fine let the documentation explain that it's the subject reference of the artifact.

**Comment by lachie83** [comment]
@nishakm can you please add the following with my vote to the table in your comment above - https://github.com/opencontainers/image-spec/issues/940#issuecomment-1234578277

Image | Distribution | Votes
-- | -- | --
subject | referrers | @lachie83

**Comment by sudo-bmitch** [comment]
Doh, apparently I forgot to submit my comment. My vote is for refers/referrers. I'm not a huge fan of the wording, but the longer we go, the more code gets written with those. I'm not a fan of an underscore in the field, but we could also do camel case if that were to get picked.

Other ideas to consider (but I'm not voting for):

- extends/extenders (similar issue to attributes since we have extensions)
- parent/children (denotes directionality, but not much else)
- associate/associates (might be even harder to type/say than referrers)

**Comment by michaelb990** [comment]
I'd also vote for `subject`/`refers` & `referrers`. (Same votes as the other MB 👍 )

**Comment by Jamstah** [comment]
Actually, I like subject / referrers and would change my vote(s) to just that one. Subject is more clear I think.

**Comment by btklein** [comment]
`Refers` / `Referrers` 👍

**Comment by sajayantony** [comment]
@nishakm can you help update the table with the other votes - 
There are more folks who are voting for `subject`/`referrers`  including me. 
I know we discussed this in the call but it looks like folks started chiming in after the call.

**Comment by mikebrow** [comment]
FYI my preference is 1 subject, referrers; 2 refers, referrers

**Comment by nishakm** [comment]
I've removed duplicate votes since more have come out. Seems like `subject/referrers` has won out. Any disputes on the vote?

**Comment by bainsy88** [comment]
Bit late to the party but having caught up on the specs etc this week I struggled a bit with refers/referrers so was glad to see this issue. 

subject/referrers works best for me
