### ISSUE TITLE
Enable security reports

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/image-spec#974]
Should image-spec enable the security reports feature recently launched by GitHub? I'm leaning towards yes, but wanted to get some buy in before clicking the button.

https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by sudo-bmitch** [comment]
@opencontainers/image-spec-maintainers I plan to turn this on today, and it can be disabled if we later discover an issue.

**Comment by sajayantony** [comment]
SGTM.

**Comment by sudo-bmitch** [comment]
This has been enabled.
