### ISSUE TITLE
Link inside Annotations spec is kind of broken

### ISSUE THREAD

**Issue by mobilutz** [opencontainers/image-spec#978]
I mean specifically the link with name `Label Schema` which links to https://label-schema.org/ on this page: https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema

Why is it broken:
1. no valid certificate
2. underlying github repo is archived: https://github.com/label-schema/label-schema.org

**Comment by sudo-bmitch** [comment]
Is there another link we should be using? The document is describing compatibility with label-schema, and label-schema stopped development in favor of the OCI annotations, so it makes sense that we would keep the translation table. We don't own the label-schema project so it's better to reach out to those maintainers to see if they know about the certificate.

**Comment by vbatts** [comment]
well, that's junky. I think the folks that had created label-schema had wished OCI to wholly included their definitions. But I haven't heard overwhelming feedback that folks are using the label-schema. :frowning_face:
