### ISSUE TITLE
Alignment/Consolidation of Predefined Annotations to Support Artifact Types

### ISSUE THREAD

**Issue by sabre1041** [opencontainers/image-spec#980]
Currently, there is guidance on the set of [predefined annotation keys](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) that can be placed upon the different types. However, with the addition of [artifact](https://github.com/opencontainers/image-spec/blob/main/artifact.md) type, there are only two annotations that are explicitly documented. 

* `org.opencontainers.artifact.created`
* `org.opencontainers.artifact.description`

The majority of the annotations prefixes which are currently documented using the `org.opencontainers.image.*` would also apply to artifacts in addition to the two that were previously documented. 

Updated guidance and documentation is needed if indeed these same keys also apply to artifact types.

**Comment by imjasonh** [comment]
> This specification defines the following annotation keys, intended for but not limited to [image index](https://github.com/opencontainers/image-spec/blob/main/image-index.md), image [manifest](https://github.com/opencontainers/image-spec/blob/main/manifest.md), [artifact](https://github.com/opencontainers/image-spec/blob/main/artifact.md), and [descriptor](https://github.com/opencontainers/image-spec/blob/main/descriptor.md) authors.

I interpret this to mean that all the annotations can be used for images, artifacts, indexes, and descriptors. It's a bit of an unfortunate misnomer, but I think we should interpret the spec to mean that, e.g., `org.opencontainers.image.documentation` is still usable by an artifact manifest.

If there's wording you think could help make this clearer, feel free to propose some here or send a PR.

**Comment by sudo-bmitch** [comment]
I had briefly considered duplicating the annotations for artifacts, but that felt worse than using the image annotations for artifacts. It's more work for consumers to search multiple names and handle conflicts if both are defined. So I agree with @imjasonh that using the image annotations for artifacts is a valid use.

**Comment by sabre1041** [comment]
@sudo-bmitch @imjasonh Perfect, and it aligns with my thoughts as well.

As for the documentation, propose that the annotations be modified to a form similar to `org.opencontainers.<type>.created` and defining the valid types explicitly (ie `image` and `artifact`). 

Thoughts?

**Comment by sajayantony** [comment]
Duplication of annotations also makes conversions harder. Don’t see any concern reusing the defined annotations for multiple manifest even though they are under .image.

**Comment by sajayantony** [comment]
@sabre1041 - Do we need additional verbiage now since the both manifests now have an `artifactType` and with #1078 avoids the duplicates. Basically trying to close out all issue in the v1.1 milestone. 

As per annotations.md 

---
 This specification defines the following annotation keys, intended for but not limited to [image index](https://github.com/opencontainers/image-spec/blob/main/image-index.md), image [manifest](https://github.com/opencontainers/image-spec/blob/main/manifest.md), and [descriptor](https://github.com/opencontainers/image-spec/blob/main/descriptor.md) authors.

**Comment by jdolitsky** [comment]
this may not make any sense after #999 ? should we close?

**Comment by tianon** [comment]
I agree; I would personally have used the existing annotations for artifacts too, and having consolidated artifacts under the image manifest makes that seem even more correct. 😅

**Comment by sabre1041** [comment]
Closing as artifact specific annotations have been removed, thus there is no longer any overlap to support consolidation
