### ISSUE TITLE
Looking for OCI guidance for `artifactType` and `mediaType`

### ISSUE THREAD

**Issue by toddysm** [opencontainers/image-spec#982]
I brought this up in one of the OCI community meetings, and I see it coming back again and again. I finally found time to put my thoughts on paper, and as I mentioned in the meeting, I am looking for guidance on how to use the `artifactType` and `mediaType` in implementations. Bare with me, it will be a long post because I would like to explain the scenarios I have in mind as well as the different options I am looking at for implementation.

Also, I went over the notes that @sudo-bmitch shared with me. These cover some of the scenarios but don't go into too many details and provide a lot of guidance.
[Standardizing artifact media types and annotations - allowing interoperability among clients (Nisha Kumar/Brandon Mitchell)](https://hackmd.io/nZzK_4AfRz-xgya6KkqseA#Standardizing-artifact-media-types-and-annotations---allowing-interoperability-among-clients-Nisha-KumarBrandon-Mitchell)

## How do I interpret the `artifactType` and the `mediaType`
Before I go into the scenario details, I would like to share how I interpret the `artifactType` and `mediaType`. I admit that I may be biased toward this interpretation. I will use SBOM as an example. For me (speaking as a user), `SBOM` is the `artifactType` (the President's EO does not specify *SPDX* or *CycloneDX*, it specifies *SBOM*), and the format in which the SBOM is saved is the `mediaType` (*SPDX* or *CycloneDX*). The EO guidance is to produce an *SBOM* and not an *SPDX* or *CycloneDX*. So, logically, the *type* is *SBOM*, and the format is *SPDX* or *CycloneDX*.

Now, at first sight, the *format* is SPDX or CycloneDX. Though, when you think about it, SPDX can be saved in JSON `application/spdx+json` or text format `text/spdx` (both [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) media types) or maybe XML `application/spdx+xml` (I don't think there is IANA media type for that).

I will come back to that later on in the explanations. 

## Scenario
First, the scenarios. I am considering generating content that will have a (logical) structure like this:

```
+ Container Image
    - Container Image Signature(s) (can be one or more)
    + SBOM(s) (can be one or more)
        - SBOM Signature (for each SBOM or combined if produced together - for example, SPDX and CycloneDX signatures as part of the build)
    + Vulnerability Report(s) (certainly more than one as scans are run at least daily)
        - Vulnerability Report Signature
    + Malware Scan Report(s) (same as the vulnerability reports)
        - Malware Scan Report Signature
    + Another Related Artifact(s) (again one or more; one thing we are thinking of is an image lifecycle annotation document with several annotations that can be updated during the lifecycle of the image - see https://github.com/opencontainers/image-spec/pull/903 for example)
        - Another Related Artifact Signature
```

With this structure, I would like to do several things. First and foremost, of course, is policy evaluation at a high scale. And not only signature verification but things like:
- License evaluation using the SBOMs (in audit mode)
- Vulnerability and malware evaluation using the reports (in audit mode)
- Preventing deployments if known packages are present or license violated (deny mode)
- Preventing deployments if known vulnerabilities are present (deny mode)
- Inventorizing images (maybe in external systems, but expectation is that the data from linked artifacts is indexed and presented as a graph. which I believe is also one of GUAC's goals)

Think of the above as launching 10 pods (being conservative here) that have several containers. For each one, you need to pull several artifacts, evaluate each one, and make a decision before the admission controller times out. Also, I don't need to pull every vulnerability report, just the latest one. The same is true for the malware report. In general, I do not expect to pull all the data down (this can also be a lot of data) before I can make the admission decision.

In addition to the above, I would like to develop also some human-facing functionalities. An example is showing those in Docker Hub or similar UI.

- List and logically group artifacts related to a container image
- Filter artifacts by logical type (SBOM, signature, vulnerability reports, etc.)
- Use different icons for artifact types (SBOMs, signatures, etc.)
- Use different icons for different media types (SPDX, CycloneDX, etc.)
- and so on...

## What are the implementation options?
Here are a few options to go with for the above, including their pros and cons.

### Separate blob for each type
I can generate something like this:

```
+ Container Image
    - Container Image Signature 1
    ...
    - Container Image Signature N
    + SPDX SBOM
        - SPDX SBOM Signature
    + CycloneDX SBOM
        - CycloneDX SBOM Signature
    + Vulnerability Report 1
        - Vulnerability Report 1 Signature
    ...
    + Vulnerability Report N
        - Vulnerability Report N Signature
    + Malware Scan Report 1
        - Malware Scan Report 1 Signature
    ...
    + Malware Scan Report 2
        - Malware Scan Report 2 Signature
    + Another Related Artifact 1
        - Another Related Artifact 1 Signature
    ...
    + Another Related Artifact N
        - Another Related Artifact N Signature
```

Let's assume that each of the above (except the image) will have a single blob. In this case, I may not need to even use the `artifactType` (except for the image) and model it as follows (example with SBOMs only):

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SPDX SBOM
      `mediaType: "application/spdx+json"`
    - SPDX CycloneDX
      `mediaType: "application/vnd.cyclonedx+json"
```

Circling back to my scenarios above, here is what I think.

#### Implementing generic clients
Implementing generic clients will be hard. For example, if I need to handle both SPDX and CycloneDX, I will need to make two calls to the registry - one for each format. If we consider that there may be other sub-formats like JSON, text, XML, etc., the number of calls that need to be made to the registry will grow. The same is true if we assume that other SBOM formats are considered, added, etc.

#### Performance issues
Related to the above, every call to the registry introduces latency and performance impact. Also, remember that those are calls for the manifests and not for the actual SBOM blobs. Once you know what format the SBOM is available, you can only request the blob.

Why is that important? Because I cannot assume that the publisher of the image is using one format or the other. Unless we say that one and only one format will be used for SBOMs, I cannot assume that I should query for `mediaType` in my admission controller and expect good performance.

Here is a simple math. For the two SBOMs formats: SPDX and CycloneDX, and the 3 subformats (I know that I am exaggerating here) JSON, text, and XML, one will need to do 6 calls to the registry + 1 additional call for the blob in the worst case. Yes, the best case is still 2 calls, but it is very deterministic, and relies on the assumption that I have the desired SBOM format attached to the image and I can handle only one format. Expectation is that you will need to do 3 calls on average - 2 calls for SPDX or CycloneDX and 1 call for the blob (assuming we all settle on JSON).

#### Visualization issues
Similar to the above, if I want to visualize the SBOMs, I will need to make multiple calls to the registry and query for all possible `mediaType`s to get all the data I need for visualization. Keep in mind that folks may want to search/filter in the UI and see only SPDX SBOMs, CycloneDX SBOMs, or only SPDX SBOMs in JSON format, or only CycloneDX SBOMs in XML.

#### Messy Architecture
If I am to develop a client, I will approach the problem as follows:
- Ask the registry for all SBOMs (SPDX and CycloneDX)
- If there aren't any, fail the admission
- If there are some, use a factory to evaluate the SBOM based on its `mediaType`
    - If my code cannot handle specific `mediaType` I can still fail

Assuming no "generic" SBOM type exists, this will be hard, and my code for pulling the SBOMs and evaluating them will need to be interdependent. Of course, this is an architectural choice - sometimes mixing the code may be acceptable.

#### Additional thoughts about this option
Note, though, that the SBOM is generated during build time. At that time, the publisher of the image can generate both SPDX and CycloneDX SBOMs (in various formats like JSON, text, and XML) at once and push them to the registry. So, the image and the SBOMs can be pushed to the registry as a single *"packet"*.

This is not the case with the vulnerability and malware scan reports, though. Those are generated on a daily basis, and every day you need to push a new report to the registry. For those, the 1:1 mapping between manifest and blob makes sense, and the above approach seems feasible.

Signatures are a mix of the above. Signatures for the image and SBOMs can be produced at build time and pushed together with the relevant artifacts. Signatures for vulnerability and malware reports need to be added every time a new report is generated.

### Multiple blobs per type
I mentioned some of the benefits of having multiple blobs per manifest above. In general, I believe that it is a waste of storage and computing resources to create a single manifest for a single blob. Here are a few options that I see the multiple blobs per manifest working. Which, of course, warrants the use of `artifactType` and the introduction of more generic `artifactType`s.

#### Combining artifacts at build time
When the image is built, the SBOMs and the signatures for the artifacts are generated. At the built time, I can produce the following content (SBOM example):

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX SBOM
          `mediaType: "application/spdx+json"`
        - SPDX CycloneDX
          `mediaType: "application/vnd.cyclonedx+json"
```

or

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX SBOM
          `mediaType: "application/spdx+json"`
        - SPDX SBOM
          `mediaType: "text/spdx"`
        - SPDX CycloneDX
          `mediaType: "application/vnd.cyclonedx+json"
```

or 

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX SBOM
          `mediaType: "application/spdx+json"`
```

All SBOM artifacts are described with a single manifest. As mentioned above, if I need to make a policy decision at admission, I can query for `application/sbom` and get all SBOMs for the image. Then, check the `mediaType`, and if I can handle the format, I can decide.

Also, in the UI, I can easily use the above manifest to show something like this:

```
Image
    [x] SPDX JSON SBOM
    [x] SPDX TEXT SBOM
    [x] CycloneSX JSON SBOM
```

Also, for compliance reasons, when I generate reports, I don't care about the format of the SBOM; I only care if an SBOM is attached to the image. (Yes, there is still the danger that somebody attaches a dummy text file and calls it SBOM but this is a separate issue :) )

*Note:* The above is the happy path scenario. In practice, I may have more than one SBOM artifact, as presented in the following structure:

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX SBOM
          `mediaType: "application/spdx+json"`
        - SPDX SBOM
          `mediaType: "text/spdx"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX CycloneDX
          `mediaType: "application/vnd.cyclonedx+json"
```

This still has the benefit, though, that I get all SBOMs with a single call to the registry.

#### Attaching signatures to artifacts
Another interesting use of `artifactType` is "attaching" the signature to the artifact. For instance, the vulnerability reports can be produced as follows:

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - Vulnerability Report
      `artifactType: "application/vulnerabilityReport"` (Note: there is no such IANA type)
        - Vulnerability Report
          `mediaType: "application/vnd.somevendor.report"` (Note: there is no such IANA type)
        - Signature
          `mediaType: "application/vnd.someothervendor.signature"` (Note: there is no such IANA type)
```

Using `mediaType` in the above structure will be pretty confusing because it is unclear how the client should handle the artifact if the artifact's media type is one. There are two blobs with different `mediaTypes` in them. It doesn't look as an ideal approach for me.

#### Additional thoughts about this option
Of course, the option to use multiple blobs per artifact has its disadvantages. At a minimum, there is no guarantee that we can achieve this from a tooling point of view. For example, not every tool can generate both SPDX and CycloneDX SBOM. This means that we will end up with a mixed structure, where you have more than one SBOM artifact attached to the image (similar to the vulnerability reports). 

In the scenario of "attached" signatures that I described above, if we have the following structure:

```
+ Container Image
  `artifactType: "application/vnd.docker.container.image.v1+json"`
    - SBOM
      `artifactType: "application/sbom"` (Note: there is no such IANA type)
        - SPDX SBOM
          `mediaType: "application/spdx+json"`
        - SPDX SBOM
          `mediaType: "text/spdx"`
        - SPDX CycloneDX
          `mediaType: "application/vnd.cyclonedx+json"
        - Signature
          `mediaType: "application/vnd.someothervendor.signature"` (Note: there is no such IANA type)
```

It won't be very clear how this signature is created. Is this the signature for a sum of all the SBOMs? It would make more sense to have the signature detached in this case (i.e. as a separate artifact linked to the SBOM artifact).

## Summary
To summarize, there are different approaches that one can take with `artifactType` usage. Above are just a few scenarios that I have off the top of my head - I am sure I miss many others. I believe using `artifactType` is beneficial and can provide optimizations and reduce the pollution of registries with unnecessary data. Though, without some guidance, different tools will take different approaches.

I will be curious to hear the OCI Community's opinion on the above scenarios and what tool vendors are thinking about the implementations they will provide.

**Comment by AaronFriel** [comment]
@toddysm thanks for raising this, I'm looking into how we could convey sboms of different types, and the distinction between `mediaType` and `artifactType` was very unclear. It wasn't obvious what IANA type I should ascribe to an artifact if it could have any arbitrary flavor of SBOM.

Signing the SBOM files themselves seems **sufficient**, but doing so means that verifying that the SBOM is intended for the root artifact is format-dependent and requires parsing and interpreting the SBOM. That's not great for automated tools, I would prefer _fewer_ parsers in the loop, not more.

So I would imagine it'd be better to sign the artifact manifest that contains the SBOM blob digests and the subject linking it to the root artifact.

However, if I've done something like `oras pull` and all I have is `sbom.spdx.json` and `sbom-manifest.json.sig`, I can't verify the former with the latter.

Seems like we'd want to be able to do both: verify the manifest linking the SBOMs to the root artifact, and be able to verify the SBOM files individually.

**Comment by sudo-bmitch** [comment]
I would avoid lumping all types of SBOMs into a single artifact with lots of layers. Since these SBOMs may be created by separate tools, we would end up with the following issues:

- Race conditions with multiple tools trying to update the same artifact, overwriting changes from another generator.
- Possible data loss where one tool adds unrecognized fields that are lost when another tool updates the artifact.
- End users that only want a single type of SBOM are forced to pull all SBOMs to their mirror to avoid breaking the digest of the artifact.
- Signing of the artifact manifest would sign all SBOMs even if the signer has only verified a single SBOM.

The better use case for me is if every SBOM generation tool uses its own artifactType and blob mediaType, and pushes multiple artifacts if it pushes different formats (json, xml, etc). The artifactType and annotations should be unique enough that end users can pick which SBOM they wish to use.

While this does mean that users need to permit a list of allowed `artifactTypes` if they don't care about the SBOM, I think it's equally important to not include unknown SBOMs that cannot be verified. Otherwise I can create something that says:

```jsonc
mediaType: "application/vnd.oci.artifact.manifest.v1+json",
artifactType: "application/sbom",
blobs: [
  {
    mediaType: "application/text",
    descriptor: "sha256:ea706edf61ef640bcdf3c9ac9045c28446e6b2d08541b9ad614c7267d0b87375",
    size: 19
  }
]
```

where the descriptor points to a blob with the contents `contains electrons`. There's no client to parse the file, no way to programmatically verify it, and I don't think it's in the spirit of checking the compliance box.

I'm not concerned with multiple manifest pulls for each type of artifact, because manifests are small, and they can be pulled concurrently. By having the artifacts separate, the end consumer can pick which artifacts they copy when they mirror images from an upstream supplier, maintain the same digest to simplify future mirroring steps, and still have valid signatures attached to those artifact manifests.

**Comment by AaronFriel** [comment]
@sudo-bmitch it seems then you'd suggest that artifactType == mediaType in this case?

I must admit to still being confused *when* I would set those two differently.

**Comment by sudo-bmitch** [comment]
> @sudo-bmitch it seems then you'd suggest that artifactType == mediaType in this case?
> 
> I must admit to still being confused *when* I would set those two differently.

@AaronFriel I've seen discussions from the notary developers that they want to support multiple signature types. In that case, the artifactType would indicate it is notary, and the blob mediaType would indicate it's cose or jwt.

The artifactType is expected to be used as a filter for clients so they can query for artifacts they create/read, and the blob mediaType is one type of data it can handle. Flattening all of the types of data into a single object to be handled by any client feels like a mistake to me.

**Comment by toddysm** [comment]
@sudo-bmitch, I totally agree with your arguments about race conditions, data loss, etc. Hence all those questions for clarity. 

Regarding your comment, though:
> it's equally important to not include unknown SBOMs that cannot be verified.

What prevents me to do the following:
```
mediaType: "application/vnd.oci.artifact.manifest.v1+json",
artifactType: "application/spdx+json",
blobs: [
  {
    mediaType: "application/spdx+json",
    descriptor: "sha256:ea706edf61ef640bcdf3c9ac9045c28446e6b2d08541b9ad614c7267d0b87375",
    size: 19
  }
]
```
and just have some random text in the blob? Setting the `artifactType` and the `mediaType` to any value doesn't guarantee that the content is conformant to the spec for that value. In the above scenario, if I don't parse the content I can still end up with false assumption for compliance. I am looking from point of view how can I break this (intentionally or unintentionally).

One more specific question. Using the signature example above, if my client needs to handle three different signatures: cosign, notary jws, and notary cose, what is the expectation for the manifests and their respective `artifactType` and `mediaType` values? My preference would be to pull anything that has one of the three above and check if it is in my trust policy to trust it. Isn't this the equivalent of trusting a signature signed with a blue pen and signature signed with a red pen? The pen color is irrelevant. What is relevant is whether I trust the signature.

@AaronFriel regarding:
> It wasn't obvious what IANA type I should ascribe to an artifact if it could have any arbitrary flavor of SBOM.
Agree, exactly the question I have! It does seem to me that I need to always be aware of the flavor even when querying the registry to retrieve the information.

**Comment by toddysm** [comment]
@sudo-bmitch Sorry, one more thing re
> I'm not concerned with multiple manifest pulls for each type of artifact, because manifests are small, and they can be pulled concurrently.

I actually am concerned about that because registries have throttling. As pointed out above, now instead of making a single call for the image manifests, I need to make three more calls for the SBOMs and three more calls for the signatures for the image only and three more calls for the signatures of the SBOMs. We are increasing the API load nine times. And this is only for those two artifacts. Hope my math makes sense.

**Comment by toddysm** [comment]
@sudo-bmitch Sorry, one more thing re
> I'm not concerned with multiple manifest pulls for each type of artifact, because manifests are small, and they can be pulled concurrently.

I actually am concerned about that because registries have throttling. As pointed out above, now instead of making a single call for the image manifests, I need to make three more calls for the SBOMs and three more calls for the signatures for the image only and three more calls for the signatures of the SBOMs. We are increasing the API load six times. And this is only for those two artifacts.

**Comment by sudo-bmitch** [comment]
> Regarding your comment, though:
> > it's equally important to not include unknown SBOMs that cannot be verified.
> 
> What prevents me to do the following:
> ```
> mediaType: "application/vnd.oci.artifact.manifest.v1+json",
> artifactType: "application/spdx+json",
> blobs: [
>   {
>     mediaType: "application/spdx+json",
>     descriptor: "sha256:ea706edf61ef640bcdf3c9ac9045c28446e6b2d08541b9ad614c7267d0b87375",
>     size: 19
>   }
> ]
> ```
> and just have some random text in the blob? Setting the `artifactType` and the `mediaType` to any value doesn't guarantee that the content is conformant to the spec for that value.

It doesn't, but if you pull the SBOM types that you recognize, then you personally have the tools to inspect the contents of the SBOM. If you pull SBOMs that you know you don't have the tools to process, then it's almost certainly a waste of time/bandwidth/storage.

> One more specific question. Using the signature example above, if my client needs to handle three different signatures: cosign, notary jws, and notary cose, what is the expectation for the manifests and their respective `artifactType` and `mediaType` values?

I expect one artifactType for notary, and a second for cosign. The blob mediaType would be up to each out those tools.

> Isn't this the equivalent of trusting a signature signed with a blue pen and signature signed with a red pen? The pen color is irrelevant. What is relevant is whether I trust the signature.

Or a file compressed with different compression tools, no point in downloading the compressed file if you don't have a decompression tool for that format.

**Comment by sudo-bmitch** [comment]
> @sudo-bmitch Sorry, one more thing re
> > I'm not concerned with multiple manifest pulls for each type of artifact, because manifests are small, and they can be pulled concurrently.
> 
> I actually am concerned about that because registries have throttling.

This is why I'm concerned with https://github.com/opencontainers/distribution-spec/pull/367. I don't think we'll see SBOMs and signatures on the SBOMs pulled for every node in a cluster running an image. Instead it will happen once when an image is being ingested by an organization. Hopefully we can limit this to only pulling the artifacts they need, rather than pulling every manifest to find the one signature that meets their policy.

**Comment by toddysm** [comment]
@sudo-bmitch Interesting... I am coming from the presumption that a single tool can handle more than one format. To use your analogy, I expect to be able to decompress RAR and ZIP with a single tool (and not being able to do that resulted in a lot of frustration on my side 😀). What I read is that a single tool should handle only a single format (7Zip for ZIP files only and WinRAR for RAR files only). Is this what you are suggesting, or did I understand it wrong?

And to make sure, we are talking about the manifests here and not the actual content - I don't need to download the archive if I know that I cannot handle it. However, I would like to know what archives are available to download (in a more efficient way) so that I can either error out or try to handle the archive I know how to handle.

**Comment by sudo-bmitch** [comment]
> What I read is that a single tool should handle only a single format

I'd say a single tool *may* handle a single format, and we shouldn't require that any new tools must handle every format. They should be able to support their new format by itself, and others that create universal interpreter tools can add to their supported artifact type list when their tool is updated. Since many of these formats are competing, an angry mob with pitchforks would descend on OCI if we required every artifact consuming tool to also support all of their competitors (and I avoid angry mobs).

> And to make sure, we are talking about the manifests here and not the actual content - I don't need to download the archive if I know that I cannot handle it.

If you query a remote registry for the content, whether it's one manifest or several for the SBOM, it should be almost identical (assuming there's enough detail in the referrers response to pick your desired manifest). But if you copy content between registries, you are forced to copy all blobs in a given manifest, even if you only wanted a single one. Almost every registry rejects a manifest if the blobs aren't pushed first. By separating manifests, end users can select which artifacts they want to mirror.

**Comment by toddysm** [comment]
Thanks for the reply @sudo-bmitch. Hope you had a nice holiday break. 

The general question I have related to the above examples - would it be possible to request both SBOM types in a single call to the referrer API or do those need to be separate always? I have some confusion about what the querying capabilities will be implemented in the API and what will be supported by every OCI compliant registry. The options I am looking at right now are:
- Have a generic `application/sbom` artifactType (all the above discussion)
- Send a request to the referrer API to give me both at the same time (reading the spec doesn't seem this will be possible - correct me if I am wrong)
- Have a common annotation and have the referrer API (I think this was the discussion in the last OCI meeting re indexing the annotations)

**Comment by sudo-bmitch** [comment]
> The options I am looking at right now are:
> 
>     * Have a generic `application/sbom` artifactType (all the above discussion)
> 
>     * Send a request to the referrer API to give me both at the same time (reading the spec doesn't seem this will be possible - correct me if I am wrong)
> 
>     * Have a common annotation and have the referrer API (I think this was the discussion in the last OCI meeting re indexing the annotations)

I'd go with option 4:

- Perform client side filtering. Query the API without an artifact type filter, and process all manifests that are supported by your tool from the list of everything.

Registries are not required to support artifact type filtering, so clients already need to have the ability to perform this themselves, plus the fallback has no server side filtering. And when you have a list of supported media types, it's just easier to get everything and do it client side rather than sending a list of API requests that will potentially fall back to responding with the full list multiple times.

**Comment by tianon** [comment]
Agreed, especially with #1101 now adding so much explicit detail. :+1:

@toddysm please do let us know if there's still something missing :bow:
